"use client";
import {useEffect,useRef,useState,type FormEvent} from "react";
import {translate,type Locale} from "@/lib/locale";
export function RecoveryCodes({locale,email}:{locale:Locale;email:string}){
 const t=(en:string,ar:string)=>translate(locale,en,ar),[count,setCount]=useState<number|null>(null),[codes,setCodes]=useState<string[]>([]),[busy,setBusy]=useState(false),[message,setMessage]=useState("");const working=useRef(false);
 useEffect(()=>{const c=new AbortController();fetch("/api/auth/recovery/codes",{signal:c.signal}).then(async r=>{if(!r.ok)throw new Error();const d=await r.json();if(!c.signal.aborted)setCount(d.count);}).catch(()=>{if(!c.signal.aborted)setMessage(t("Could not load recovery status. Refresh or sign in again.","تعذر تحميل حالة الاستعادة. حدّث الصفحة أو سجّل الدخول مجددًا."));});return()=>c.abort();},[locale]);
 async function generate(e:FormEvent<HTMLFormElement>){e.preventDefault();if(working.current)return;const form=e.currentTarget,currentPassword=String(new FormData(form).get("currentPassword"));working.current=true;setBusy(true);setCodes([]);setMessage("");try{const r=await fetch("/api/auth/recovery/codes",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({currentPassword})}),d=await r.json();if(r.ok){setCodes(d.codes);setCount(d.codes.length);form.reset();setMessage(t("Save these codes now. They cannot be displayed again.","احفظ هذه الرموز الآن، فلن تُعرض مرة أخرى."));}else setMessage(r.status===403?t("Current password is incorrect.","كلمة المرور الحالية غير صحيحة."):r.status===429?t("Too many attempts. Try again in 15 minutes.","محاولات كثيرة. جرّب بعد 15 دقيقة."):t("Could not generate codes. Sign in again and retry.","تعذر إنشاء الرموز. سجّل الدخول مجددًا وأعد المحاولة."));}catch{setCount(null);setMessage(t("Result could not be confirmed. Generate a new set to replace any codes saved by this request.","تعذر تأكيد النتيجة. أنشئ مجموعة جديدة لاستبدال أي رموز حُفظت بهذا الطلب."));}finally{working.current=false;setBusy(false);}}
 function download(){const file=new Blob([`Final Arrow ERP — Account recovery\n${email}\n\n${codes.join("\n")}\n\nKeep private and offline. Recovery or password changes invalidate every code.\n`],{type:"text/plain;charset=utf-8"}),url=URL.createObjectURL(file),a=document.createElement("a");a.href=url;a.download="final-arrow-erp-recovery-codes.txt";a.click();URL.revokeObjectURL(url);}
 return <section className="panel"><h2>{t("Account recovery codes","رموز استعادة الحساب")}</h2><p>{t("Generate ten private backup codes while you can sign in, then store them offline. A code plus your email can reset your password without email delivery. Anyone holding a code can access your account; keep them out of chat and shared files.","أنشئ عشرة رموز احتياطية خاصة أثناء قدرتك على الدخول، واحفظها خارج النظام. يمكنك استعادة كلمة المرور بالبريد الإلكتروني ورمز دون انتظار رسالة بريد. من يملك رمزًا يستطيع دخول حسابك؛ لا ترسل الرموز في المحادثات أو الملفات المشتركة.")}</p><p>{t("Generating a new set replaces all old codes. Recovery or any password change invalidates every code and closes all sessions. After signing in again, create a new set. Codes cannot be recovered if lost.","إنشاء مجموعة جديدة يلغي جميع الرموز القديمة. الاستعادة أو أي تغيير لكلمة المرور يلغي كل الرموز ويغلق جميع الجلسات. أنشئ مجموعة جديدة بعد تسجيل الدخول مجددًا. لا يمكن استرجاع الرموز المفقودة.")}</p>{count!==null&&<p>{t("Available codes","الرموز المتاحة")}: {count}</p>}
 <form onSubmit={e=>void generate(e)}><fieldset disabled={busy}><label>{t("Current password to replace recovery codes","كلمة المرور الحالية لاستبدال رموز الاستعادة")}<input type="password" name="currentPassword" autoComplete="current-password" required maxLength={1024}/></label><button>{t("Generate new codes and invalidate old ones","إنشاء رموز جديدة وإلغاء القديمة")}</button></fieldset></form>{message&&<p role="status">{message}</p>}{codes.length>0&&<section><pre dir="ltr">{codes.join("\n")}</pre><button onClick={download}>{t("Download private codes","تنزيل الرموز الخاصة")}</button><button onClick={()=>setCodes([])}>{t("I saved them; hide codes","حفظتها؛ إخفاء الرموز")}</button></section>}</section>;
}
