import {NextResponse} from "next/server";
import {z} from "zod";
import {db} from "@/lib/db";
import {currentUser} from "@/lib/auth";
import {RoleError,lockTenant,requireOwner,validatePermissions,protectedRoles,roleRevision} from "@/lib/role-management";
import {roleFailure} from "@/lib/role-management";
const schema=z.object({tenantId:z.string().uuid(),name:z.string().trim().min(2).max(80),permissions:z.array(z.string().min(1).max(80)).max(100),expectedRevision:z.string().regex(/^[a-f0-9]{64}$/)}).strict();
export async function PATCH(request:Request,{params}:{params:Promise<{id:string}>}){
 const actor=await currentUser();if(!actor)return NextResponse.json({error:"Unauthenticated"},{status:401});const {id}=await params,parsed=schema.safeParse(await request.json().catch(()=>null));if(!z.string().uuid().safeParse(id).success||!parsed.success)return NextResponse.json({error:"Invalid role"},{status:400});const {tenantId,name,permissions,expectedRevision}=parsed.data;
 try{await db.$transaction(async tx=>{await lockTenant(tx,tenantId);await requireOwner(tx,tenantId,actor.id);const role=await tx.role.findFirst({where:{tenantId,id},include:{permissions:{select:{permissionKey:true}}}});if(!role)throw new RoleError("Role not found",404);if(protectedRoles.includes(role.name))throw new RoleError("Built-in roles cannot be edited",403);if(roleRevision(role)!==expectedRevision)throw new RoleError("Role changed. Refresh before saving again");if(protectedRoles.some(n=>n.toLowerCase()===name.toLowerCase()))throw new RoleError("Built-in role names are reserved",400);if(await tx.role.findFirst({where:{tenantId,id:{not:id},name:{equals:name,mode:"insensitive"}}}))throw new RoleError("Role name is already in use");await validatePermissions(tx,tenantId,permissions);await tx.role.update({where:{id},data:{name}});await tx.rolePermission.deleteMany({where:{tenantId,roleId:id}});await tx.rolePermission.createMany({data:permissions.map(permissionKey=>({tenantId,roleId:id,permissionKey}))});await tx.auditLog.create({data:{tenantId,actorId:actor.id,action:"role.updated",entity:"Role",entityId:id,metadata:{before:{name:role.name,permissions:role.permissions.map(p=>p.permissionKey)},after:{name,permissions}}}});});return NextResponse.json({ok:true});}catch(e){return roleFailure(e);}
}
