"use client";
import {useState} from "react";
import {translate,type Locale} from "@/lib/locale";
type Summary={currency:string;assets:string;liabilities:string;equity:string;earnings:string;equityAndEarnings:string;difference:string;balanced:boolean};
type Result={to:string;scope:string;lineCount:number;summary:Summary[];rows:{accountId:string;code:string;name:string;type:string;currency:string;amount:string}[]};
export function BalanceSheet({scope,locale}:{scope:{tenantId:string;companyId:string;branches:{id:string;name:string}[]};locale:Locale}){
 const t=(en:string,ar:string)=>translate(locale,en,ar);const [result,setResult]=useState<Result|null>(null);const [query,setQuery]=useState("");const [error,setError]=useState("");const [busy,setBusy]=useState(false);
 const labels:Record<string,string>={ASSET:"أصول",LIABILITY:"التزامات",EQUITY:"حقوق ملكية",REVENUE:"إيرادات",EXPENSE:"مصروفات"};
 async function load(form:FormData){setBusy(true);setError("");setResult(null);setQuery("");const params=new URLSearchParams({tenantId:scope.tenantId,companyId:scope.companyId,to:String(form.get("to"))});const branch=String(form.get("branchId")||"");if(branch)params.set("branchId",branch);try{const r=await fetch(`/api/ledger/balance-sheet?${params}`);const data=await r.json();if(r.ok){setResult(data);setQuery(params.toString());}else setError(data.error);}catch{setError(t("Network request failed","فشل الاتصال بالشبكة"));}finally{setBusy(false);}}
 return <section className="panel"><h2>{t("Balance sheet — manual ledger","المركز المالي — الدفتر اليدوي")}</h2><p>{t("Includes all accessible posted journals through the selected entry date, up to 20000 lines. Remaining revenue/expense account balances form cumulative unclosed earnings, not annual profit. Closing journals move earnings into equity. No currency conversion or automatic document posting; this is not a complete statutory financial statement.","يشمل كل القيود المرحلة المتاحة حتى تاريخ القيد المحدد، بحد 20000 سطر. أرصدة الإيرادات والمصروفات المتبقية تشكل النتيجة المتراكمة غير المقفلة وليست ربح السنة. تنقل قيود الإقفال النتيجة لحقوق الملكية. لا يوجد تحويل عملات أو ترحيل تلقائي للمستندات؛ ليس قوائم مالية نظامية مكتملة.")}</p><form action={load}><label>{t("Through date","حتى تاريخ")} <input name="to" type="date" required/></label><label>{t("Branch","الفرع")} <select name="branchId"><option value="">{t("All accessible records","كل السجلات المتاحة")}</option>{scope.branches.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></label><button disabled={busy}>{t("Show report","عرض التقرير")}</button></form>{error&&<p role="status">{error}</p>}{result&&<><p>{result.to} · {result.scope==="COMPANY"?t("Company scope","نطاق الشركة"):t("Accessible branch scope","نطاق الفروع المتاحة")} · {result.lineCount} {t("lines","سطر")}</p><a href={`/api/ledger/balance-sheet?${query}&format=csv`}>{t("Download CSV","تنزيل CSV")}</a>{result.summary.map(g=><article className="card" key={g.currency}><strong>{g.currency} · {g.balanced?t("Balanced","متوازن"):t("Unbalanced","غير متوازن")}</strong><p>{t("Assets","الأصول")}: {g.assets} · {t("Liabilities","الالتزامات")}: {g.liabilities}</p><p>{t("Equity accounts","حسابات حقوق الملكية")}: {g.equity} · {t("Unclosed earnings","النتيجة غير المقفلة")}: {g.earnings}</p><p>{t("Equity including earnings","حقوق الملكية مع النتيجة")}: {g.equityAndEarnings} · {t("Balance difference","فرق التوازن")}: {g.difference}</p></article>)}<table><thead><tr><th>{t("Account","الحساب")}</th><th>{t("Type","النوع")}</th><th>{t("Balance","الرصيد")}</th><th>{t("Currency","العملة")}</th></tr></thead><tbody>{result.rows.map(r=><tr key={`${r.accountId}:${r.currency}`}><td>{r.code} · {r.name}</td><td>{t(r.type,labels[r.type])}</td><td>{r.amount}</td><td>{r.currency}</td></tr>)}</tbody></table>{!result.rows.length&&<p>{t("No posted movements.","لا توجد حركات مرحلة.")}</p>}</>}</section>;
}
