"use client";
import {useState} from "react";
import {translate,type Locale} from "@/lib/locale";
type Result={from:string;to:string;scope:string;lineCount:number;summary:{currency:string;revenue:string;expenses:string;netIncome:string}[];rows:{accountId:string;code:string;name:string;type:string;currency:string;debit:string;credit:string;amount:string}[]};
export function IncomeStatement({scope,locale}:{scope:{tenantId:string;companyId:string;branches:{id:string;name:string}[]};locale:Locale}){
 const t=(en:string,ar:string)=>translate(locale,en,ar);const [result,setResult]=useState<Result|null>(null);const [query,setQuery]=useState("");const [error,setError]=useState("");const [busy,setBusy]=useState(false);
 async function load(form:FormData){setBusy(true);setError("");setResult(null);setQuery("");const params=new URLSearchParams({tenantId:scope.tenantId,companyId:scope.companyId,from:String(form.get("from")),to:String(form.get("to"))});const branch=String(form.get("branchId")||"");if(branch)params.set("branchId",branch);try{const response=await fetch(`/api/ledger/income-statement?${params}`);const data=await response.json();if(response.ok){setResult(data);setQuery(params.toString());}else setError(data.error);}catch{setError(t("Network request failed","فشل الاتصال بالشبكة"));}finally{setBusy(false);}}
 return <section className="panel"><h2>{t("Income statement","قائمة الدخل")}</h2><p>{t("Uses posted manual journals only. Revenue is credit minus debit; expenses are debit minus credit. Reversals and closing journals affect the period. Invoices, payroll, POS and expense documents do not post automatically. This is not a complete statutory financial statement.","يعتمد القيود اليدوية المرحلة فقط. الإيراد هو الدائن ناقص المدين، والمصروف هو المدين ناقص الدائن. القيود العكسية وقيود الإقفال تؤثر على الفترة. الفواتير والرواتب ونقاط البيع ومستندات المصاريف لا ترحّل تلقائياً. لا يمثل هذا التقرير قوائم مالية نظامية مكتملة.")}</p><p>{t("Maximum 366 days and 20000 income/expense lines. Each currency is reported separately.","حتى 366 يوماً و20000 سطر إيراد أو مصروف. كل عملة منفصلة.")}</p><form action={load}><label>{t("From","من")} <input type="date" name="from" required/></label><label>{t("To","إلى")} <input type="date" name="to" required/></label><label>{t("Branch","الفرع")} <select name="branchId"><option value="">{t("All accessible records","كل السجلات المتاحة")}</option>{scope.branches.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></label><button disabled={busy}>{t("Show report","عرض التقرير")}</button></form>{error&&<p role="status">{error}</p>}{result&&<><p>{result.from} — {result.to} · {result.scope==="COMPANY"?t("Company scope","نطاق الشركة"):t("Accessible branch scope","نطاق الفروع المتاحة")} · {result.lineCount} {t("lines","سطر")}</p><a href={`/api/ledger/income-statement?${query}&format=csv`}>{t("Download CSV","تنزيل CSV")}</a>{result.summary.map(g=><article className="card" key={g.currency}><strong>{g.currency}</strong><p>{t("Revenue","الإيرادات")}: {g.revenue} · {t("Expenses","المصروفات")}: {g.expenses} · {t("Net income / loss","صافي الربح / الخسارة")}: {g.netIncome}</p></article>)}<div style={{overflowX:"auto"}}><table><thead><tr>{[t("Account","الحساب"),t("Type","النوع"),t("Debit","مدين"),t("Credit","دائن"),t("Net amount","صافي المبلغ"),t("Currency","العملة")].map(label=><th key={label}>{label}</th>)}</tr></thead><tbody>{result.rows.map(r=><tr key={`${r.accountId}:${r.currency}`}><td>{r.code} · {r.name}</td><td>{r.type==="REVENUE"?t("Revenue","إيراد"):t("Expense","مصروف")}</td><td>{r.debit}</td><td>{r.credit}</td><td>{r.amount}</td><td>{r.currency}</td></tr>)}</tbody></table></div>{!result.rows.length&&<p>{t("No posted revenue or expense movements.","لا توجد حركات إيراد أو مصروف مرحلة.")}</p>}</>}</section>;
}
