"use client";
import {useState} from "react";
import {translate,type Locale} from "@/lib/locale";
type Result={from:string;to:string;account:{code:string;name:string};summary:{currency:string;opening:string;debit:string;credit:string;closing:string}[];rows:{id:string;number:string;date:string;description:string;currency:string;debit:string;credit:string;balance:string;reversal:boolean}[]};
export function AccountStatement({scope,accounts,locale}:{scope:{tenantId:string;companyId:string;branches:{id:string;name:string}[]};accounts:{id:string;code:string;name:string}[];locale:Locale}){
 const t=(en:string,ar:string)=>translate(locale,en,ar);const [result,setResult]=useState<Result|null>(null);const [query,setQuery]=useState("");const [error,setError]=useState("");const [busy,setBusy]=useState(false);const [limit,setLimit]=useState(100);
 async function load(form:FormData){setBusy(true);setError("");setResult(null);setQuery("");setLimit(100);const params=new URLSearchParams({tenantId:scope.tenantId,companyId:scope.companyId,accountId:String(form.get("accountId")),from:String(form.get("from")),to:String(form.get("to"))});const branch=String(form.get("branchId")||"");if(branch)params.set("branchId",branch);try{const r=await fetch(`/api/ledger/account-statement?${params}`);const data=await r.json();if(r.ok){setResult(data);setQuery(params.toString());}else setError(data.error);}catch{setError(t("Network request failed","فشل الاتصال بالشبكة"));}finally{setBusy(false);}}
 return <section className="panel"><h2>{t("Account statement","كشف حركة الحساب")}</h2><p>{t("Balances are debit minus credit, separately for each currency. Earlier visible journals form the opening balance; reversals remain included. Maximum 366 days, 5000 period lines and 20000 earlier lines.","الرصيد يساوي المدين ناقص الدائن لكل عملة منفصلة. القيود السابقة المتاحة تشكل رصيد البداية، وتبقى القيود العكسية ضمن الكشف. الحد 366 يوماً و5000 سطر في الفترة و20000 سطر سابق.")}</p><form action={load}><label>{t("Account","الحساب")} <select name="accountId" required><option value="">{t("Select account","اختر الحساب")}</option>{accounts.map(a=><option key={a.id} value={a.id}>{a.code} · {a.name}</option>)}</select></label><label>{t("From","من")} <input type="date" name="from" required/></label><label>{t("To","إلى")} <input type="date" name="to" required/></label><label>{t("Branch","الفرع")} <select name="branchId"><option value="">{t("All accessible records","كل السجلات المتاحة")}</option>{scope.branches.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></label><button disabled={busy}>{t("Show statement","عرض الكشف")}</button></form>{error&&<p role="status">{error}</p>}{result&&<><h3>{result.account.code} · {result.account.name}</h3><p>{result.from} — {result.to}</p><a href={`/api/ledger/account-statement?${query}&format=csv`}>{t("Download CSV","تنزيل CSV")}</a>{result.summary.map(g=><article className="card" key={g.currency}><strong>{g.currency}</strong><p>{t("Opening","رصيد البداية")}: {g.opening} · {t("Debit","مدين")}: {g.debit} · {t("Credit","دائن")}: {g.credit} · {t("Closing","رصيد النهاية")}: {g.closing}</p></article>)}<div style={{overflowX:"auto"}}><table><thead><tr>{[t("Date","التاريخ"),t("Number","الرقم"),t("Description","الوصف"),t("Debit","مدين"),t("Credit","دائن"),t("Balance","الرصيد"),t("Currency","العملة")].map(label=><th key={label}>{label}</th>)}</tr></thead><tbody>{result.rows.slice(0,limit).map(r=><tr key={r.id}><td>{r.date}</td><td>{r.number}{r.reversal&&` · ${t("Reversal","عكسي")}`}</td><td>{r.description}</td><td>{r.debit}</td><td>{r.credit}</td><td>{r.balance}</td><td>{r.currency}</td></tr>)}</tbody></table></div>{limit<result.rows.length&&<button onClick={()=>setLimit(n=>n+100)}>{t("Load more","تحميل المزيد")}</button>}{!result.rows.length&&<p>{t("No movements in this period.","لا توجد حركات في هذه الفترة.")}</p>}</>}</section>;
}
