import test from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {spawn} from 'node:child_process';
import {PrismaClient} from '@prisma/client';
const origin='http://127.0.0.1:3227';
async function call(path,method='GET',body,cookie){const r=await fetch(origin+path,{method,headers:{'Content-Type':'application/json',...(cookie?{Cookie:cookie}:{})},...(body?{body:JSON.stringify(body)}:{})});return {status:r.status,data:await r.json(),cookie:r.headers.get('set-cookie')?.split(';')[0]};}
test('bank statements and matches are exact, immutable, scoped, reversible and balance-aware',{timeout:90000},async()=>{
 const db=new PrismaClient(),server=spawn('./node_modules/.bin/next',['start','-p','3227'],{env:{...process.env,ALLOW_REGISTRATION:'true'},stdio:['ignore','ignore','inherit']});
 try{
  let ready=false;for(let i=0;i<60;i++){try{if((await fetch(origin)).ok){ready=true;break;}}catch{}await new Promise(r=>setTimeout(r,500));}assert.ok(ready);
  async function owner(){const s=randomUUID().slice(0,8),r=await call('/api/auth/register','POST',{name:'Bank QA',email:`bank-${s}@example.invalid`,password:'Bank-reconciliation-2026',organization:'Bank QA',slug:`bank-${s}`});assert.equal(r.status,201);return r;}
  const actor=await owner(),outsider=await owner(),tenantId=actor.data.tenantId,cookie=actor.cookie;
  const create=async(path,body)=>{const r=await call(path,'POST',{tenantId,...body},cookie);assert.equal(r.status,201,JSON.stringify(r.data));return r.data;};
  const {company}=await create('/api/companies',{name:'Bank company',code:'BANK',baseCurrency:'OMR'}),companyId=company.id;
  const {branch}=await create('/api/branches',{companyId,name:'Main',code:'MAIN'});
  const account=async(code,type)=>(await create('/api/ledger/accounts',{companyId,code,name:code,type})).account;
  const bank=await account('1010','ASSET'),otherBank=await account('1020','ASSET'),revenue=await account('4000','REVENUE');
  const day=new Date().toISOString().slice(0,10),before=new Date(Date.parse(day)-86400000).toISOString().slice(0,10),after=new Date(Date.parse(day)+86400000).toISOString().slice(0,10),future=new Date(Date.parse(day)+172800000).toISOString().slice(0,10);
  async function journal(number,amount,date=day,accountId=bank.id){const incoming=!amount.startsWith('-'),abs=amount.replace('-','');const {entry}=await create('/api/ledger/journals',{companyId,branchId:branch.id,number,entryDate:date,description:number,lines:[{accountId,debit:incoming?abs:'0',credit:incoming?'0':abs},{accountId:revenue.id,debit:incoming?'0':abs,credit:incoming?abs:'0'}]});return {...entry,bankLine:entry.lines.find(l=>l.accountId===accountId)};}
  const opening=await journal('BANK-OPEN','100',before),pastIn=await journal('BANK-PAST-IN','1',before),pastOut=await journal('BANK-PAST-OUT','-1',before),receipt=await journal('BANK-IN','10.125'),payment=await journal('BANK-OUT','-3.125'),transitIn=await journal('BANK-TRANSIT-IN','2'),transitOut=await journal('BANK-TRANSIT-OUT','-1'),other=await journal('BANK-OTHER','10.125',day,otherBank.id),futureEntry=await journal('BANK-FUTURE','10.125',future);
  async function viewer(type){const invite=await create('/api/invitations',{email:`bank-view-${randomUUID().slice(0,8)}@example.invalid`,role:'Viewer',scope:{type,companyId,...(type==='BRANCH'?{branchId:branch.id}:{})}});const r=await call('/api/invitations/accept','POST',{token:invite.path.split('/').at(-1),name:'Bank viewer',password:'Bank-viewer-password-2026'});assert.equal(r.status,200);return r.cookie;}
  const viewerCookie=await viewer('COMPANY'),branchCookie=await viewer('BRANCH'),viewerRole=await db.role.findUnique({where:{tenantId_name:{tenantId,name:'Viewer'}}});await db.rolePermission.create({data:{tenantId,roleId:viewerRole.id,permissionKey:'ledger:read'}});
  const payload={tenantId,companyId,requestId:randomUUID(),accountId:bank.id,reference:'BANK-CURRENT',from:day,to:after,opening:'100.000',closing:'107.000',lines:[{bookingDate:day,reference:'Bank receipt',amount:'10.125'},{bookingDate:after,reference:'Bank payment',amount:'-3.125'}]};
  assert.equal((await call('/api/bank/statements','POST',payload)).status,401);assert.equal((await call('/api/bank/statements','POST',payload,outsider.cookie)).status,403);assert.equal((await call('/api/bank/statements','POST',payload,viewerCookie)).status,403);assert.equal((await call(`/api/bank/statements?tenantId=${tenantId}&companyId=${companyId}`,'GET',undefined,branchCookie)).status,403);
  for(const changed of [{closing:'108'},{lines:[{bookingDate:before,reference:'Outside dates',amount:'7'}]},{lines:[{bookingDate:day,reference:'Zero movement',amount:'0'}]},{from:after,to:day}])assert.equal((await call('/api/bank/statements','POST',{...payload,...changed},cookie)).status,400);
  assert.equal((await call('/api/bank/statements','POST',{...payload,accountId:revenue.id},cookie)).status,404);
  const duplicated=await Promise.all([call('/api/bank/statements','POST',payload,cookie),call('/api/bank/statements','POST',payload,cookie)]);assert.ok(duplicated.every(r=>r.status===201),JSON.stringify(duplicated));assert.equal(duplicated[0].data.id,duplicated[1].data.id);const id=duplicated[0].data.id,path=`/api/bank/statements/${id}`;
  assert.equal((await call('/api/bank/statements','POST',{...payload,closing:'108',lines:[{bookingDate:day,reference:'Other receipt',amount:'8'}]},cookie)).status,409);
  assert.equal((await call('/api/bank/statements','POST',{...payload,requestId:randomUUID(),reference:'OVERLAP'},cookie)).status,409);
  const get=()=>call(path+`?tenantId=${tenantId}`,'GET',undefined,cookie);let state=(await get()).data;assert.equal(state.bookClosing,'108.000');assert.equal(state.reconciled,false);assert.equal(state.pendingBank,2);assert.equal((await call(path+`?tenantId=${tenantId}`,'GET',undefined,viewerCookie)).status,200);assert.equal((await call(path+`?tenantId=${tenantId}`,'GET',undefined,branchCookie)).status,403);
  const bankIn=state.statement.lines.find(l=>l.amount==='10.125'),bankOut=state.statement.lines.find(l=>l.amount==='-3.125'),match={tenantId,action:'match',requestId:randomUUID(),bankLineId:bankIn.id,journalLineId:receipt.bankLine.id};
  assert.equal((await call(path+'/matches','POST',match,viewerCookie)).status,403);
  for(const line of [payment.bankLine,other.bankLine,futureEntry.bankLine])assert.ok([404,409].includes((await call(path+'/matches','POST',{...match,journalLineId:line.id},cookie)).status));
  await assert.rejects(db.bankMatch.create({data:{id:randomUUID(),tenantId,companyId,accountId:bank.id,bankLineId:bankIn.id,journalLineId:payment.bankLine.id,createdBy:opening.createdBy}}));
  const racing=await Promise.all([call(path+'/matches','POST',match,cookie),call(path+'/matches','POST',{...match,requestId:randomUUID()},cookie)]);assert.deepEqual(racing.map(r=>r.status).sort(),[201,409]);const saved=racing.find(r=>r.status===201).data.match;const retry={...match,requestId:saved.id};assert.equal((await call(path+'/matches','POST',retry,cookie)).status,201);assert.equal((await call(path+'/matches','POST',{...retry,journalLineId:transitIn.bankLine.id},cookie)).status,409);
  assert.equal((await call(path+'/matches','POST',{tenantId,action:'match',requestId:randomUUID(),bankLineId:bankOut.id,journalLineId:payment.bankLine.id},cookie)).status,201);
  state=(await get()).data;assert.equal(state.pendingBank,0);assert.equal(state.difference,'-100.000');assert.equal(state.reconciled,false);
  const past=await create('/api/bank/statements',{...payload,requestId:randomUUID(),reference:'BANK-OPENING',from:before,to:before,opening:'0',closing:'100',lines:[{bookingDate:before,reference:'Opening deposit',amount:'100'},{bookingDate:before,reference:'Past in',amount:'1'},{bookingDate:before,reference:'Past out',amount:'-1'}]});const pastPath=`/api/bank/statements/${past.id}`,pastState=(await call(pastPath+`?tenantId=${tenantId}`,'GET',undefined,cookie)).data;
  for(const [amount,entry] of [['100.000',opening]])assert.equal((await call(pastPath+'/matches','POST',{tenantId,action:'match',requestId:randomUUID(),bankLineId:pastState.statement.lines.find(l=>l.amount===amount).id,journalLineId:entry.bankLine.id},cookie)).status,201);
  state=(await get()).data;assert.equal(state.bookClosing,'108.000');assert.equal(state.outstandingTotal,'1.000');assert.equal(state.adjustedBank,'108.000');assert.equal(state.difference,'0.000');assert.equal(state.pendingBank,2);assert.equal(state.reconciled,false,'zero difference cannot hide unmatched earlier offsetting bank movements');
  for(const [amount,entry] of [['1.000',pastIn],['-1.000',pastOut]])assert.equal((await call(pastPath+'/matches','POST',{tenantId,action:'match',requestId:randomUUID(),bankLineId:pastState.statement.lines.find(l=>l.amount===amount).id,journalLineId:entry.bankLine.id},cookie)).status,201);
  state=(await get()).data;assert.equal(state.pendingBank,0);assert.equal(state.reconciled,true);assert.equal(state.outstanding.length,2);assert.ok(state.outstanding.some(l=>l.id===transitOut.bankLine.id));
  assert.equal((await call(pastPath+'/matches','POST',retry,cookie)).status,409,'exact retries cannot move to another statement');
  await assert.rejects(db.bankMatch.update({where:{id:saved.id},data:{cancelledAt:new Date(),cancelledBy:opening.createdBy,cancelReason:null}}));
  const cancel={tenantId,action:'cancel',matchId:saved.id,reason:'Wrong bank reference'};const cancelled=await call(path+'/matches','POST',cancel,cookie);assert.equal(cancelled.status,201);assert.ok(cancelled.data.match.cancelledAt);assert.equal((await call(path+'/matches','POST',cancel,cookie)).status,201);assert.equal((await call(path+'/matches','POST',{...cancel,reason:'Changed cancellation'},cookie)).status,409);assert.equal((await call(path+'/matches','POST',retry,cookie)).data.match.cancelledAt,cancelled.data.match.cancelledAt);assert.equal((await get()).data.pendingBank,1);assert.equal((await get()).data.reconciled,false);
  const rematched=await call(path+'/matches','POST',{...match,requestId:randomUUID()},cookie);assert.equal(rematched.status,201);assert.equal((await get()).data.reconciled,true);
  await assert.rejects(db.bankMatch.delete({where:{id:saved.id}}));await assert.rejects(db.bankMatch.update({where:{id:saved.id},data:{cancelledAt:null,cancelledBy:null,cancelReason:null}}));await assert.rejects(db.bankStatement.update({where:{id},data:{reference:'Changed'}}));await assert.rejects(db.bankStatementLine.update({where:{id:bankIn.id},data:{amount:'11'}}));await assert.rejects(db.$transaction(async tx=>{await tx.bankStatementLine.createMany({data:[{id:randomUUID(),tenantId,companyId,accountId:bank.id,statementId:id,position:3,bookingDate:new Date(day),reference:'Late positive',amount:'1'},{id:randomUUID(),tenantId,companyId,accountId:bank.id,statementId:id,position:4,bookingDate:new Date(day),reference:'Late negative',amount:'-1'}]});}));
  const badId=randomUUID();await assert.rejects(db.$transaction(async tx=>{await tx.bankStatement.create({data:{id:badId,tenantId,companyId,accountId:otherBank.id,reference:'BAD-TOTAL',from:new Date(day),to:new Date(day),opening:'0',closing:'5',currency:'OMR',requestHash:'a'.repeat(64),createdBy:opening.createdBy}});}));assert.equal(await db.bankStatement.count({where:{id:badId}}),0);
  assert.equal((await call('/api/ledger/period-lock','PATCH',{tenantId,companyId,lockedThrough:after,expectedLockedThrough:null,reason:'Close bank book period'},cookie)).status,200);assert.equal((await call(path+'/matches','POST',{...cancel,matchId:rematched.data.match.id},cookie)).status,201,'a fresh cancellation works after ledger period close');assert.equal((await call(path+'/matches','POST',{...match,requestId:randomUUID()},cookie)).status,201,'a fresh match works after ledger period close');
  for(const url of ['/accounting/bank',`/accounting/bank/${id}`]){const r=await fetch(origin+url,{headers:{Cookie:cookie}});assert.equal(r.status,200,url);assert.match(await r.text(),/FINAL|Final Arrow/);}
  assert.equal((await fetch(origin+`/accounting/bank/${id}`,{headers:{Cookie:branchCookie}})).status,404);
  const voidBody={tenantId,action:'void',reason:'Correct imported statement reference'};
  assert.equal((await call(path+'/void','POST',voidBody,viewerCookie)).status,403);assert.equal((await call(path+'/void','POST',voidBody,cookie)).status,409);
  state=(await get()).data;for(const line of state.statement.lines)for(const m of line.matches)assert.equal((await call(path+'/matches','POST',{tenantId,action:'cancel',matchId:m.id,reason:'Replace incorrect statement'},cookie)).status,201);
  await assert.rejects(db.bankStatement.update({where:{id},data:{voidedAt:new Date(),voidedBy:opening.createdBy,voidReason:null}}));
  assert.equal((await call(path+'/void','POST',voidBody,cookie)).status,201);assert.equal((await call(path+'/void','POST',voidBody,cookie)).status,201);assert.equal((await call(path+'/void','POST',{...voidBody,reason:'Changed void reason'},cookie)).status,409);
  assert.equal((await call(path+'/matches','POST',{...match,requestId:randomUUID()},cookie)).status,409);await assert.rejects(db.bankMatch.create({data:{id:randomUUID(),tenantId,companyId,accountId:bank.id,bankLineId:bankIn.id,journalLineId:receipt.bankLine.id,createdBy:opening.createdBy}}));
  await assert.rejects(db.bankStatement.update({where:{id},data:{voidedAt:null,voidedBy:null,voidReason:null}}));await assert.rejects(db.bankStatement.delete({where:{id}}));
  state=(await get()).data;assert.ok(state.statement.voidedAt);assert.equal(state.reconciled,false);assert.equal(state.pendingBank,0);
  assert.equal((await call('/api/bank/statements','POST',{...payload,requestId:randomUUID()},cookie)).status,409,'voided references remain reserved');
  const replacement=await create('/api/bank/statements',{...payload,requestId:randomUUID(),reference:'BANK-CORRECTED'});assert.notEqual(replacement.id,id);assert.equal((await get()).data.pendingBank,2);assert.equal(await db.bankStatement.count({where:{tenantId}}),3);
  assert.equal(await db.auditLog.count({where:{tenantId,action:'bank-statement.imported'}}),3);assert.equal(await db.auditLog.count({where:{tenantId,action:'bank-match.cancelled'}}),4);assert.equal(await db.auditLog.count({where:{tenantId,action:'bank-statement.voided'}}),1);assert.equal(await db.bankMatch.count({where:{tenantId}}),7);
 }finally{server.kill('SIGTERM');await db.$disconnect();}
});
