import assert from "node:assert/strict";
import test from "node:test";
import { randomUUID } from "node:crypto";
import { spawn } from "node:child_process";
import { PrismaClient } from "@prisma/client";

const origin="http://127.0.0.1:3218";
async function call(path,method="GET",body,cookie) {
  const r=await fetch(origin+path,{method,headers:{"Content-Type":"application/json",...(cookie?{Cookie:cookie}:{})},...(body?{body:JSON.stringify(body)}:{})});
  return {status:r.status,data:await r.json(),cookie:r.headers.get("set-cookie")?.split(";")[0]};
}
test("document posting is exact, scoped, single-use and reversal-safe",{timeout:90000},async()=>{
  // CI-only fixtures: use the isolated PostgreSQL service, never the live ERP.
  const db=new PrismaClient();
  const server=spawn("./node_modules/.bin/next",["start","-p","3218"],{env:{...process.env,ALLOW_REGISTRATION:"true"},stdio:["ignore","ignore","inherit"]});
  try {
    let ready=false;
    for(let i=0;i<60;i++){try{if((await fetch(origin)).ok){ready=true;break;}}catch{}await new Promise(r=>setTimeout(r,500));}
    assert.ok(ready);
    async function owner(){const suffix=randomUUID().slice(0,8);const r=await call("/api/auth/register","POST",{name:"Posting QA",email:`posting-${suffix}@example.invalid`,password:"Long-test-password-2026",organization:"Posting QA",slug:`posting-${suffix}`});assert.equal(r.status,201);return r;}
    const actor=await owner(),outsider=await owner();const tenantId=actor.data.tenantId,cookie=actor.cookie;
    const create=async(path,body)=>{const r=await call(path,"POST",{tenantId,...body},cookie);assert.equal(r.status,201,JSON.stringify(r.data));return r.data;};
    const {company}=await create("/api/companies",{name:"Posting company",code:"POST",baseCurrency:"OMR"});
    const {company:other}=await create("/api/companies",{name:"Other company",code:"OTHER"});
    const companyId=company.id;
    async function account(code,type,company=companyId){return (await create("/api/ledger/accounts",{companyId:company,code,name:code,type})).account;}
    const asset=await account("ASSET","ASSET"),revenue=await account("REVENUE","REVENUE"),expenseAccount=await account("COST","EXPENSE"),foreign=await account("FOREIGN","ASSET",other.id);
    const {customer}=await create("/api/customers",{companyId,code:"CUST",displayName:"Posting customer"});
    const {quote}=await create("/api/quotes",{companyId,customerId:customer.id,number:"QUOTE-POST",lines:[{description:"Service",quantity:3,unitPrice:"2.125"}]});
    for(const action of ["send","accept"])assert.equal((await call(`/api/quotes/${quote.id}/status`,"PATCH",{tenantId,action},cookie)).status,200);
    const {order}=await create(`/api/quotes/${quote.id}/order`,{number:"ORDER-POST"});
    for(const action of ["start","complete"])assert.equal((await call(`/api/orders/${order.id}/status`,"PATCH",{tenantId,action},cookie)).status,200);
    const {invoice}=await create(`/api/orders/${order.id}/invoice`,{number:"INV-POST"});
    const day=new Date().toISOString().slice(0,10);
    const invoicePath=`/api/ledger/documents/invoice/${invoice.id}`;
    const body={tenantId,entryDate:day,debitAccountId:asset.id,creditAccountId:revenue.id};
    assert.equal((await call(invoicePath,"POST",body)).status,401);
    assert.equal((await call(invoicePath,"POST",body,outsider.cookie)).status,403);
    assert.equal((await call(invoicePath,"POST",body,cookie)).status,409,"draft cannot post");
    assert.equal((await call(`/api/invoices/${invoice.id}/status`,"PATCH",{tenantId,action:"issue"},cookie)).status,200);
    assert.equal((await call(invoicePath,"POST",{...body,debitAccountId:foreign.id},cookie)).status,409);
    assert.equal((await call(invoicePath,"POST",{...body,creditAccountId:asset.id},cookie)).status,409);
    assert.equal((await call(invoicePath,"POST",{...body,entryDate:"2020-01-01"},cookie)).status,409);
    await db.company.update({where:{id:companyId},data:{ledgerLockedThrough:new Date(`${day}T00:00:00Z`)}});
    assert.equal((await call(invoicePath,"POST",body,cookie)).status,409,"closed period");
    await db.company.update({where:{id:companyId},data:{ledgerLockedThrough:null}});
    const competing=await Promise.all([call(invoicePath,"POST",body,cookie),call(invoicePath,"POST",body,cookie)]);
    assert.deepEqual(competing.map(r=>r.status).sort(),[201,409]);
    const journal=competing.find(r=>r.status===201).data.entry;
    assert.equal(journal.number.length,30);
    const saved=await db.journalEntry.findUnique({where:{id:journal.id},include:{lines:{orderBy:{position:"asc"}}}});
    assert.equal(saved.total.toFixed(3),"6.375");assert.equal(saved.lines[0].debit.toFixed(3),"6.375");assert.equal(saved.lines[1].credit.toFixed(3),"6.375");
    assert.equal((await call(invoicePath+`?tenantId=${tenantId}`,"GET",undefined,cookie)).data.entry.id,journal.id);
    assert.equal((await call(`/api/invoices/${invoice.id}/status`,"PATCH",{tenantId,action:"void",reason:"Correction"},cookie)).status,409);
    assert.equal((await call(`/api/ledger/journals/${journal.id}/reverse`,"POST",{tenantId,number:"REV-INVOICE",entryDate:day,reason:"Correction"},cookie)).status,201);
    assert.equal((await call(`/api/invoices/${invoice.id}/status`,"PATCH",{tenantId,action:"void",reason:"Correction"},cookie)).status,200);
    assert.equal((await call(invoicePath,"POST",body,cookie)).status,409);
    const {expense}=await create("/api/expenses",{companyId,number:"EXP-POST",description:"Supplies",category:"Office",amount:"8.125",expenseDate:day});
    const expensePath=`/api/ledger/documents/expense/${expense.id}`;
    const expenseBody={...body,debitAccountId:expenseAccount.id,creditAccountId:asset.id};
    assert.equal((await call(expensePath,"POST",expenseBody,cookie)).status,409);
    assert.equal((await call(`/api/expenses/${expense.id}/status`,"PATCH",{tenantId,action:"post"},cookie)).status,200);
    const posted=await call(expensePath,"POST",expenseBody,cookie);assert.equal(posted.status,201,JSON.stringify(posted.data));
    assert.equal((await call(`/api/expenses/${expense.id}/status`,"PATCH",{tenantId,action:"void",reason:"Correction"},cookie)).status,409);
    assert.equal((await call(`/api/ledger/journals/${posted.data.entry.id}/reverse`,"POST",{tenantId,number:"REV-EXPENSE",entryDate:day,reason:"Correction"},cookie)).status,201);
    assert.equal((await call(`/api/expenses/${expense.id}/status`,"PATCH",{tenantId,action:"void",reason:"Correction"},cookie)).status,200);
    assert.equal((await call(expensePath,"POST",expenseBody,cookie)).status,409);
    const {branch}=await create("/api/branches",{companyId,name:"Main",code:"MAIN"});
    const {item}=await create("/api/pos/items",{companyId,branchId:branch.id,code:"FOOD",name:"Meal",category:"Food",price:"3.125"});
    const {order:posOrder}=await create("/api/pos/orders",{companyId,branchId:branch.id,number:"POS-POST",type:"TAKEAWAY",lines:[{itemId:item.id,quantity:2}]});
    const posPath=`/api/ledger/documents/pos/${posOrder.id}`;
    assert.equal((await call(posPath,"POST",body,cookie)).status,409,"open POS cannot post");
    assert.equal((await call(`/api/pos/orders/${posOrder.id}`,"PATCH",{tenantId,action:"pay",method:"CASH",tendered:"10.000"},cookie)).status,200);
    const posPosted=await call(posPath,"POST",body,cookie);assert.equal(posPosted.status,201,JSON.stringify(posPosted.data));
    const posJournal=await db.journalEntry.findUnique({where:{id:posPosted.data.entry.id}});
    assert.equal(posJournal.total.toFixed(3),"6.250","post revenue, not cash tendered");assert.equal(posJournal.branchId,branch.id);
    assert.equal((await call(posPath,"POST",body,cookie)).status,409);
    assert.equal((await call(`/api/ledger/journals/${posJournal.id}/reverse`,"POST",{tenantId,number:"REV-POS",entryDate:day,reason:"QA correction"},cookie)).status,201);
    const {item:stockItem}=await create("/api/inventory/items",{companyId,branchId:branch.id,sku:"STOCK-REV",name:"Stock reversal item",unit:"kg"});
    const stockScope={tenantId,companyId,branchId:branch.id,itemId:stockItem.id};
    const stockQuery=new URLSearchParams({tenantId,companyId,branchId:branch.id});
    const stock=async()=> (await call(`/api/inventory/stock?${stockQuery}`,"GET",undefined,cookie)).data;
    await create("/api/inventory/stock",{...stockScope,action:"in",quantity:"10.125",reason:"Opening balance"});
    const incoming=(await stock()).movements[0];
    await create("/api/inventory/stock",{...stockScope,action:"out",quantity:"3.125",reason:"Stock issued"});
    const outgoing=(await stock()).movements[0];
    const reverse=async(id,actor=cookie)=>call(`/api/inventory/movements/${id}/reverse`,"POST",{tenantId,reason:"QA correction"},actor);
    assert.equal((await reverse(incoming.id,outsider.cookie)).status,403);
    assert.equal((await reverse(incoming.id)).status,409,"cannot return more stock than remains");
    const outReversed=await reverse(outgoing.id);assert.equal(outReversed.status,201,JSON.stringify(outReversed.data));
    assert.equal(outReversed.data.balance.quantity,"10.125");
    assert.equal((await reverse(outReversed.data.movement.id)).status,409,"cannot reverse a reversal");
    const stockCompeting=await Promise.all([reverse(incoming.id),reverse(incoming.id)]);
    assert.deepEqual(stockCompeting.map(r=>r.status).sort(),[201,409]);
    assert.equal((await stock()).balances.find(b=>b.itemId===stockItem.id).quantity,"0");
    assert.equal((await stock()).movements.find(m=>m.id===incoming.id).reversed,true);
    assert.equal((await stock()).movements.find(m=>m.id===outReversed.data.movement.id).isReversal,true);
    const {supplier}=await create("/api/suppliers",{companyId,branchId:branch.id,code:"SUP-REV",displayName:"Return supplier"});
    const {order:purchase}=await create("/api/purchase-orders",{companyId,branchId:branch.id,supplierId:supplier.id,number:"PO-REV",lines:[{description:"Stock item",quantity:2,unitPrice:"1.000"}]});
    assert.equal((await call(`/api/purchase-orders/${purchase.id}/status`,"PATCH",{tenantId,action:"issue"},cookie)).status,200);
    await create(`/api/purchase-orders/${purchase.id}/receive`,{branchId:branch.id,lines:[{orderLineId:purchase.lines[0].id,itemId:stockItem.id}]});
    const receiptMovement=(await stock()).movements.find(m=>m.type==="PURCHASE_RECEIPT");assert.ok(receiptMovement);
    const returned=await reverse(receiptMovement.id);assert.equal(returned.status,201,JSON.stringify(returned.data));
    assert.equal(returned.data.balance.quantity,"0");
    assert.equal((await reverse(receiptMovement.id)).status,409);
    assert.equal((await db.purchaseOrder.findUnique({where:{id:purchase.id}})).status,"RECEIVED","preserve original receipt history");
    const receiptQuery=new URLSearchParams({tenantId,companyId});
    const receiptList=await call(`/api/purchase-orders/receipts?${receiptQuery}`,"GET",undefined,cookie);
    assert.equal(receiptList.status,200);assert.equal(receiptList.data.receipts.length,1);
    const receiptId=receiptList.data.receipts[0].id;
    assert.equal(receiptList.data.receipts[0].order.id,purchase.id);assert.equal(receiptList.data.receipts[0]._count.lines,1);
    assert.equal((await call(`/api/purchase-orders/receipts?${receiptQuery}`,"GET",undefined,outsider.cookie)).status,403);
    assert.equal((await call(`/api/purchase-orders/receipts?${receiptQuery}&q=Return`,"GET",undefined,cookie)).data.receipts.length,1);
    assert.equal((await call(`/api/purchase-orders/receipts?${receiptQuery}&q=${receiptId}`,"GET",undefined,cookie)).data.receipts.length,1);
    assert.equal((await call(`/api/purchase-orders/receipts?${receiptQuery}&q=Missing`,"GET",undefined,cookie)).data.receipts.length,0);
    assert.equal((await call(`/api/purchase-orders/receipts?${receiptQuery}&page=1`,"GET",undefined,cookie)).data.receipts.length,0);
    assert.equal((await call(`/api/purchase-orders/receipts?${receiptQuery}&page=-1`,"GET",undefined,cookie)).status,400);
    assert.equal((await call(`/api/purchase-orders/receipts?${receiptQuery}&tenantId=${tenantId}`,"GET",undefined,cookie)).status,400);
    const viewerEmail=`receipts-${randomUUID().slice(0,8)}@example.invalid`;
    const invitation=await create("/api/invitations",{email:viewerEmail,role:"Viewer",scope:{type:"BRANCH",companyId,branchId:branch.id}});
    const viewer=await call("/api/invitations/accept","POST",{token:invitation.path.split("/").at(-1),name:"Receipt viewer",password:"Receipt-viewer-password-2026"});
    assert.equal(viewer.status,200);
    assert.equal((await call(`/api/purchase-orders/receipts?${receiptQuery}`,"GET",undefined,viewer.cookie)).data.receipts.length,1);
    const {branch:sibling}=await create("/api/branches",{companyId,name:"Other receiving branch",code:"RECEIPT-OTHER"});
    assert.equal((await call(`/api/purchase-orders/receipts?${receiptQuery}&branchId=${sibling.id}`,"GET",undefined,viewer.cookie)).status,403);
    // A company-scoped source order cannot be exposed by a branch-only purchasing role.
    const {supplier:sharedSupplier}=await create("/api/suppliers",{companyId,code:"SHARED-SUP",displayName:"Shared supplier"});
    const {order:sharedPurchase}=await create("/api/purchase-orders",{companyId,supplierId:sharedSupplier.id,number:"PO-SHARED-RECEIPT",lines:[{description:"Shared order",quantity:1,unitPrice:"1"}]});
    assert.equal((await call(`/api/purchase-orders/${sharedPurchase.id}/status`,"PATCH",{tenantId,action:"issue"},cookie)).status,200);
    await create(`/api/purchase-orders/${sharedPurchase.id}/receive`,{branchId:branch.id,lines:[{orderLineId:sharedPurchase.lines[0].id,itemId:stockItem.id}]});
    assert.equal((await call(`/api/purchase-orders/receipts?${receiptQuery}`,"GET",undefined,cookie)).data.receipts.length,2);
    assert.equal((await call(`/api/purchase-orders/receipts?${receiptQuery}`,"GET",undefined,viewer.cookie)).data.receipts.length,1);
    const liability=await account("PAYABLE","LIABILITY"),deductionLiability=await account("DEDUCT","LIABILITY");
    const {employee}=await create("/api/employees",{companyId,branchId:branch.id,code:"PAY-QA",fullName:"Payroll QA"});
    const {entry:payroll}=await create("/api/payroll",{companyId,employeeId:employee.id,period:day.slice(0,7),baseSalary:"10.125",allowances:"2.250",deductions:"3.125"});
    const payrollPath=`/api/ledger/documents/payroll/${payroll.id}`;
    const payrollBody={tenantId,entryDate:day,debitAccountId:expenseAccount.id,creditAccountId:liability.id,deductionAccountId:deductionLiability.id};
    assert.equal((await call(payrollPath,"POST",payrollBody)).status,401);
    assert.equal((await call(payrollPath,"POST",payrollBody,outsider.cookie)).status,403);
    assert.equal((await call(payrollPath,"POST",payrollBody,cookie)).status,409,"draft payroll cannot accrue");
    assert.equal((await call(`/api/payroll/${payroll.id}`,"PATCH",{tenantId,action:"approve"},cookie)).status,200);
    assert.equal((await call(payrollPath,"POST",{...payrollBody,deductionAccountId:undefined},cookie)).status,409,"deductions need a selected account");
    assert.equal((await call(payrollPath,"POST",{...payrollBody,creditAccountId:asset.id},cookie)).status,409,"net pay accrues a liability");
    assert.equal((await call(payrollPath,"POST",{...payrollBody,deductionAccountId:expenseAccount.id},cookie)).status,409,"deductions use a separate account");
    assert.equal((await call(payrollPath,"POST",{...payrollBody,debitAccountId:foreign.id},cookie)).status,409,"foreign-company account rejected");
    assert.equal((await call(payrollPath,"POST",{...payrollBody,entryDate:"2020-01-01"},cookie)).status,409);
    await db.company.update({where:{id:companyId},data:{ledgerLockedThrough:new Date(`${day}T00:00:00Z`)}});
    assert.equal((await call(payrollPath,"POST",payrollBody,cookie)).status,409);
    await db.company.update({where:{id:companyId},data:{ledgerLockedThrough:null}});
    const payrollCompeting=await Promise.all([call(payrollPath,"POST",payrollBody,cookie),call(payrollPath,"POST",payrollBody,cookie)]);
    assert.deepEqual(payrollCompeting.map(r=>r.status).sort(),[201,409]);
    const payrollJournal=payrollCompeting.find(r=>r.status===201).data.entry;
    const payrollSaved=await db.journalEntry.findUnique({where:{id:payrollJournal.id},include:{lines:{orderBy:{position:"asc"}}}});
    assert.equal(payrollSaved.total.toFixed(3),"12.375");assert.equal(payrollSaved.branchId,branch.id);
    assert.deepEqual(payrollSaved.lines.map(l=>[l.debit.toFixed(3),l.credit.toFixed(3)]),[["12.375","0.000"],["0.000","9.250"],["0.000","3.125"]]);
    assert.equal((await call(payrollPath+`?tenantId=${tenantId}`,"GET",undefined,cookie)).data.entry.id,payrollJournal.id);
    assert.equal((await call(payrollPath+`?tenantId=${tenantId}`,"GET",undefined,outsider.cookie)).status,403);
    assert.equal((await call(`/api/payroll/${payroll.id}`,"PATCH",{tenantId,action:"void",reason:"Correction"},cookie)).status,409,"cannot void accrued payroll");
    assert.equal((await call(`/api/ledger/journals/${payrollJournal.id}/reverse`,"POST",{tenantId,number:"REV-PAYROLL",entryDate:day,reason:"QA correction"},cookie)).status,201);
    assert.equal((await call(`/api/payroll/${payroll.id}`,"PATCH",{tenantId,action:"void",reason:"Correction"},cookie)).status,200);
    assert.equal((await call(payrollPath,"POST",payrollBody,cookie)).status,409);
    // Zero net pay still creates a balanced gross/deduction accrual; no zero journal line.
    const {entry:zeroNet}=await create("/api/payroll",{companyId,employeeId:employee.id,period:"2020-01",baseSalary:"5.125",allowances:"0",deductions:"5.125"});
    assert.equal((await call(`/api/payroll/${zeroNet.id}`,"PATCH",{tenantId,action:"approve"},cookie)).status,200);
    assert.equal((await call(`/api/payroll/${zeroNet.id}`,"PATCH",{tenantId,action:"pay",reference:"Recorded manually"},cookie)).status,200);
    const deductionOffset=await account("OFFSET","EXPENSE");
    const zeroPosted=await call(`/api/ledger/documents/payroll/${zeroNet.id}`,"POST",{...payrollBody,deductionAccountId:deductionOffset.id},cookie);
    assert.equal(zeroPosted.status,201,JSON.stringify(zeroPosted.data));
    assert.equal(await db.journalLine.count({where:{entryId:zeroPosted.data.entry.id}}),2);
    assert.equal((await call(`/api/ledger/journals/${zeroPosted.data.entry.id}/reverse`,"POST",{tenantId,number:"REV-ZERO-PAY",entryDate:day,reason:"QA correction"},cookie)).status,201);
    const {entry:noDeductions}=await create("/api/payroll",{companyId,employeeId:employee.id,period:"2020-02",baseSalary:"4.125",allowances:"0",deductions:"0"});
    assert.equal((await call(`/api/payroll/${noDeductions.id}`,"PATCH",{tenantId,action:"approve"},cookie)).status,200);
    const noDeductionPath=`/api/ledger/documents/payroll/${noDeductions.id}`;
    assert.equal((await call(noDeductionPath,"POST",payrollBody,cookie)).status,409,"reject unused deduction account");
    const noDeductionPost=await call(noDeductionPath,"POST",{...payrollBody,deductionAccountId:undefined},cookie);
    assert.equal(noDeductionPost.status,201,JSON.stringify(noDeductionPost.data));
    assert.equal(await db.journalLine.count({where:{entryId:noDeductionPost.data.entry.id}}),2);
    const paymentPath=`/api/ledger/documents/payroll-payment/${noDeductions.id}`;
    const paymentBody={tenantId,entryDate:day,debitAccountId:liability.id,creditAccountId:asset.id};
    assert.equal((await call(paymentPath,"POST",paymentBody,cookie)).status,409,"payment must be recorded first");
    assert.equal((await call(`/api/payroll/${noDeductions.id}`,"PATCH",{tenantId,action:"pay",reference:"Manual bank payment reference"},cookie)).status,200);
    assert.equal((await call(paymentPath,"POST",paymentBody,outsider.cookie)).status,403);
    assert.equal((await call(paymentPath,"POST",{...paymentBody,debitAccountId:deductionLiability.id},cookie)).status,409,"must settle original net payable account");
    assert.equal((await call(paymentPath,"POST",{...paymentBody,creditAccountId:foreign.id},cookie)).status,409);
    const settlementCompeting=await Promise.all([call(paymentPath,"POST",paymentBody,cookie),call(paymentPath,"POST",paymentBody,cookie)]);
    assert.deepEqual(settlementCompeting.map(r=>r.status).sort(),[201,409]);
    const settlement=settlementCompeting.find(r=>r.status===201).data.entry;
    const settlementSaved=await db.journalEntry.findUnique({where:{id:settlement.id},include:{lines:{orderBy:{position:"asc"}}}});
    assert.equal(settlementSaved.total.toFixed(3),"4.125");assert.equal(settlementSaved.branchId,branch.id);
    assert.equal(settlementSaved.lines[0].accountId,liability.id);assert.equal(settlementSaved.lines[1].accountId,asset.id);
    assert.deepEqual(settlementSaved.lines.map(l=>[l.debit.toFixed(3),l.credit.toFixed(3)]),[["4.125","0.000"],["0.000","4.125"]]);
    assert.equal((await call(paymentPath+`?tenantId=${tenantId}`,"GET",undefined,cookie)).data.entry.id,settlement.id);
    assert.equal((await call(`/api/ledger/journals/${noDeductionPost.data.entry.id}/reverse`,"POST",{tenantId,number:"REV-NODED-PAY",entryDate:day,reason:"QA correction"},cookie)).status,409,"reverse settlement before accrual");
    assert.equal((await call(`/api/ledger/journals/${settlement.id}/reverse`,"POST",{tenantId,number:"REV-SETTLEMENT",entryDate:day,reason:"QA correction"},cookie)).status,201);
    assert.equal((await call(`/api/ledger/journals/${noDeductionPost.data.entry.id}/reverse`,"POST",{tenantId,number:"REV-NODED-PAY",entryDate:day,reason:"QA correction"},cookie)).status,201);
    assert.equal((await call(paymentPath,"POST",paymentBody,cookie)).status,409,"reversed accrual cannot be settled again");
    assert.equal((await call(`/api/ledger/documents/payroll-payment/${zeroNet.id}`,"POST",paymentBody,cookie)).status,409,"zero net requires no payment journal");
    assert.equal(await db.auditLog.count({where:{tenantId,action:"payroll-payment.ledger_posted"}}),1);
    const {entry:zeroGross}=await create("/api/payroll",{companyId,employeeId:employee.id,period:"2020-03",baseSalary:"0",allowances:"0",deductions:"0"});
    assert.equal((await call(`/api/payroll/${zeroGross.id}`,"PATCH",{tenantId,action:"approve"},cookie)).status,200);
    assert.equal((await call(`/api/ledger/documents/payroll/${zeroGross.id}`,"POST",{...payrollBody,deductionAccountId:undefined},cookie)).status,409);
    assert.equal(await db.auditLog.count({where:{tenantId,action:"payroll.ledger_posted"}}),3);
    const {entry:racePayroll}=await create("/api/payroll",{companyId,employeeId:employee.id,period:"2020-04",baseSalary:"1.125",allowances:"0",deductions:"0"});
    assert.equal((await call(`/api/payroll/${racePayroll.id}`,"PATCH",{tenantId,action:"approve"},cookie)).status,200);
    assert.equal((await call(`/api/payroll/${racePayroll.id}`,"PATCH",{tenantId,action:"pay",reference:"Recorded race payment"},cookie)).status,200);
    const racePaymentPath=`/api/ledger/documents/payroll-payment/${racePayroll.id}`;
    assert.equal((await call(racePaymentPath,"POST",paymentBody,cookie)).status,409,"payment needs an active accrual");
    const nextDay=new Date(Date.now()+86400000).toISOString().slice(0,10);
    const raceAccrual=await call(`/api/ledger/documents/payroll/${racePayroll.id}`,"POST",{...payrollBody,entryDate:nextDay,deductionAccountId:undefined},cookie);
    assert.equal(raceAccrual.status,201,JSON.stringify(raceAccrual.data));
    assert.equal((await call(racePaymentPath,"POST",paymentBody,cookie)).status,409,"payment date cannot precede accrual");
    const raceAccrualReverse=()=>call(`/api/ledger/journals/${raceAccrual.data.entry.id}/reverse`,"POST",{tenantId,number:"REV-RACE-ACCRUAL",entryDate:nextDay,reason:"Race correction"},cookie);
    const raceResults=await Promise.all([call(racePaymentPath,"POST",{...paymentBody,entryDate:nextDay},cookie),raceAccrualReverse()]);
    assert.deepEqual(raceResults.map(r=>r.status).sort(),[201,409],"settlement and accrual reversal cannot both succeed");
    if(raceResults[0].status===201){
      assert.equal((await call(`/api/ledger/journals/${raceResults[0].data.entry.id}/reverse`,"POST",{tenantId,number:"REV-RACE-PAY",entryDate:nextDay,reason:"Race correction"},cookie)).status,201);
      assert.equal((await raceAccrualReverse()).status,201);
    }
    const reserved=await call("/api/ledger/journals","POST",{tenantId,companyId,number:journal.number,entryDate:day,description:"Reserved reference",lines:[{accountId:asset.id,debit:"1",credit:"0"},{accountId:revenue.id,debit:"0",credit:"1"}]},cookie);
    assert.equal(reserved.status,400);
    assert.equal((await call("/api/ledger/journals","POST",{tenantId,companyId,number:payrollJournal.number,entryDate:day,description:"Reserved payroll reference",lines:[{accountId:expenseAccount.id,debit:"1",credit:"0"},{accountId:liability.id,debit:"0",credit:"1"}]},cookie)).status,400);
    const trial=await call(`/api/ledger/trial-balance?tenantId=${tenantId}&companyId=${companyId}`,"GET",undefined,cookie);assert.equal(trial.status,200);
    assert.ok(trial.data.rows.every(row=>row.debitBalance==="0.000"&&row.creditBalance==="0.000"));
    assert.equal(await db.auditLog.count({where:{tenantId,action:{in:["invoice.ledger_posted","expense.ledger_posted","pos.ledger_posted"]}}}),3);
  } finally {server.kill("SIGTERM");await db.$disconnect();}
});
