import assert from "node:assert/strict";
import test from "node:test";
import {randomUUID} from "node:crypto";
import {spawn} from "node:child_process";
import {PrismaClient} from "@prisma/client";
const origin="http://127.0.0.1:3231";
async function call(path,method="GET",body,cookie){const r=await fetch(origin+path,{method,headers:{"Content-Type":"application/json",...(cookie?{Cookie:cookie}:{})},...(body?{body:JSON.stringify(body)}:{})});const text=await r.text();let data;try{data=JSON.parse(text);}catch{throw new Error(`${method} ${path}: ${r.status} ${text.slice(0,200)}`);}return{status:r.status,data,cookie:r.headers.get("set-cookie")?.split(";")[0]};}
test("expense VAT preserves deductible cost, gross credits, scoped reports and correction history",{timeout:90000},async()=>{
 // Isolated PostgreSQL CI fixtures only; never create production financial data.
 const db=new PrismaClient(),server=spawn("./node_modules/.bin/next",["start","-p","3231"],{env:{...process.env,ALLOW_REGISTRATION:"true"},stdio:["ignore","ignore","inherit"]});
 try{
  let ready=false;for(let i=0;i<60;i++){try{if((await fetch(origin)).ok){ready=true;break;}}catch{}await new Promise(r=>setTimeout(r,500));}assert.ok(ready);
  async function owner(){const id=randomUUID().slice(0,8),r=await call("/api/auth/register","POST",{name:"Expense VAT QA",email:`expense-vat-${id}@example.invalid`,password:"Expense-VAT-password-2026",organization:"Expense VAT QA",slug:`expense-vat-${id}`});assert.equal(r.status,201);return r;}
  const actor=await owner(),outsider=await owner(),tenantId=actor.data.tenantId,cookie=actor.cookie;
  const create=async(path,body)=>{const r=await call(path,"POST",{tenantId,...body},cookie);assert.equal(r.status,201,JSON.stringify(r.data));return r.data;};
  const {company}=await create("/api/companies",{name:"Expense VAT",code:"EVAT",baseCurrency:"OMR"}),companyId=company.id;
  const {branch}=await create("/api/branches",{companyId,name:"Main",code:"MAIN"}),{branch:sibling}=await create("/api/branches",{companyId,name:"Other",code:"OTHER"});
  const account=async(code,type,c=companyId)=>(await create("/api/ledger/accounts",{companyId:c,code,name:code,type})).account;
  const cost=await account("6000","EXPENSE"),cash=await account("1010","ASSET"),payable=await account("2000","LIABILITY"),input=await account("1500","ASSET"),input2=await account("1510","ASSET"),output=await account("2200","LIABILITY");
  const {company:other}=await create("/api/companies",{name:"Foreign company",code:"FOREIGN"}),foreign=await account("FOREIGN","ASSET",other.id);
  const day=new Date().toISOString().slice(0,10),tomorrow=new Date(Date.parse(day)+86400000).toISOString().slice(0,10);
  const expense=async(number,amount="10.125",branchId=branch.id,date=day)=>(await create("/api/expenses",{companyId,branchId,number,description:"Supplier office expense",category:"Office",amount,expenseDate:date})).expense;
  const endpoint=id=>`/api/ledger/documents/expense/${id}`,base={tenantId,entryDate:day,debitAccountId:cost.id,creditAccountId:cash.id};
  const tax={supplierName:"Invoice supplier",supplierTaxNumber:"OM-SUPPLIER-123",reference:"SUP-EXPENSE-001",treatment:"STANDARD",recoverable:true};
  const postStatus=async id=>assert.equal((await call(`/api/expenses/${id}/status`,"PATCH",{tenantId,action:"post"},cookie)).status,200);
  const legacy=await expense("EXP-LEGACY");await postStatus(legacy.id);const legacyPosted=await call(endpoint(legacy.id),"POST",base,cookie);assert.equal(legacyPosted.status,201);assert.equal(legacyPosted.data.expenseVat,null);
  const settings={tenantId,expectedRevision:0,enabled:true,taxNumber:"OM-BUYER-123",sellerName:"Expense buyer",sellerAddress:"Muscat test address",effectiveFrom:tomorrow,outputAccountId:output.id},profilePath=`/api/companies/${companyId}/vat`;assert.equal((await call(profilePath,"PUT",settings,cookie)).status,200);
  const before=await expense("EXP-BEFORE");await postStatus(before.id);assert.equal((await call(endpoint(before.id),"POST",{...base,expenseVat:tax},cookie)).status,409);assert.equal((await call(endpoint(before.id),"POST",base,cookie)).status,201);
  const activeSettings={...settings,effectiveFrom:day};assert.equal((await call(profilePath,"PUT",{...activeSettings,expectedRevision:1},cookie)).status,200);
  const main=await expense("EXP-STANDARD");assert.equal((await call(endpoint(main.id),"POST",{...base,expenseVat:tax},cookie)).status,409);await postStatus(main.id);
  assert.equal((await call(endpoint(main.id),"POST",base,cookie)).status,409);assert.equal((await call(endpoint(main.id),"POST",{...base,expenseVat:tax},cookie)).status,409,"deductible input needs configured asset");
  assert.equal((await call(profilePath,"PUT",{...activeSettings,expectedRevision:2,inputAccountId:input.id},cookie)).status,200);
  const body={...base,expenseVat:tax};assert.equal((await call(endpoint(main.id),"POST",body)).status,401);assert.equal((await call(endpoint(main.id),"POST",body,outsider.cookie)).status,403);assert.equal((await call(endpoint(main.id)+`?tenantId=${tenantId}`,"GET",undefined,outsider.cookie)).status,403);
  for(const expenseVat of [{...tax,treatment:"EXEMPT"},{...tax,supplierTaxNumber:null},{...tax,supplierName:""},{...tax,reference:"x"},{...tax,treatment:"REVERSE_CHARGE"}])assert.equal((await call(endpoint(main.id),"POST",{...base,expenseVat},cookie)).status,400);
  assert.equal((await call(endpoint(main.id),"POST",{...body,creditAccountId:input.id},cookie)).status,409,"tax account cannot equal payment account");assert.equal((await call(endpoint(main.id),"POST",{...body,creditAccountId:foreign.id},cookie)).status,409);assert.equal((await call(endpoint(main.id),"POST",{...body,entryDate:"2020-01-01"},cookie)).status,409);
  const inspect=await call(endpoint(main.id)+`?tenantId=${tenantId}`,"GET",undefined,cookie);assert.equal(inspect.data.expenseVatSetup.required,true);assert.equal(inspect.data.expenseVatSetup.netAmount,"10.125");
  const competing=await Promise.all([call(endpoint(main.id),"POST",body,cookie),call(endpoint(main.id),"POST",body,cookie)]);assert.deepEqual(competing.map(r=>r.status).sort(),[201,409]);const posted=competing.find(r=>r.status===201).data;assert.equal(posted.gross,"10.631");assert.equal(Number(posted.expenseVat.taxAmount),.506);assert.equal(Number(posted.expenseVat.recoverableTax),.506);
  const journal=await db.journalEntry.findUnique({where:{id:posted.entry.id},include:{lines:{orderBy:{position:"asc"}}}});assert.deepEqual(journal.lines.map(l=>[l.accountId,l.debit.toFixed(3),l.credit.toFixed(3)]),[[cost.id,"10.125","0.000"],[cash.id,"0.000","10.631"],[input.id,"0.506","0.000"]]);assert.equal(journal.total.toFixed(3),"10.631");
  await assert.rejects(db.expenseVat.update({where:{entryId:posted.entry.id},data:{reference:"Changed"}}));await assert.rejects(db.expenseVat.delete({where:{entryId:posted.entry.id}}));await assert.rejects(db.expense.update({where:{id:main.id},data:{amount:"12"}}));await assert.rejects(db.expense.update({where:{id:main.id},data:{status:"VOID"}}));await assert.rejects(db.expenseVat.create({data:{...posted.expenseVat,entryId:legacyPosted.data.entry.id,expenseId:legacy.id}}));
  const non=await expense("EXP-NON-DEDUCTIBLE");await postStatus(non.id);const nonPosted=await call(endpoint(non.id),"POST",{...base,creditAccountId:payable.id,expenseVat:{...tax,reference:"SUP-NON",recoverable:false}},cookie);assert.equal(nonPosted.status,201,JSON.stringify(nonPosted.data));assert.equal(nonPosted.data.gross,"10.631");const nonLines=await db.journalLine.findMany({where:{entryId:nonPosted.data.entry.id},orderBy:{position:"asc"}});assert.equal(nonLines.length,2);assert.equal(nonLines[0].debit.toFixed(3),"10.631");assert.equal(nonLines[1].accountId,payable.id);
  const excluded=[];for(const treatment of ["ZERO","EXEMPT","NO_VAT"]){const e=await expense(`EXP-${treatment.replaceAll("_","-")}`,"1.000");await postStatus(e.id);const p=await call(endpoint(e.id),"POST",{...base,expenseVat:{...tax,reference:`SUP-${treatment}`,supplierTaxNumber:null,treatment,recoverable:false}},cookie);assert.equal(p.status,201,JSON.stringify(p.data));assert.equal(p.data.gross,"1.000");assert.equal(p.data.expenseVat.treatment,treatment);assert.equal(await db.journalLine.count({where:{entryId:p.data.entry.id}}),2);excluded.push(e);}
  const small=await expense("EXP-ROUND-ZERO","0.001");await postStatus(small.id);const smallPosted=await call(endpoint(small.id),"POST",body,cookie);assert.equal(smallPosted.status,201);assert.equal(Number(smallPosted.data.expenseVat.taxAmount),0);assert.equal(await db.journalLine.count({where:{entryId:smallPosted.data.entry.id}}),2);
  const listPath=`/api/expenses?tenantId=${tenantId}&companyId=${companyId}`,list=await call(listPath,"GET",undefined,cookie),mainRow=list.data.expenses.find(e=>e.id===main.id);assert.equal(mainRow.amount,"10.125");assert.equal(mainRow.grossAmount,"10.631");assert.equal(mainRow.expenseCost,"10.125");assert.equal(mainRow.recoverableTax,"0.506");assert.equal(list.data.expenses.find(e=>e.id===non.id).expenseCost,"10.631");
  const reportPath=`/api/expenses/report?${new URLSearchParams({tenantId,companyId,from:day,to:day,status:"POSTED"})}`,report=await call(reportPath,"GET",undefined,cookie);assert.equal(report.status,200);assert.equal(report.data.summary[0].amount,"44.007");assert.equal(report.data.amountBasis,"netPlusNonDeductibleVAT");assert.equal((await call(`/api/dashboard?tenantId=${tenantId}&companyId=${companyId}`,"GET",undefined,cookie)).data.expenses.postedAmount,"44.007");const csv=await fetch(origin+reportPath+"&format=csv",{headers:{Cookie:cookie}});assert.equal(csv.status,200);const csvText=await csv.text();assert.match(csvText,/"Expense cost","Currency","Net before VAT","VAT","Deductible VAT","Gross document amount"/);assert.match(csvText,/"10\.125","OMR","10\.125","0\.506","0\.506","10\.631"/);
  async function member(name,permissions,branchId=branch.id){const {role}=await create("/api/roles",{name,permissions}),email=`expense-${randomUUID().slice(0,8)}@example.invalid`,invite=await create("/api/invitations",{email,roleId:role.id,scope:{type:"BRANCH",companyId,branchId}}),r=await call("/api/invitations/accept","POST",{token:invite.path.split("/").at(-1),name,password:"Expense-member-password-2026"});assert.equal(r.status,200);return r.cookie;}
  const ledgerOnly=await member("Ledger without source",["company:read","branch:read","ledger:read","ledger:post"]),reader=await member("Expense VAT reader",["company:read","branch:read","ledger:read","expense:read"]),wrongBranch=await member("Other branch expense",["company:read","branch:read","ledger:read","ledger:post","expense:read"],sibling.id);
  const reverseBody={tenantId,number:"EXP-REV",entryDate:day,reason:"VAT expense correction"};assert.equal((await call(`/api/ledger/journals/${posted.entry.id}/reverse`,"POST",reverseBody,ledgerOnly)).status,409);assert.equal((await call(endpoint(main.id)+`?tenantId=${tenantId}`,"GET",undefined,ledgerOnly)).status,403);assert.equal((await call(endpoint(main.id)+`?tenantId=${tenantId}`,"GET",undefined,reader)).status,200);assert.equal((await call(endpoint(main.id),"POST",body,reader)).status,403);assert.equal((await call(endpoint(main.id)+`?tenantId=${tenantId}`,"GET",undefined,wrongBranch)).status,403);
  assert.equal((await call(reportPath,"GET",undefined,wrongBranch)).data.count,0);assert.equal((await call(listPath,"GET",undefined,wrongBranch)).data.expenses.length,0);
  const direct=await expense("EXP-DIRECT");await postStatus(direct.id);const createdBy=(await db.expense.findUnique({where:{id:direct.id}})).createdBy,number=`SYSE-${BigInt("0x"+direct.id.replaceAll("-","")).toString(36).toUpperCase().padStart(25,"0")}`;
  async function directVat(amounts,includeVat=true,includeAudit=true){return db.$transaction(async tx=>{const entry=await tx.journalEntry.create({data:{tenantId,companyId,branchId:branch.id,number,entryDate:new Date(day),currency:"OMR",total:amounts.gross,description:"Direct expense VAT",createdBy,lines:{create:[{position:0,accountId:cost.id,debit:amounts.net,credit:"0"},{position:1,accountId:cash.id,debit:"0",credit:amounts.gross},...(amounts.tax!=="0"?[{position:2,accountId:input.id,debit:amounts.tax,credit:"0"}]:[])]}}});if(includeVat)await tx.expenseVat.create({data:{entryId:entry.id,tenantId,companyId,expenseId:direct.id,netAmount:"10.125",taxAmount:amounts.tax,recoverableTax:amounts.tax,inputAccountId:input.id,...tax}});if(includeAudit)await tx.auditLog.create({data:{tenantId,actorId:createdBy,entity:"Expense",entityId:direct.id,action:"expense.ledger_posted",metadata:{journalId:entry.id}}});});}
  await assert.rejects(directVat({net:"10.125",tax:"0.500",gross:"10.625"}));await assert.rejects(directVat({net:"10.125",tax:"0",gross:"10.125"},false));await assert.rejects(directVat({net:"10.125",tax:"0.506",gross:"10.631"},true,false));assert.equal(await db.journalEntry.count({where:{number}}),0);
  assert.equal((await call(profilePath,"PUT",{...activeSettings,expectedRevision:3,inputAccountId:input2.id,sellerName:"Changed buyer"},cookie)).status,200);assert.equal((await call(endpoint(main.id)+`?tenantId=${tenantId}`,"GET",undefined,cookie)).data.expenseVatSetup.snapshot.inputAccountId,input.id);
  assert.equal((await call(`/api/expenses/${main.id}/status`,"PATCH",{tenantId,action:"void",reason:"Correction"},cookie)).status,409);const reversed=await call(`/api/ledger/journals/${posted.entry.id}/reverse`,"POST",reverseBody,cookie);assert.equal(reversed.status,201,JSON.stringify(reversed.data));const revLines=await db.journalLine.findMany({where:{entryId:reversed.data.entry.id},orderBy:{position:"asc"}});assert.deepEqual(revLines.map(l=>[l.accountId,l.debit.toFixed(3),l.credit.toFixed(3)]),[[cost.id,"0.000","10.125"],[cash.id,"10.631","0.000"],[input.id,"0.000","0.506"]]);assert.equal((await call(`/api/expenses/${main.id}/status`,"PATCH",{tenantId,action:"void",reason:"Correction"},cookie)).status,200);assert.equal((await call(endpoint(main.id),"POST",body,cookie)).status,409);assert.equal((await db.expenseVat.findUnique({where:{expenseId:main.id}})).reference,tax.reference);await assert.rejects(db.expense.update({where:{id:main.id},data:{status:"POSTED"}}));
  assert.equal((await call(profilePath,"PUT",{...activeSettings,expectedRevision:4,enabled:false,inputAccountId:input2.id},cookie)).status,200);const plain=await expense("EXP-DISABLED");await postStatus(plain.id);assert.equal((await call(endpoint(plain.id),"POST",body,cookie)).status,409);assert.equal((await call(endpoint(plain.id),"POST",base,cookie)).status,201);assert.equal((await db.expense.findUnique({where:{id:legacy.id},include:{vat:true}})).vat,null);
  const locked=await expense("EXP-LOCKED");await postStatus(locked.id);assert.equal((await call("/api/ledger/period-lock","PATCH",{tenantId,companyId,lockedThrough:day,expectedLockedThrough:null,reason:"Close expense VAT"},cookie)).status,200);assert.equal((await call(endpoint(locked.id),"POST",base,cookie)).status,409);assert.equal((await call(endpoint(locked.id),"POST",{...base,entryDate:tomorrow},cookie)).status,201);
  for(const path of ["/accounting/expenses","/accounting/vat-settings",`/accounting/ledger/journals/${posted.entry.id}`]){const r=await fetch(origin+path,{headers:{Cookie:cookie}});assert.equal(r.status,200,path);assert.match(await r.text(),/Final Arrow ERP/);}
  assert.equal((await db.$queryRaw`SELECT relrowsecurity FROM pg_class WHERE oid='"ExpenseVat"'::regclass`)[0].relrowsecurity,true);
 }finally{server.kill("SIGTERM");await db.$disconnect();}
});
