import assert from "node:assert/strict";
import test from "node:test";
import {randomUUID} from "node:crypto";
import {spawn} from "node:child_process";
import {PrismaClient} from "@prisma/client";
const origin="http://127.0.0.1:3229";
async function call(path,method="GET",body,cookie){const r=await fetch(origin+path,{method,headers:{"Content-Type":"application/json",...(cookie?{Cookie:cookie}:{})},...(body?{body:JSON.stringify(body)}:{})});return{status:r.status,data:await r.json(),cookie:r.headers.get("set-cookie")?.split(";")[0]};}
test("Oman invoice VAT snapshots, gross journals and customer collections",{timeout:90000},async()=>{
 // Synthetic business data is created only in isolated CI PostgreSQL.
 const db=new PrismaClient(),server=spawn("./node_modules/.bin/next",["start","-p","3229"],{env:{...process.env,ALLOW_REGISTRATION:"true"},stdio:["ignore","ignore","inherit"]});
 try{
  let ready=false;for(let i=0;i<60;i++){try{if((await fetch(origin)).ok){ready=true;break;}}catch{}await new Promise(r=>setTimeout(r,500));}assert.ok(ready);
  async function owner(){const s=randomUUID().slice(0,8),r=await call("/api/auth/register","POST",{name:"VAT QA",email:`vat-${s}@example.invalid`,password:"VAT-password-2026",organization:"VAT QA",slug:`vat-${s}`});assert.equal(r.status,201);return r;}
  const actor=await owner(),outsider=await owner(),tenantId=actor.data.tenantId,cookie=actor.cookie;
  async function create(path,body){const r=await call(path,"POST",{tenantId,...body},cookie);assert.equal(r.status,201,JSON.stringify(r.data));return r.data;}
  const {company}=await create("/api/companies",{name:"VAT company",code:"VAT",baseCurrency:"OMR"}),companyId=company.id;
  const {branch}=await create("/api/branches",{companyId,name:"Main",code:"MAIN"}),{customer}=await create("/api/customers",{companyId,branchId:branch.id,code:"CUSTOMER",displayName:"VAT customer"});
  const account=async(code,type,c=companyId)=>(await create("/api/ledger/accounts",{companyId:c,code,name:code,type})).account;
  const ar=await account("1200","ASSET"),cash=await account("1010","ASSET"),revenue=await account("4000","REVENUE"),output=await account("2200","LIABILITY"),output2=await account("2210","LIABILITY");
  const day=new Date().toISOString().slice(0,10),tomorrow=new Date(Date.parse(day)+86400000).toISOString().slice(0,10);
  const linePrices=["10.125","0.010","2.000","3.000"],treatments=["STANDARD","STANDARD","ZERO","EXEMPT"],choices=treatments.map((treatment,position)=>({position,treatment}));
  async function order(number){const {quote}=await create("/api/quotes",{companyId,branchId:branch.id,customerId:customer.id,number:`Q-${number}`,lines:linePrices.map((unitPrice,i)=>({description:`VAT line ${i}`,quantity:1,unitPrice}))});for(const action of ["send","accept"])assert.equal((await call(`/api/quotes/${quote.id}/status`,"PATCH",{tenantId,action},cookie)).status,200);const {order}=await create(`/api/quotes/${quote.id}/order`,{number:`O-${number}`});for(const action of ["start","complete"])assert.equal((await call(`/api/orders/${order.id}/status`,"PATCH",{tenantId,action},cookie)).status,200);return order;}
  const oldOrder=await order("OLD"),legacy=(await create(`/api/orders/${oldOrder.id}/invoice`,{number:"INV-OLD"})).invoice;assert.equal(legacy.vat,null);
  const path=`/api/companies/${companyId}/vat`,q=`?tenantId=${tenantId}`,settings={tenantId,expectedRevision:0,enabled:true,taxNumber:"OM-TEST-123",sellerName:"VAT registered seller",sellerAddress:"Muscat test address",effectiveFrom:day,outputAccountId:output.id};
  assert.equal((await call(path+q)).status,401);assert.equal((await call(path+q,"GET",undefined,outsider.cookie)).status,403);assert.equal((await call(path+q,"GET",undefined,cookie)).data.profile,null);
  const invite=await create("/api/invitations",{email:`vat-view-${randomUUID().slice(0,8)}@example.invalid`,role:"Viewer",scope:{type:"BRANCH",companyId,branchId:branch.id}}),viewer=await call("/api/invitations/accept","POST",{token:invite.path.split("/").at(-1),name:"VAT branch viewer",password:"VAT-viewer-password-2026"});assert.equal(viewer.status,200);assert.equal((await call(path+q,"GET",undefined,viewer.cookie)).status,403);assert.equal((await call(path,"PUT",settings,viewer.cookie)).status,403);
  assert.equal((await call(path,"PUT",{...settings,outputAccountId:ar.id},cookie)).status,409);assert.equal((await call(path,"PUT",{...settings,taxNumber:null},cookie)).status,400);
  const {company:foreign}=await create("/api/companies",{name:"Foreign VAT",code:"FOREIGN",baseCurrency:"USD"}),foreignOutput=await account("2200","LIABILITY",foreign.id);assert.equal((await call(path,"PUT",{...settings,outputAccountId:foreignOutput.id},cookie)).status,409);assert.equal((await call(`/api/companies/${foreign.id}/vat`,"PUT",{...settings,outputAccountId:foreignOutput.id},cookie)).status,409);
  const races=await Promise.all([call(path,"PUT",settings,cookie),call(path,"PUT",{...settings,sellerName:"Race seller"},cookie)]);assert.deepEqual(races.map(r=>r.status).sort(),[200,409]);const saved=races.find(r=>r.status===200).data.profile;assert.equal(saved.revision,1);
  assert.equal((await call(`/api/companies/${companyId}`,"PATCH",{tenantId,name:"VAT company",legalName:null,baseCurrency:"USD"},cookie)).status,409);
  const o=await order("MIXED"),invoicePath=`/api/orders/${o.id}/invoice`,base={tenantId,number:"INV-MIXED"};
  assert.equal((await call(invoicePath,"POST",base,cookie)).status,409);
  for(const vat of [choices.slice(1),[{position:0,treatment:"STANDARD"},...choices.slice(1).map(c=>({...c,position:0}))],choices.map(c=>({...c,position:c.position+10}))])assert.equal((await call(invoicePath,"POST",{...base,vat},cookie)).status,409);
  assert.equal((await call(invoicePath,"POST",{...base,vat:[{position:0,treatment:"UNKNOWN"}]},cookie)).status,400);
  const {invoice}=await create(invoicePath,{number:base.number,vat:choices});assert.equal(invoice.subtotal,"15.135");assert.equal(Number(invoice.vat.taxAmount),0.507);assert.deepEqual(invoice.vat.details.map(d=>d.tax),["0.506","0.001","0.000","0.000"]);assert.deepEqual(invoice.vat.details.map(d=>d.treatment),treatments);
  assert.equal((await call(invoicePath,"POST",{...base,vat:choices},cookie)).status,409);
  await assert.rejects(db.invoice.update({where:{id:invoice.id},data:{subtotal:"1"}}));await assert.rejects(db.invoiceLine.update({where:{id:invoice.lines[0].id},data:{amount:"1"}}));await assert.rejects(db.invoiceLine.create({data:{tenantId,invoiceId:invoice.id,position:8,description:"Late line",quantity:1,unitPrice:"1",amount:"1"}}));await assert.rejects(db.invoiceVat.update({where:{invoiceId:invoice.id},data:{taxAmount:"1"}}));await assert.rejects(db.invoiceVat.delete({where:{invoiceId:invoice.id}}));
  await assert.rejects(db.invoiceVat.create({data:{...invoice.vat,invoiceId:legacy.id}}));
  const user=(await db.membership.findFirst({where:{tenantId}})).userId;
  const directOrder=await order("DIRECT"),direct={tenantId,companyId,branchId:branch.id,customerId:customer.id,orderId:directOrder.id,number:"INV-DIRECT",customerName:customer.displayName,currency:"OMR",subtotal:"15.135",createdBy:user,lines:{create:linePrices.map((price,position)=>({position,description:`VAT line ${position}`,quantity:1,unitPrice:price,amount:price}))}};
  await assert.rejects(db.invoice.create({data:direct}));assert.equal(await db.invoice.count({where:{orderId:directOrder.id}}),0);
  for(const detail of [invoice.vat.details.map((d,i)=>i===0?{...d,tax:"0.000"}:d),invoice.vat.details.map((d,i)=>i===0?{...d,treatment:null}:d),invoice.vat.details.map((d,i)=>i===0?{...d,net:"9.000"}:d)])await assert.rejects(db.$transaction(async tx=>{const i=await tx.invoice.create({data:direct});await tx.invoiceVat.create({data:{...invoice.vat,invoiceId:i.id,details:detail}});}));
  const changed=await call(path,"PUT",{...settings,expectedRevision:1,sellerName:"New seller name",outputAccountId:output2.id},cookie);assert.equal(changed.status,200);const frozen=await db.invoiceVat.findUnique({where:{invoiceId:invoice.id}});assert.equal(frozen.sellerName,saved.sellerName);assert.equal(frozen.outputAccountId,output.id);assert.equal((await db.invoice.findUnique({where:{id:legacy.id},include:{vat:true}})).vat,null);
  const listing=await call(`/api/invoices?${new URLSearchParams({tenantId,companyId})}`,"GET",undefined,cookie);assert.equal(listing.data.invoices.find(i=>i.id===invoice.id).gross,"15.642");
  assert.equal((await call(`/api/invoices/${invoice.id}/status`,"PATCH",{tenantId,action:"issue"},cookie)).status,200);
  const posted=await create(`/api/ledger/documents/invoice/${invoice.id}`,{entryDate:day,debitAccountId:ar.id,creditAccountId:revenue.id});const journal=await db.journalEntry.findUnique({where:{id:posted.entry.id},include:{lines:{orderBy:{position:"asc"}}}});assert.equal(journal.total.toFixed(3),"15.642");assert.equal(journal.lines.length,3);assert.deepEqual(journal.lines.map(l=>[l.accountId,l.debit.toFixed(3),l.credit.toFixed(3)]),[[ar.id,"15.642","0.000"],[revenue.id,"0.000","15.135"],[output.id,"0.000","0.507"]]);
  const report=await call(`/api/invoices/report?${new URLSearchParams({tenantId,companyId,from:day,to:day,q:"INV-MIXED"})}`,"GET",undefined,cookie);assert.equal(report.status,200);assert.equal(report.data.summary[0].amount,"15.642");
  const statement=()=>call(`/api/accounting/customer-statement?${new URLSearchParams({tenantId,companyId,customerId:customer.id,from:day,to:day})}`,"GET",undefined,cookie);assert.equal((await statement()).data.summary[0].closing,"15.642");
  const settlementPath=`/api/invoices/${invoice.id}/settlements`,pay={tenantId,requestId:randomUUID(),kind:"COLLECTION",amount:"15.642",entryDate:day,assetAccountId:cash.id,reference:"Gross VAT collection"};
  assert.equal((await call(settlementPath,"POST",{...pay,amount:"15.643"},cookie)).status,409);const collected=await call(settlementPath,"POST",pay,cookie);assert.equal(collected.status,201,JSON.stringify(collected.data));assert.equal((await call(settlementPath+q,"GET",undefined,cookie)).data.balance,"0.000");assert.equal((await statement()).data.summary[0].closing,"0.000");
  const reverse=(id,number)=>call(`/api/ledger/journals/${id}/reverse`,"POST",{tenantId,number,entryDate:day,reason:"VAT correction test"},cookie);assert.equal((await reverse(posted.entry.id,"VAT-PARENT-BLOCK")).status,409);
  const refunded=await call(settlementPath,"POST",{...pay,requestId:randomUUID(),kind:"REFUND",amount:"15.642",reference:"Gross VAT refund"},cookie);assert.equal(refunded.status,201);assert.equal((await reverse(collected.data.settlement.entry.id,"VAT-COLLECT-BLOCK")).status,409);assert.equal((await reverse(refunded.data.settlement.entry.id,"VAT-REFUND-REV")).status,201);assert.equal((await reverse(collected.data.settlement.entry.id,"VAT-COLLECT-REV")).status,201);assert.equal((await reverse(posted.entry.id,"VAT-PARENT-REV")).status,201);assert.equal((await statement()).data.summary[0].closing,"0.000");
  const z=await order("ZERO"),zero=(await create(`/api/orders/${z.id}/invoice`,{number:"INV-ZERO",vat:choices.map(c=>({...c,treatment:c.position%2?"EXEMPT":"ZERO"}))})).invoice;assert.equal(Number(zero.vat.taxAmount),0);assert.equal(zero.vat.outputAccountId,output2.id);assert.equal((await call(`/api/invoices/${zero.id}/status`,"PATCH",{tenantId,action:"issue"},cookie)).status,200);const zeroPost=await create(`/api/ledger/documents/invoice/${zero.id}`,{entryDate:day,debitAccountId:ar.id,creditAccountId:revenue.id});assert.equal(await db.journalLine.count({where:{entryId:zeroPost.entry.id}}),2);
  assert.equal((await call(path,"PUT",{...settings,expectedRevision:2,effectiveFrom:tomorrow},cookie)).status,200);const f=await order("FUTURE");assert.equal((await call(`/api/orders/${f.id}/invoice`,"POST",{tenantId,number:"INV-FUTURE",vat:choices},cookie)).status,409);assert.equal((await create(`/api/orders/${f.id}/invoice`,{number:"INV-FUTURE"})).invoice.vat,null);
  for(const url of ["/accounting/vat-settings","/accounting/invoices",`/accounting/invoices/${invoice.id}`,`/accounting/invoices/${invoice.id}/settlements`]){const r=await fetch(origin+url,{headers:{Cookie:cookie}});assert.equal(r.status,200,url);const html=await r.text();assert.match(html,/FINAL/);if(url===`/accounting/invoices/${invoice.id}`){assert.match(html,/15\.642/);assert.match(html,/0\.507/);assert.match(html,/OM-TEST-123/);assert.match(html,/VAT registered seller|Race seller/);}}
  assert.equal((await db.$queryRaw`SELECT relrowsecurity FROM pg_class WHERE oid='"InvoiceVat"'::regclass`)[0].relrowsecurity,true);
 }finally{server.kill("SIGTERM");await db.$disconnect();}
});
