import assert from "node:assert/strict";
import test from "node:test";
import {randomUUID} from "node:crypto";
import {spawn} from "node:child_process";
import {PrismaClient} from "@prisma/client";
const origin="http://127.0.0.1:3233";
async function call(path,method="GET",body,cookie){const r=await fetch(origin+path,{method,headers:{"Content-Type":"application/json",...(cookie?{Cookie:cookie}:{})},...(body?{body:JSON.stringify(body)}:{})});const text=await r.text();let data;try{data=JSON.parse(text);}catch{throw new Error(`${method} ${path}: ${r.status} ${text.slice(0,200)}`);}return{status:r.status,data,cookie:r.headers.get("set-cookie")?.split(";")[0]};}
test("full POS refunds preserve gross tax, exact retries, source locks and corrections",{timeout:90000},async()=>{
 // Disposable CI database only. Never refund or create financial data in production QA.
 const db=new PrismaClient(),server=spawn("./node_modules/.bin/next",["start","-p","3233"],{env:{...process.env,ALLOW_REGISTRATION:"true"},stdio:["ignore","ignore","inherit"]});
 try{
  let ready=false;for(let i=0;i<60;i++){try{if((await fetch(origin)).ok){ready=true;break;}}catch{}await new Promise(r=>setTimeout(r,500));}assert.ok(ready);
  async function owner(){const id=randomUUID().slice(0,8),r=await call("/api/auth/register","POST",{name:"POS refund QA",email:`pos-refund-${id}@example.invalid`,password:"POS-refund-password-2026",organization:"POS refund QA",slug:`pos-refund-${id}`});assert.equal(r.status,201);return r;}
  const actor=await owner(),outsider=await owner(),tenantId=actor.data.tenantId,cookie=actor.cookie;
  const create=async(path,body)=>{const r=await call(path,"POST",{tenantId,...body},cookie);assert.equal(r.status,201,JSON.stringify(r.data));return r.data;};
  const {company}=await create("/api/companies",{name:"Refund POS",code:"REFUND",baseCurrency:"OMR"}),companyId=company.id;
  const {branch}=await create("/api/branches",{companyId,name:"Main",code:"MAIN"}),{branch:sibling}=await create("/api/branches",{companyId,name:"Other",code:"OTHER"}),scope={tenantId,companyId,branchId:branch.id};
  const account=async(code,type)=>(await create("/api/ledger/accounts",{companyId,code,name:code,type})).account;
  const cash=await account("1010","ASSET"),revenue=await account("4000","REVENUE"),output=await account("2200","LIABILITY"),output2=await account("2210","LIABILITY");
  const {item}=await create("/api/pos/items",{companyId,branchId:branch.id,code:"MEAL",name:"Original meal",category:"Food",price:"10.125"});
  const day=new Date().toISOString().slice(0,10),tomorrow=new Date(Date.parse(day)+86400000).toISOString().slice(0,10),later=new Date(Date.parse(day)+2*86400000).toISOString().slice(0,10);
  const order=async(number,treatment)=>(await create("/api/pos/orders",{companyId,branchId:branch.id,number,type:"TAKEAWAY",lines:[{itemId:item.id,quantity:1,...(treatment?{treatment}:{})}]})).order;
  const plain=await order("PLAIN");const pay=async o=>assert.equal((await call(`/api/pos/orders/${o.id}`,"PATCH",{tenantId,action:"pay",method:"CASH",tendered:"20.000"},cookie)).status,200);
  const posting={tenantId,entryDate:day,debitAccountId:cash.id,creditAccountId:revenue.id},post=async o=>(await create(`/api/ledger/documents/pos/${o.id}`,posting)).entry;
  await pay(plain);await post(plain);
  const profilePath=`/api/companies/${companyId}/vat`,settings={tenantId,expectedRevision:0,enabled:true,taxNumber:"OM-REFUND-123",sellerName:"Refund seller",sellerAddress:"Muscat refund address",effectiveFrom:day,outputAccountId:output.id};assert.equal((await call(profilePath,"PUT",settings,cookie)).status,200);
  const main=await order("VAT-SALE","STANDARD"),unpaid=await order("UNPAID","EXEMPT"),unposted=await order("UNPOSTED","ZERO");await pay(main);await pay(unposted);const original=await post(main),endpoint=id=>`/api/pos/orders/${id}/refunds`,body={tenantId,requestId:randomUUID(),entryDate:day,reference:"CASH-REFUND-001",reason:"Order fully returned"};
  assert.equal((await call(endpoint(main.id),"GET",undefined,cookie)).status,400);assert.equal((await call(endpoint(main.id)+`?tenantId=${tenantId}&tenantId=${tenantId}`,"GET",undefined,cookie)).status,400);assert.equal((await call(endpoint(main.id),"POST",body)).status,401);assert.equal((await call(endpoint(main.id),"POST",body,outsider.cookie)).status,403);
  assert.equal((await call(endpoint(unpaid.id),"POST",body,cookie)).status,409);assert.equal((await call(endpoint(unposted.id),"POST",body,cookie)).status,409);assert.equal((await call(endpoint(main.id),"POST",{...body,amount:"1.000"},cookie)).status,400);assert.equal((await call(endpoint(main.id),"POST",{...body,entryDate:"2020-01-01"},cookie)).status,409);
  const initial=await call(endpoint(main.id)+`?tenantId=${tenantId}`,"GET",undefined,cookie);assert.equal(initial.data.eligible,true);assert.equal(initial.data.amount,"10.631");assert.equal(initial.data.taxAmount,"0.506");
  // Profile/account edits must never alter the original refund tax account.
  assert.equal((await call(profilePath,"PUT",{...settings,expectedRevision:1,outputAccountId:output2.id,sellerName:"Changed seller"},cookie)).status,200);assert.equal((await call(profilePath,"PUT",{...settings,expectedRevision:2,enabled:false,outputAccountId:output2.id},cookie)).status,200);
  const concurrent=await Promise.all([call(endpoint(main.id),"POST",body,cookie),call(endpoint(main.id),"POST",body,cookie)]);assert.deepEqual(concurrent.map(r=>r.status),[201,201]);assert.deepEqual(concurrent.map(r=>r.data.replayed).sort(),[false,true]);assert.equal(concurrent[0].data.refund.id,body.requestId);const saved=concurrent[0].data.refund;
  const lines=await db.journalLine.findMany({where:{entryId:saved.entry.id},orderBy:{position:"asc"}});assert.deepEqual(lines.map(l=>[l.accountId,l.debit.toFixed(3),l.credit.toFixed(3)]),[[cash.id,"0.000","10.631"],[revenue.id,"10.125","0.000"],[output.id,"0.506","0.000"]]);assert.equal((await db.journalEntry.findUnique({where:{id:saved.entry.id}})).reversalOf,null);
  assert.equal((await call(endpoint(main.id),"POST",{...body,requestId:randomUUID()},cookie)).status,409);for(const changed of [{reference:"Changed reference"},{reason:"Changed reason"},{entryDate:tomorrow}])assert.equal((await call(endpoint(main.id),"POST",{...body,...changed},cookie)).status,409);assert.equal((await call(endpoint(plain.id),"POST",body,cookie)).status,409);
  await assert.rejects(db.posRefund.update({where:{id:saved.id},data:{reason:"Rewrite"}}));await assert.rejects(db.posRefund.delete({where:{id:saved.id}}));assert.equal((await db.posOrder.findUnique({where:{id:main.id}})).status,"PAID");
  const reportPath=`/api/pos/refunds/report?${new URLSearchParams({...scope,from:day,to:day})}`,report=await call(reportPath,"GET",undefined,cookie);assert.equal(report.status,200);assert.equal(report.data.summary[0].amount,"10.631");assert.equal(report.data.summary[0].netAmount,"10.125");assert.equal(report.data.summary[0].taxAmount,"0.506");assert.equal(report.data.summary[0].reversedCount,0);assert.equal((await call(reportPath.replace(`branchId=${branch.id}`,`branchId=${sibling.id}`),"GET",undefined,cookie)).data.count,0);assert.equal((await call(reportPath.replace(`to=${day}`,`to=2099-01-01`),"GET",undefined,cookie)).status,400);
  async function member(name,permissions,branchId=branch.id){const {role}=await create("/api/roles",{name,permissions}),email=`refund-${randomUUID().slice(0,8)}@example.invalid`,invite=await create("/api/invitations",{email,roleId:role.id,scope:{type:"BRANCH",companyId,branchId}}),r=await call("/api/invitations/accept","POST",{token:invite.path.split("/").at(-1),name,password:"Refund-member-password-2026"});assert.equal(r.status,200);return r.cookie;}
  const ledgerOnly=await member("No POS",["company:read","branch:read","ledger:read","ledger:post"]),reader=await member("POS ledger reader",["company:read","branch:read","pos:read","ledger:read","ledger:post"]),wrongBranch=await member("Other refund branch",["company:read","branch:read","pos:read","pos:manage","ledger:read","ledger:post"],sibling.id);
  assert.equal((await call(endpoint(main.id)+`?tenantId=${tenantId}`,"GET",undefined,ledgerOnly)).status,403);assert.equal((await call(endpoint(main.id)+`?tenantId=${tenantId}`,"GET",undefined,reader)).status,200);assert.equal((await call(endpoint(main.id),"POST",body,reader)).status,403);assert.equal((await call(endpoint(main.id),"POST",body,wrongBranch)).status,403);assert.equal((await call(reportPath,"GET",undefined,wrongBranch)).status,403);assert.equal((await call(reportPath,"GET",undefined,ledgerOnly)).status,403);
  const reverse=(id,number,date=day,c=cookie)=>call(`/api/ledger/journals/${id}/reverse`,"POST",{tenantId,number,entryDate:date,reason:"Refund correction"},c);
  assert.equal((await reverse(original.id,"SALE-REV-BLOCKED")).status,409);assert.equal((await reverse(saved.entry.id,"REF-REV-FORBIDDEN",day,reader)).status,409);
  // Database guards must also block direct original reversal while refund is active.
  const originalRow=await db.journalEntry.findUnique({where:{id:original.id},include:{lines:true}}),createdBy=originalRow.createdBy;
  await assert.rejects(db.journalEntry.create({data:{tenantId,companyId,branchId:branch.id,number:"DIRECT-SALE-REV",entryDate:new Date(day),currency:"OMR",total:"10.631",description:"Direct reversal blocked",reversalOf:original.id,createdBy,lines:{create:originalRow.lines.map(l=>({position:l.position,accountId:l.accountId,debit:l.credit,credit:l.debit}))}}}));
  const reversed=await reverse(saved.entry.id,"REF-REV",tomorrow);assert.equal(reversed.status,201,JSON.stringify(reversed.data));const rev=await db.journalLine.findMany({where:{entryId:reversed.data.entry.id},orderBy:{position:"asc"}});assert.deepEqual(rev.map(l=>[l.accountId,l.debit.toFixed(3),l.credit.toFixed(3)]),[[cash.id,"10.631","0.000"],[revenue.id,"0.000","10.125"],[output.id,"0.000","0.506"]]);assert.equal((await reverse(original.id,"TOO-EARLY")).status,409);assert.equal((await call(endpoint(main.id),"POST",body,cookie)).data.replayed,true,"retry after correction must not create a new refund");
  const corrected=await call(reportPath,"GET",undefined,cookie);assert.equal(corrected.data.summary[0].amount,"0.000");assert.equal(corrected.data.summary[0].reversedAmount,"10.631");assert.equal(corrected.data.summary[0].reversedCount,1);
  const newBody={...body,requestId:randomUUID(),entryDate:tomorrow,reference:"REISSUE-001"};assert.equal((await call(endpoint(main.id),"POST",{...newBody,entryDate:day},cookie)).status,409);const reissue=await call(endpoint(main.id),"POST",newBody,cookie);assert.equal(reissue.status,201,JSON.stringify(reissue.data));assert.equal((await call(endpoint(main.id)+`?tenantId=${tenantId}`,"GET",undefined,cookie)).data.count,2);assert.equal((await reverse(reissue.data.refund.entry.id,"REISSUE-REV",tomorrow)).status,201);assert.equal((await reverse(original.id,"SALE-REV",tomorrow)).status,201);assert.equal((await call(endpoint(main.id),"POST",{...newBody,requestId:randomUUID()},cookie)).status,409);
  const plainBody={...body,requestId:randomUUID(),reference:"=FORMULA-REFERENCE"};const different=await Promise.all([call(endpoint(plain.id),"POST",plainBody,cookie),call(endpoint(plain.id),"POST",{...plainBody,requestId:randomUUID()},cookie)]);assert.deepEqual(different.map(r=>r.status).sort(),[201,409]);const plainSaved=different.find(r=>r.status===201).data.refund;assert.equal(Number(plainSaved.taxAmount),0);assert.equal(await db.journalLine.count({where:{entryId:plainSaved.entry.id}}),2);
  const csv=await fetch(origin+reportPath+"&format=csv",{headers:{Cookie:cookie}});assert.equal(csv.status,200);const csvText=await csv.text();assert.match(csvText,/"Net before VAT","VAT","Gross refund"/);assert.match(csvText,/'=FORMULA-REFERENCE/);assert.match(csvText,/"REVERSED"/);
  const html=await fetch(origin+`/pos/${main.id}`,{headers:{Cookie:cookie}});assert.equal(html.status,200);assert.match(await html.text(),/CASH-REFUND-001/);const paid=await call(`/api/pos/report?${new URLSearchParams({...scope,from:day,to:day,timeZone:"UTC"})}`,"GET",undefined,cookie);assert.equal(paid.data.summary[0].total,"30.881","paid register retains original sales independently of refund corrections");
  // Missing/late/wrong sources and journal amounts cannot bypass refund validation.
  const directSource=await order("DIRECT-SOURCE");await pay(directSource);const directOriginal=await post(directSource);const directLines=await db.journalLine.findMany({where:{entryId:directOriginal.id},orderBy:{position:"asc"}});
  const direct=async(includeSource=true,includeAudit=true,wrong=false)=>db.$transaction(async tx=>{const id=randomUUID(),number=`SYSU-${BigInt("0x"+id.replaceAll("-","")).toString(36).toUpperCase().padStart(25,"0")}`,e=await tx.journalEntry.create({data:{tenantId,companyId,branchId:branch.id,number,entryDate:new Date(day),currency:"OMR",total:"10.125",description:"Direct refund",createdBy,lines:{create:directLines.map(l=>({position:l.position,accountId:l.accountId,debit:wrong?l.debit:l.credit,credit:wrong?l.credit:l.debit}))}}});if(includeSource)await tx.posRefund.create({data:{id,tenantId,companyId,orderId:directSource.id,entryId:e.id,originalEntryId:directOriginal.id,netAmount:"10.125",taxAmount:"0",amount:"10.125",reference:"Direct reference",reason:"Direct test refund",createdBy}});if(includeAudit)await tx.auditLog.create({data:{tenantId,actorId:createdBy,entity:"PosRefund",entityId:id,action:"pos-refund.recorded",metadata:{journalId:e.id}}});return e;});
  await assert.rejects(direct(false));await assert.rejects(direct(true,false));await assert.rejects(direct(true,true,true));
  assert.equal((await call("/api/ledger/period-lock","PATCH",{tenantId,companyId,lockedThrough:tomorrow,expectedLockedThrough:null,reason:"Close refund period"},cookie)).status,200);assert.equal((await call(endpoint(directSource.id),"POST",{...body,requestId:randomUUID(),entryDate:tomorrow},cookie)).status,409);assert.equal((await call(endpoint(directSource.id),"POST",{...body,requestId:randomUUID(),entryDate:later},cookie)).status,201);
  assert.equal((await call("/api/ledger/journals","POST",{tenantId,companyId,branchId:branch.id,number:`SYSU-${"0".repeat(25)}`,entryDate:later,description:"Manual reserved",lines:[{accountId:cash.id,debit:"1",credit:"0"},{accountId:revenue.id,debit:"0",credit:"1"}]},cookie)).status,400);
  assert.equal((await db.$queryRaw`SELECT relrowsecurity FROM pg_class WHERE oid='"PosRefund"'::regclass`)[0].relrowsecurity,true);
 }finally{server.kill("SIGTERM");await db.$disconnect();}
});
