import assert from "node:assert/strict";
import test from "node:test";
import {randomUUID} from "node:crypto";
import {spawn} from "node:child_process";
import {PrismaClient} from "@prisma/client";
const origin="http://127.0.0.1:3232";
async function call(path,method="GET",body,cookie){const r=await fetch(origin+path,{method,headers:{"Content-Type":"application/json",...(cookie?{Cookie:cookie}:{})},...(body?{body:JSON.stringify(body)}:{})});const text=await r.text();let data;try{data=JSON.parse(text);}catch{throw new Error(`${method} ${path}: ${r.status} ${text.slice(0,200)}`);}return{status:r.status,data,cookie:r.headers.get("set-cookie")?.split(";")[0]};}
test("POS VAT freezes explicit line tax, gross payment and original ledger accounts",{timeout:90000},async()=>{
 // Disposable CI PostgreSQL only. No production test orders or registration changes.
 const db=new PrismaClient(),server=spawn("./node_modules/.bin/next",["start","-p","3232"],{env:{...process.env,ALLOW_REGISTRATION:"true"},stdio:["ignore","ignore","inherit"]});
 try{
  let ready=false;for(let i=0;i<60;i++){try{if((await fetch(origin)).ok){ready=true;break;}}catch{}await new Promise(r=>setTimeout(r,500));}assert.ok(ready);
  async function owner(){const id=randomUUID().slice(0,8),r=await call("/api/auth/register","POST",{name:"POS VAT QA",email:`pos-vat-${id}@example.invalid`,password:"POS-VAT-password-2026",organization:"POS VAT QA",slug:`pos-vat-${id}`});assert.equal(r.status,201);return r;}
  const actor=await owner(),outsider=await owner(),tenantId=actor.data.tenantId,cookie=actor.cookie;
  const create=async(path,body)=>{const r=await call(path,"POST",{tenantId,...body},cookie);assert.equal(r.status,201,JSON.stringify(r.data));return r.data;};
  const {company}=await create("/api/companies",{name:"POS VAT",code:"POSVAT",baseCurrency:"OMR"}),companyId=company.id;
  const {branch}=await create("/api/branches",{companyId,name:"Main",code:"MAIN"}),{branch:sibling}=await create("/api/branches",{companyId,name:"Other",code:"OTHER"}),scope={tenantId,companyId,branchId:branch.id};
  const account=async(code,type)=>(await create("/api/ledger/accounts",{companyId,code,name:code,type})).account;
  const cash=await account("1010","ASSET"),revenue=await account("4000","REVENUE"),output=await account("2200","LIABILITY"),output2=await account("2210","LIABILITY");
  const item=async(code,price)=>(await create("/api/pos/items",{companyId,branchId:branch.id,code,name:code,category:"Food",price})).item;
  const a=await item("MEAL","10.125"),b=await item("ZERO","1.000"),c=await item("EXEMPT","2.000"),tiny=await item("SMALL","0.010");
  const order=async(number,lines=[{itemId:a.id,quantity:1}])=>(await create("/api/pos/orders",{companyId,branchId:branch.id,number,type:"TAKEAWAY",lines})).order;
  const legacy=await order("POS-LEGACY");assert.equal(legacy.vat,null);assert.equal(Number(legacy.total),10.125);
  const day=new Date().toISOString().slice(0,10),tomorrow=new Date(Date.parse(day)+86400000).toISOString().slice(0,10),profilePath=`/api/companies/${companyId}/vat`,settings={tenantId,expectedRevision:0,enabled:true,taxNumber:"OM-POS-123",sellerName:"Original POS seller",sellerAddress:"Original Muscat address",effectiveFrom:tomorrow,outputAccountId:output.id};
  assert.equal((await call(profilePath,"PUT",settings,cookie)).status,200);assert.equal((await call(`/api/pos/orders?${new URLSearchParams(scope)}`,"GET",undefined,cookie)).data.vatRequired,false);const before=await order("POS-BEFORE");assert.equal(before.vat,null);
  const mixed=[{itemId:a.id,quantity:1,treatment:"STANDARD"},{itemId:b.id,quantity:1,treatment:"ZERO"},{itemId:c.id,quantity:1,treatment:"EXEMPT"},{itemId:tiny.id,quantity:1,treatment:"STANDARD"}];
  const body={...scope,number:"POS-MIXED",type:"TAKEAWAY",lines:mixed};assert.equal((await call("/api/pos/orders","POST",body,cookie)).status,409);
  const active={...settings,effectiveFrom:day};assert.equal((await call(profilePath,"PUT",{...active,expectedRevision:1},cookie)).status,200);assert.equal((await call(`/api/pos/orders?${new URLSearchParams(scope)}`,"GET",undefined,cookie)).data.vatRequired,true);
  assert.equal((await call("/api/pos/orders","POST",body)).status,401);assert.equal((await call("/api/pos/orders","POST",body,outsider.cookie)).status,403);
  for(const lines of [[{itemId:a.id,quantity:1}],[{itemId:a.id,quantity:1,treatment:"NO_VAT"}],[mixed[0],mixed[0]]])assert.ok([400,409].includes((await call("/api/pos/orders","POST",{...body,lines},cookie)).status));
  const saved=await order("POS-MIXED",mixed);assert.equal(Number(saved.total),13.642);assert.equal(Number(saved.vat.netAmount),13.135);assert.equal(Number(saved.vat.taxAmount),.507);
  assert.deepEqual(saved.vat.details.map(l=>l.tax),["0.506","0.000","0.000","0.001"]);assert.deepEqual(saved.vat.details.map(l=>l.treatment),["STANDARD","ZERO","EXEMPT","STANDARD"]);assert.equal(saved.vat.outputAccountId,output.id);assert.equal(saved.vat.sellerName,settings.sellerName);
  // Menu edits cannot rewrite historical net or gross amounts.
  assert.equal((await call(`/api/pos/items/${a.id}`,"PATCH",{tenantId,price:"20.000",name:"Changed meal"},cookie)).status,200);
  assert.equal((await db.posOrder.findUnique({where:{id:saved.id}})).total.toFixed(3),"13.642");
  await assert.rejects(db.posVat.update({where:{orderId:saved.id},data:{sellerName:"Rewrite"}}));await assert.rejects(db.posVat.delete({where:{orderId:saved.id}}));await assert.rejects(db.posOrder.update({where:{id:saved.id},data:{total:"99"}}));await assert.rejects(db.posOrderLine.create({data:{orderId:saved.id,position:4,itemId:a.id,itemName:"Late line",quantity:1,unitPrice:"1",amount:"1"}}));
  const payPath=`/api/pos/orders/${saved.id}`;assert.equal((await call(payPath,"PATCH",{tenantId,action:"pay",method:"CASH",tendered:"13.135"},cookie)).status,400);assert.equal((await call(payPath,"PATCH",{tenantId,action:"pay",method:"CASH",tendered:"20.000"},cookie)).status,200);const paid=await db.posOrder.findUnique({where:{id:saved.id}});assert.equal(paid.change.toFixed(3),"6.358");
  const card=await order("POS-CARD",[{itemId:b.id,quantity:1,treatment:"ZERO"}]);assert.equal((await call(`/api/pos/orders/${card.id}`,"PATCH",{tenantId,action:"pay-card",reference:"TERMINAL-001"},cookie)).status,200);assert.equal((await db.posOrder.findUnique({where:{id:card.id}})).paymentReference,"TERMINAL-001");
  const race=await order("POS-RACE",[{itemId:c.id,quantity:1,treatment:"EXEMPT"}]);const racing=await Promise.all([call(`/api/pos/orders/${race.id}`,"PATCH",{tenantId,action:"pay-card",reference:"RACE-CARD"},cookie),call(`/api/pos/orders/${race.id}`,"PATCH",{tenantId,action:"cancel",reason:"Race cancellation"},cookie)]);assert.deepEqual(racing.map(r=>r.status).sort(),[200,409]);
  // Configuration changes affect future orders, never saved tax or the output account.
  assert.equal((await call(profilePath,"PUT",{...active,expectedRevision:2,outputAccountId:output2.id,sellerName:"Changed seller"},cookie)).status,200);assert.equal((await call(profilePath,"PUT",{...active,expectedRevision:3,enabled:false,outputAccountId:output2.id},cookie)).status,200);
  const endpoint=id=>`/api/ledger/documents/pos/${id}`,posting={tenantId,entryDate:day,debitAccountId:cash.id,creditAccountId:revenue.id};assert.equal((await call(endpoint(saved.id),"POST",posting,outsider.cookie)).status,403);
  const inspect=await call(endpoint(saved.id)+`?tenantId=${tenantId}`,"GET",undefined,cookie);assert.equal(inspect.data.posVat.taxAmount,"0.507");assert.equal(inspect.data.posVat.outputAccount.code,"2200");
  const concurrent=await Promise.all([call(endpoint(saved.id),"POST",posting,cookie),call(endpoint(saved.id),"POST",posting,cookie)]);assert.deepEqual(concurrent.map(r=>r.status).sort(),[201,409]);const journal=concurrent.find(r=>r.status===201).data.entry;
  const lines=await db.journalLine.findMany({where:{entryId:journal.id},orderBy:{position:"asc"}});assert.deepEqual(lines.map(l=>[l.accountId,l.debit.toFixed(3),l.credit.toFixed(3)]),[[cash.id,"13.642","0.000"],[revenue.id,"0.000","13.135"],[output.id,"0.000","0.507"]]);
  const zeroPosted=await call(endpoint(card.id),"POST",posting,cookie);assert.equal(zeroPosted.status,201,JSON.stringify(zeroPosted.data));assert.equal(await db.journalLine.count({where:{entryId:zeroPosted.data.entry.id}}),2);
  const plain=await order("POS-DISABLED");assert.equal(plain.vat,null);assert.equal((await call("/api/pos/orders","POST",{...body,number:"POS-DISABLED-TAX"},cookie)).status,409);assert.equal((await db.posOrder.findUnique({where:{id:legacy.id},include:{vat:true}})).vat,null);await assert.rejects(db.posVat.create({data:{...saved.vat,orderId:legacy.id}}));
  async function member(name,permissions,branchId=branch.id){const {role}=await create("/api/roles",{name,permissions}),email=`pos-${randomUUID().slice(0,8)}@example.invalid`,invite=await create("/api/invitations",{email,roleId:role.id,scope:{type:"BRANCH",companyId,branchId}}),r=await call("/api/invitations/accept","POST",{token:invite.path.split("/").at(-1),name,password:"POS-member-password-2026"});assert.equal(r.status,200);return r.cookie;}
  const ledgerOnly=await member("Ledger without POS",["company:read","branch:read","ledger:read","ledger:post"]),reader=await member("POS reader",["company:read","branch:read","pos:read"]),wrongBranch=await member("Other POS",["company:read","branch:read","pos:read","ledger:read","ledger:post"],sibling.id);
  assert.equal((await call(`/api/pos/orders?${new URLSearchParams(scope)}`,"GET",undefined,reader)).status,200);assert.equal((await call(endpoint(saved.id)+`?tenantId=${tenantId}`,"GET",undefined,reader)).status,403);assert.equal((await call(endpoint(saved.id),"POST",posting,wrongBranch)).status,403);
  const revBody={tenantId,number:"POS-REV",entryDate:day,reason:"POS VAT correction"};assert.equal((await call(`/api/ledger/journals/${journal.id}/reverse`,"POST",revBody,ledgerOnly)).status,409);const reversed=await call(`/api/ledger/journals/${journal.id}/reverse`,"POST",revBody,cookie);assert.equal(reversed.status,201,JSON.stringify(reversed.data));const rev=await db.journalLine.findMany({where:{entryId:reversed.data.entry.id},orderBy:{position:"asc"}});assert.deepEqual(rev.map(l=>[l.accountId,l.debit.toFixed(3),l.credit.toFixed(3)]),[[cash.id,"0.000","13.642"],[revenue.id,"13.135","0.000"],[output.id,"0.507","0.000"]]);assert.equal((await call(endpoint(saved.id),"POST",posting,cookie)).status,409);assert.equal((await db.posOrder.findUnique({where:{id:saved.id}})).status,"PAID");
  const reportPath=`/api/pos/report?${new URLSearchParams({...scope,from:day,to:day,timeZone:"UTC"})}`,report=await call(reportPath,"GET",undefined,cookie);assert.equal(report.status,200);const cashGroup=report.data.summary.find(g=>g.method==="CASH");assert.equal(cashGroup.total,"13.642");assert.equal(cashGroup.netAmount,"13.135");assert.equal(cashGroup.taxAmount,"0.507");const csv=await fetch(origin+reportPath+"&format=csv",{headers:{Cookie:cookie}});assert.match(await csv.text(),/"Net before VAT","VAT"/);
  const receipt=await fetch(origin+`/pos/${saved.id}`,{headers:{Cookie:cookie}});assert.equal(receipt.status,200);const html=await receipt.text();assert.match(html,/Original POS seller/);assert.match(html,/OM-POS-123/);assert.match(html,/13\.642/);assert.match(html,/0\.507/);assert.doesNotMatch(html,/Changed meal/);assert.equal((await fetch(origin+`/pos/${saved.id}`,{headers:{Cookie:wrongBranch}})).status,404);
  assert.equal((await call(profilePath,"PUT",{...active,expectedRevision:4},cookie)).status,200);
  const source=(await db.posOrder.findUnique({where:{id:saved.id}})),createdBy=source.createdBy;
  const directOrder=async(includeTax=true,tax="1.000",details=[{position:0,treatment:"STANDARD",net:"20.000",tax}])=>db.$transaction(async tx=>{const o=await tx.posOrder.create({data:{...scope,number:`DIRECT-${randomUUID().slice(0,8).toUpperCase()}`,type:"TAKEAWAY",currency:"OMR",total:includeTax?`21.000`:"20.000",createdBy,lines:{create:[{position:0,itemId:a.id,itemName:"Direct",quantity:1,unitPrice:"20.000",amount:"20.000"}]}}});if(includeTax)await tx.posVat.create({data:{orderId:o.id,tenantId,companyId,netAmount:"20.000",taxAmount:tax,outputAccountId:output.id,taxNumber:settings.taxNumber,sellerName:settings.sellerName,sellerAddress:settings.sellerAddress,details}});return o;});
  await assert.rejects(directOrder(false));await assert.rejects(directOrder(true,"0.999"));await assert.rejects(directOrder(true,"1.000",[{position:0,treatment:"EXEMPT",net:"20.000",tax:"1.000"}]));const direct=await directOrder();assert.equal(direct.total.toFixed(3),"21.000");
  const unposted=await order("POS-DIRECT-JOURNAL",[{itemId:a.id,quantity:1,treatment:"STANDARD"}]);assert.equal((await call(`/api/pos/orders/${unposted.id}`,"PATCH",{tenantId,action:"pay-card",reference:"DIRECT-CARD"},cookie)).status,200);const sysNumber=`SYSP-${BigInt("0x"+unposted.id.replaceAll("-","")).toString(36).toUpperCase().padStart(25,"0")}`;
  await assert.rejects(db.$transaction(async tx=>{const j=await tx.journalEntry.create({data:{tenantId,companyId,branchId:branch.id,number:sysNumber,entryDate:new Date(day),currency:"OMR",total:"21",description:"Wrong gross revenue",createdBy,lines:{create:[{position:0,accountId:cash.id,debit:"21",credit:"0"},{position:1,accountId:revenue.id,debit:"0",credit:"21"}]}}});await tx.auditLog.create({data:{tenantId,actorId:createdBy,entity:"PosOrder",entityId:unposted.id,action:"pos.ledger_posted",metadata:{journalId:j.id}}});}));assert.equal(await db.journalEntry.count({where:{number:sysNumber}}),0);
  assert.equal((await call("/api/ledger/period-lock","PATCH",{tenantId,companyId,lockedThrough:day,expectedLockedThrough:null,reason:"Close POS VAT"},cookie)).status,200);assert.equal((await call(endpoint(unposted.id),"POST",posting,cookie)).status,409);assert.equal((await call(endpoint(unposted.id),"POST",{...posting,entryDate:tomorrow},cookie)).status,201);
  assert.equal((await db.$queryRaw`SELECT relrowsecurity FROM pg_class WHERE oid='"PosVat"'::regclass`)[0].relrowsecurity,true);
 }finally{server.kill("SIGTERM");await db.$disconnect();}
});
