import assert from "node:assert/strict";
import test from "node:test";
import {randomUUID} from "node:crypto";
import {spawn} from "node:child_process";
import {PrismaClient} from "@prisma/client";
const origin="http://127.0.0.1:3230";
async function call(path,method="GET",body,cookie){const r=await fetch(origin+path,{method,headers:{"Content-Type":"application/json",...(cookie?{Cookie:cookie}:{})},...(body?{body:JSON.stringify(body)}:{})});return{status:r.status,data:await r.json(),cookie:r.headers.get("set-cookie")?.split(";")[0]};}
test("purchase VAT separates deductible cost, gross payments and exact partial return tax",{timeout:90000},async()=>{
 // Isolated CI PostgreSQL only; never create financial fixtures in the live ERP.
 const db=new PrismaClient(),server=spawn("./node_modules/.bin/next",["start","-p","3230"],{env:{...process.env,ALLOW_REGISTRATION:"true"},stdio:["ignore","ignore","inherit"]});
 try{
  let ready=false;for(let i=0;i<60;i++){try{if((await fetch(origin)).ok){ready=true;break;}}catch{}await new Promise(r=>setTimeout(r,500));}assert.ok(ready);
  async function owner(){const s=randomUUID().slice(0,8),r=await call("/api/auth/register","POST",{name:"Purchase VAT QA",email:`purchase-vat-${s}@example.invalid`,password:"Purchase-VAT-password-2026",organization:"Purchase VAT QA",slug:`purchase-vat-${s}`});assert.equal(r.status,201);return r;}
  const actor=await owner(),outsider=await owner(),tenantId=actor.data.tenantId,cookie=actor.cookie;
  async function create(path,body){const r=await call(path,"POST",{tenantId,...body},cookie);assert.equal(r.status,201,JSON.stringify(r.data));return r.data;}
  const {company}=await create("/api/companies",{name:"Purchase VAT",code:"PVAT",baseCurrency:"OMR"}),companyId=company.id;
  const {branch}=await create("/api/branches",{companyId,name:"Main",code:"MAIN"}),{supplier}=await create("/api/suppliers",{companyId,branchId:branch.id,code:"SUP",displayName:"Registered supplier"}),{item}=await create("/api/inventory/items",{companyId,branchId:branch.id,sku:"VAT-ITEM",name:"VAT item",unit:"unit"});
  const account=async(code,type,c=companyId)=>(await create("/api/ledger/accounts",{companyId:c,code,name:code,type})).account;
  const cost=await account("1400","ASSET"),payable=await account("2000","LIABILITY"),input=await account("1500","ASSET"),input2=await account("1510","ASSET"),output=await account("2200","LIABILITY"),cash=await account("1010","ASSET");
  const day=new Date().toISOString().slice(0,10),tomorrow=new Date(Date.parse(day)+86400000).toISOString().slice(0,10);
  async function receipt(number,prices=["10.125","2.375","3.000","4.000","5.000"],quantities=[2,1,1,1,1]){const {order}=await create("/api/purchase-orders",{companyId,branchId:branch.id,supplierId:supplier.id,number,lines:prices.map((unitPrice,i)=>({description:`Purchase VAT ${i}`,quantity:quantities[i],unitPrice}))});assert.equal((await call(`/api/purchase-orders/${order.id}/status`,"PATCH",{tenantId,action:"issue"},cookie)).status,200);return(await create(`/api/purchase-orders/${order.id}/receive`,{branchId:branch.id,requestId:randomUUID(),lines:order.lines.map(l=>({orderLineId:l.id,itemId:item.id,quantity:quantities[l.position]}))})).receipt;}
  const endpoint=(kind,id)=>`/api/ledger/documents/purchase-${kind}/${id}`,posting={tenantId,entryDate:day,debitAccountId:cost.id,creditAccountId:payable.id};
  const legacy=await receipt("PO-LEGACY",["1.000"],[1]),legacyPosted=await call(endpoint("receipt",legacy.id),"POST",posting,cookie);assert.equal(legacyPosted.status,201);assert.equal(legacyPosted.data.purchaseVat,null);
  const profilePath=`/api/companies/${companyId}/vat`,settings={tenantId,expectedRevision:0,enabled:true,taxNumber:"OM-BUYER-123",sellerName:"VAT buyer",sellerAddress:"Muscat buyer test address",effectiveFrom:day,outputAccountId:output.id};assert.equal((await call(profilePath,"PUT",settings,cookie)).status,200);
  const mixed=await receipt("PO-MIXED"),choices=mixed.lines.map((l,i)=>({receiptLineId:l.id,treatment:["STANDARD","STANDARD","ZERO","EXEMPT","NO_VAT"][i],recoverable:i===0}));
  // Receipt response ordering is not relied on: source lines carry order-line positions.
  const storedLines=await db.goodsReceiptLine.findMany({where:{receiptId:mixed.id},include:{orderLine:true},orderBy:{orderLine:{position:"asc"}}});const taxLines=storedLines.map((l,i)=>({...choices[i],receiptLineId:l.id})),vat={supplierTaxNumber:"OM-SUPPLIER-123",reference:"SUP-INVOICE-001",lines:taxLines};
  assert.equal((await call(endpoint("receipt",mixed.id),"POST",posting,cookie)).status,409);assert.equal((await call(endpoint("receipt",mixed.id),"POST",{...posting,purchaseVat:vat},cookie)).status,409,"input account required for deductible tax");
  assert.equal((await call(profilePath,"PUT",{...settings,expectedRevision:1,inputAccountId:payable.id},cookie)).status,409);const {company:foreign}=await create("/api/companies",{name:"Other VAT",code:"OTHER"}),foreignInput=await account("1500","ASSET",foreign.id);assert.equal((await call(profilePath,"PUT",{...settings,expectedRevision:1,inputAccountId:foreignInput.id},cookie)).status,409);
  assert.equal((await call(profilePath,"PUT",{...settings,expectedRevision:1,inputAccountId:input.id},cookie)).status,200);
  const body={...posting,purchaseVat:vat};assert.equal((await call(endpoint("receipt",mixed.id),"POST",body,outsider.cookie)).status,403);assert.equal((await call(endpoint("receipt",mixed.id),"POST",body)).status,401);
  for(const lines of [taxLines.slice(1),taxLines.map(l=>({...l,receiptLineId:taxLines[0].receiptLineId})),taxLines.map(l=>({...l,receiptLineId:randomUUID()}))])assert.equal((await call(endpoint("receipt",mixed.id),"POST",{...posting,purchaseVat:{...vat,lines}},cookie)).status,409);
  assert.equal((await call(endpoint("receipt",mixed.id),"POST",{...posting,purchaseVat:{...vat,supplierTaxNumber:null}},cookie)).status,400);assert.equal((await call(endpoint("receipt",mixed.id),"POST",{...posting,purchaseVat:{...vat,lines:taxLines.map(l=>({...l,recoverable:true}))}},cookie)).status,400);
  const posted=await call(endpoint("receipt",mixed.id),"POST",body,cookie);assert.equal(posted.status,201,JSON.stringify(posted.data));assert.equal(posted.data.gross,"35.757");const saved=posted.data.purchaseVat;assert.equal(Number(saved.netAmount),34.625);assert.equal(Number(saved.taxAmount),1.132);assert.equal(Number(saved.recoverableTax),1.013);
  const journal=await db.journalEntry.findUnique({where:{id:posted.data.entry.id},include:{lines:{orderBy:{position:"asc"}}}});assert.deepEqual(journal.lines.map(l=>[l.accountId,l.debit.toFixed(3),l.credit.toFixed(3)]),[[cost.id,"34.744","0.000"],[payable.id,"0.000","35.757"],[input.id,"1.013","0.000"]]);assert.equal((await call(endpoint("receipt",mixed.id),"POST",body,cookie)).status,409);
  await assert.rejects(db.purchaseVat.update({where:{entryId:posted.data.entry.id},data:{reference:"Changed"}}));await assert.rejects(db.purchaseVat.delete({where:{entryId:posted.data.entry.id}}));await assert.rejects(db.purchaseVat.create({data:{...saved,entryId:legacyPosted.data.entry.id,receiptId:legacy.id}}));
  const getState=()=>call(`/api/purchasing/receipts/${mixed.id}/settlements?tenantId=${tenantId}`,"GET",undefined,cookie);assert.equal((await getState()).data.balance,"35.757");const statement=()=>call(`/api/purchasing/supplier-statement?${new URLSearchParams({tenantId,companyId,supplierId:supplier.id,from:day,to:day})}`,"GET",undefined,cookie);assert.equal((await statement()).data.summary[0].closing,"36.757");
  const pay={tenantId,requestId:randomUUID(),kind:"PAYMENT",amount:"35.757",entryDate:day,assetAccountId:cash.id,reference:"Paid gross VAT invoice"},settle=`/api/purchasing/receipts/${mixed.id}/settlements`;assert.equal((await call(settle,"POST",{...pay,amount:"35.758"},cookie)).status,409);const payment=await call(settle,"POST",pay,cookie);assert.equal(payment.status,201,JSON.stringify(payment.data));assert.equal((await getState()).data.balance,"0.000");
  assert.equal((await call(profilePath,"PUT",{...settings,expectedRevision:2,inputAccountId:input2.id,sellerName:"Changed buyer"},cookie)).status,200);assert.equal((await db.purchaseVat.findUnique({where:{entryId:posted.data.entry.id}})).inputAccountId,input.id);
  const returned=async(receiptId,receiptLineId,quantity=1)=>(await create(`/api/purchase-orders/receipts/${receiptId}/returns`,{requestId:randomUUID(),reason:"VAT stock return",lines:[{receiptLineId,quantity}]})).goodsReturn;
  const first=await returned(mixed.id,storedLines[0].id),second=await returned(mixed.id,storedLines[0].id),credit={tenantId,entryDate:day,debitAccountId:payable.id,creditAccountId:cost.id};
  assert.equal((await call(endpoint("return",first.id),"POST",credit,cookie)).status,409);const inspect=await call(endpoint("return",first.id)+`?tenantId=${tenantId}`,"GET",undefined,cookie);assert.equal(inspect.data.purchaseSetup.debitAccountId,payable.id);assert.equal(inspect.data.purchaseVatSetup.recorded,false);
  const returnOne=await call(endpoint("return",second.id),"POST",{...credit,creditReference:"SUP-CREDIT-001"},cookie);assert.equal(returnOne.status,201,JSON.stringify(returnOne.data));assert.equal(returnOne.data.gross,"10.632");assert.equal(Number(returnOne.data.purchaseVat.taxAmount),0.507);assert.equal(returnOne.data.purchaseVat.inputAccountId,input.id);assert.equal((await getState()).data.balance,"-10.632");
  const refund=await call(settle,"POST",{...pay,requestId:randomUUID(),kind:"REFUND",amount:"10.632",reference:"Supplier gross refund"},cookie);assert.equal(refund.status,201);assert.equal((await getState()).data.balance,"0.000");
  const returnTwo=await call(endpoint("return",first.id),"POST",{...credit,creditReference:"SUP-CREDIT-002"},cookie);assert.equal(returnTwo.status,201,JSON.stringify(returnTwo.data));assert.equal(returnTwo.data.gross,"10.631");assert.equal(Number(returnTwo.data.purchaseVat.taxAmount),0.506);assert.equal((await getState()).data.balance,"-10.631");assert.equal((await call(settle,"POST",{...pay,requestId:randomUUID(),kind:"REFUND",amount:"10.632"},cookie)).status,409);
  const reverse=(id,number,date=day)=>call(`/api/ledger/journals/${id}/reverse`,"POST",{tenantId,number,entryDate:date,reason:"Purchase VAT correction"},cookie);assert.equal((await reverse(posted.data.entry.id,"PV-PARENT-BLOCK")).status,409);assert.equal((await reverse(refund.data.settlement.entry.id,"PV-REFUND-REV")).status,201);assert.equal((await reverse(payment.data.settlement.entry.id,"PV-PAYMENT-REV")).status,201);assert.equal((await reverse(returnOne.data.entry.id,"PV-RETURN-REV-1")).status,201);assert.equal((await reverse(returnTwo.data.entry.id,"PV-RETURN-REV-2")).status,201);assert.equal((await reverse(posted.data.entry.id,"PV-PARENT-REV")).status,201);assert.equal((await statement()).data.summary[0].closing,"1.000");
  const tiny=await receipt("PO-TINY",["0.010"],[2]),tinyLine=tiny.lines[0].id,tinyVat={...vat,reference:"SUP-TINY",lines:[{receiptLineId:tinyLine,treatment:"STANDARD",recoverable:true}]};const tinyPosted=await call(endpoint("receipt",tiny.id),"POST",{...posting,purchaseVat:tinyVat},cookie);assert.equal(tinyPosted.status,201);assert.equal(tinyPosted.data.gross,"0.021");const tiny1=await returned(tiny.id,tinyLine),tiny2=await returned(tiny.id,tinyLine);const tinyPosts=await Promise.all([call(endpoint("return",tiny1.id),"POST",{...credit,creditReference:"TINY-CREDIT-1"},cookie),call(endpoint("return",tiny2.id),"POST",{...credit,creditReference:"TINY-CREDIT-2"},cookie)]);assert.ok(tinyPosts.every(r=>r.status===201),JSON.stringify(tinyPosts));assert.deepEqual(tinyPosts.map(r=>Number(r.data.purchaseVat.taxAmount)).sort(),[0,.001]);assert.deepEqual(await Promise.all(tinyPosts.map(r=>db.journalLine.count({where:{entryId:r.data.entry.id}}))).then(a=>a.sort()),[2,3]);
  const noTax=await receipt("PO-NO-TAX",["1.000"],[1]),noTaxPosted=await call(endpoint("receipt",noTax.id),"POST",{...posting,purchaseVat:{reference:"NON-REGISTERED-INVOICE",supplierTaxNumber:null,lines:[{receiptLineId:noTax.lines[0].id,treatment:"NO_VAT",recoverable:false}]}},cookie);assert.equal(noTaxPosted.status,201);assert.equal(noTaxPosted.data.purchaseVat.supplierTaxNumber,null);assert.equal(await db.journalLine.count({where:{entryId:noTaxPosted.data.entry.id}}),2);
  const direct=await receipt("PO-DIRECT",["1.000"],[1]),user=(await db.membership.findFirst({where:{tenantId}})).userId,number=`SYSG-${BigInt("0x"+direct.id.replaceAll("-","")).toString(36).toUpperCase().padStart(25,"0")}`;
  await assert.rejects(db.$transaction(async tx=>{const entry=await tx.journalEntry.create({data:{tenantId,companyId,branchId:branch.id,number,entryDate:new Date(day),currency:"OMR",total:"1",description:"Missing tax snapshot",createdBy:user,lines:{create:[{position:0,accountId:cost.id,debit:"1",credit:"0"},{position:1,accountId:payable.id,debit:"0",credit:"1"}]}}});await tx.auditLog.create({data:{tenantId,actorId:user,entity:"GoodsReceipt",entityId:direct.id,action:"purchase-receipt.ledger_posted",metadata:{journalId:entry.id}}});}));assert.equal(await db.journalEntry.count({where:{number}}),0);
  assert.equal((await call(profilePath,"PUT",{...settings,expectedRevision:3,enabled:false,inputAccountId:input2.id},cookie)).status,200);const plain=await receipt("PO-PLAIN",["1.000"],[1]);assert.equal((await call(endpoint("receipt",plain.id),"POST",{...posting,purchaseVat:{...tinyVat,lines:[{receiptLineId:plain.lines[0].id,treatment:"STANDARD",recoverable:true}]}},cookie)).status,409);assert.equal((await call(endpoint("receipt",plain.id),"POST",posting,cookie)).status,201);assert.equal(await db.purchaseVat.count({where:{receiptId:legacy.id}}),0);
  const thirdReturn=await returned(noTax.id,noTax.lines[0].id);assert.equal((await call(endpoint("return",thirdReturn.id),"POST",{...credit,creditReference:"NO-TAX-CREDIT"},cookie)).status,201,"original VAT treatment is retained after profile disabled");
  const locked=await receipt("PO-LOCK",["1.000"],[1]);assert.equal((await call("/api/ledger/period-lock","PATCH",{tenantId,companyId,lockedThrough:day,expectedLockedThrough:null,reason:"Close VAT period"},cookie)).status,200);assert.equal((await call(endpoint("receipt",locked.id),"POST",posting,cookie)).status,409);assert.equal((await call(endpoint("receipt",locked.id),"POST",{...posting,entryDate:tomorrow},cookie)).status,201);
  for(const url of [`/purchasing/receipts/${mixed.id}`,`/purchasing/returns/${second.id}`,`/purchasing/receipts/${mixed.id}/settlements`,"/accounting/vat-settings"]){const r=await fetch(origin+url,{headers:{Cookie:cookie}});assert.equal(r.status,200,url);const html=await r.text();assert.match(html,/Final Arrow ERP/);if(url===`/purchasing/receipts/${mixed.id}`){assert.match(html,/35\.757/);assert.match(html,/SUP-INVOICE-001/);assert.match(html,/1\.013/);}}
  assert.equal((await db.$queryRaw`SELECT relrowsecurity FROM pg_class WHERE oid='"PurchaseVat"'::regclass`)[0].relrowsecurity,true);
  const sqlNumber=await db.$queryRaw`SELECT erp_purchase_document_number('SYSG',${direct.id}::uuid) AS number`;assert.equal(sqlNumber[0].number,number);
 }finally{server.kill("SIGTERM");await db.$disconnect();}
});
