import {NextResponse} from "next/server";
import {Prisma} from "@prisma/client";
import {z} from "zod";
import {db} from "@/lib/db";
import {currentUser} from "@/lib/auth";
import {canAccess} from "@/lib/access";
import {dueDate} from "@/lib/date";
const uuid=z.string().uuid(),schema=z.object({tenantId:uuid,expectedRevision:z.number().int().min(0),enabled:z.boolean(),inputAccountId:uuid.nullable().optional(),taxNumber:z.string().trim().min(3).max(40).nullable(),sellerName:z.string().trim().min(2).max(200).nullable(),sellerAddress:z.string().trim().min(3).max(500).nullable(),effectiveFrom:dueDate.nullable(),outputAccountId:uuid.nullable()}).strict().refine(s=>!s.enabled||[s.taxNumber,s.sellerName,s.sellerAddress,s.effectiveFrom,s.outputAccountId].every(Boolean));
async function allowed(userId:string,tenantId:string,companyId:string){return(await Promise.all([canAccess({userId,tenantId,companyId,permission:"company:update"}),canAccess({userId,tenantId,companyId,permission:"ledger:read"})])).every(Boolean);}
export async function GET(request:Request,{params}:{params:Promise<{id:string}>}){const actor=await currentUser();if(!actor)return NextResponse.json({error:"Unauthenticated"},{status:401});const{id}=await params,q=new URL(request.url).searchParams,tenantId=q.get("tenantId");if(!uuid.safeParse(id).success||!uuid.safeParse(tenantId).success||q.size!==1)return NextResponse.json({error:"Invalid scope"},{status:400});if(!(await allowed(actor.id,tenantId!,id)))return NextResponse.json({error:"Forbidden"},{status:403});return NextResponse.json({profile:await db.companyVatProfile.findUnique({where:{companyId:id}})},{headers:{"Cache-Control":"private, no-store"}});}
export async function PUT(request:Request,{params}:{params:Promise<{id:string}>}){
 const actor=await currentUser();if(!actor)return NextResponse.json({error:"Unauthenticated"},{status:401});const{id}=await params,input=schema.safeParse(await request.json().catch(()=>null));if(!uuid.safeParse(id).success||!input.success)return NextResponse.json({error:"Provide complete registered-company VAT settings"},{status:400});const{tenantId,expectedRevision,...body}=input.data;if(!(await allowed(actor.id,tenantId,id)))return NextResponse.json({error:"Forbidden"},{status:403});
 try{const profile=await db.$transaction(async tx=>{const rows=await tx.$queryRaw<{baseCurrency:string}[]>`SELECT "baseCurrency" FROM "Company" WHERE id=${id}::uuid AND "tenantId"=${tenantId}::uuid FOR UPDATE`;if(!rows.length)throw new Error("missing");const old=await tx.companyVatProfile.findUnique({where:{companyId:id}});if((old?.revision??0)!==expectedRevision)throw new Error("stale");if(body.enabled&&rows[0].baseCurrency!=="OMR")throw new Error("currency");if(body.outputAccountId&&!(await tx.ledgerAccount.findFirst({where:{id:body.outputAccountId,tenantId,companyId:id,type:"LIABILITY"}})))throw new Error("account");
 if(body.inputAccountId&&!(await tx.ledgerAccount.findFirst({where:{id:body.inputAccountId,tenantId,companyId:id,type:"ASSET"}})))throw new Error("account");
 const data={...body,inputAccountId:body.inputAccountId===undefined?old?.inputAccountId??null:body.inputAccountId,effectiveFrom:body.effectiveFrom?new Date(body.effectiveFrom):null,revision:expectedRevision+1};const result=await tx.companyVatProfile.upsert({where:{companyId:id},create:{tenantId,companyId:id,...data},update:data});await tx.auditLog.create({data:{tenantId,actorId:actor.id,entity:"Company",entityId:id,action:"company.vat-settings.updated",metadata:{before:old?JSON.parse(JSON.stringify(old)):null,after:JSON.parse(JSON.stringify(result))}}});return result;});return NextResponse.json({profile},{headers:{"Cache-Control":"private, no-store"}});
 }catch(e){if(e instanceof Error&&["stale","missing","currency","account"].includes(e.message))return NextResponse.json({error:e.message==="stale"?"Settings changed. Refresh before saving.":e.message==="missing"?"Company not found":"Choose OMR, a liability output account and an asset input account in this company"},{status:e.message==="missing"?404:409});if(e instanceof Prisma.PrismaClientKnownRequestError&&["P2002","P2003","P2004"].includes(e.code))return NextResponse.json({error:"VAT settings conflict"},{status:409});throw e;}
}
