import {redirect} from "next/navigation";
import {currentUser} from "@/lib/auth";
import {db} from "@/lib/db";
import {readableCompanyPermissions} from "@/lib/access";
import {getLocale} from "@/lib/server-locale";
import {translate} from "@/lib/locale";
import {LanguageSwitcher} from "../../language-switcher";
import {z} from "zod";
export default async function SettlementsPage({searchParams}:{searchParams:Promise<Record<string,string|string[]|undefined>>}){
 const actor=await currentUser();if(!actor)redirect("/login");const locale=await getLocale(),t=(en:string,ar:string)=>translate(locale,en,ar);
 const memberships=await db.membership.findMany({where:{userId:actor.id,status:"ACTIVE"},include:{tenant:{include:{companies:{orderBy:{name:"asc"}}}}}});
 const scopes=(await Promise.all(memberships.flatMap(({tenant})=>tenant.companies.map(async company=>{
  const rights=await readableCompanyPermissions({userId:actor.id,tenantId:tenant.id,companyId:company.id,permissions:["supplier:read","purchase-order:read","inventory-stock:read","ledger:read"]});if(Object.values(rights).some(r=>r===false))return null;return {tenantId:tenant.id,companyId:company.id,value:`${tenant.id}:${company.id}`,label:`${tenant.name} / ${company.name}`,rights};
 })))).filter(s=>s!==null);
 const query=await searchParams,scope=scopes.find(s=>s.value===query.scope)??(query.scope?undefined:scopes[0]),parsed=z.coerce.number().int().min(0).max(100000).safeParse(query.page??0),page=parsed.success?parsed.data:0;
 const valid=parsed.success&&!Object.values(query).some(v=>Array.isArray(v));
 const filter=(rights:string[]|null|false)=>rights===null?{}:{branchId:{in:Array.isArray(rights)?rights:[]}};
 const rows=scope&&valid?await db.supplierSettlement.findMany({where:{tenantId:scope.tenantId,companyId:scope.companyId,AND:[filter(scope.rights["ledger:read"]),filter(scope.rights["inventory-stock:read"])],receipt:{order:{...filter(scope.rights["purchase-order:read"]),supplier:filter(scope.rights["supplier:read"])}}},orderBy:[{createdAt:"desc"},{id:"asc"}],skip:page*50,take:51,include:{receipt:{select:{order:{select:{number:true,supplierName:true}},branch:{select:{name:true}}}},entry:{select:{id:true,number:true,entryDate:true,currency:true,reversal:{select:{id:true,number:true}}}}}}):[];
 const pageLink=(n:number)=>`/purchasing/settlements?${new URLSearchParams({scope:scope!.value,page:String(n)})}`;
 return <main><style>{`.settlement-table{width:100%;min-width:750px;border-collapse:collapse}.settlement-table td,.settlement-table th{padding:12px;text-align:start;border-bottom:1px solid #ddd}`}</style><header><strong>FINAL <span>ARROW</span> ERP</strong><LanguageSwitcher locale={locale}/><a href="/purchasing/receipts">{t("Goods receipts","استلام البضائع")}</a><a href="/purchasing/supplier-balances">{t("Supplier balances","أرصدة الموردين")}</a><a href="/workspace">{t("Workspace","مساحة العمل")}</a></header>
 <section className="hero"><p>{t("PURCHASING / ACCOUNTING","المشتريات / المحاسبة")}</p><h1>{t("Supplier settlements.","تسويات الموردين.")}</h1><p className="sub">{t("Recorded payments and refunds linked to received goods and balanced journals.","دفعات واستردادات مسجّلة مرتبطة بالاستلام وقيود محاسبية متوازنة.")}</p></section>
 <section className="panel"><h2>{t("Record a payment or refund","تسجيل دفعة أو استرداد")}</h2><p>{t("Open a posted goods receipt and choose Supplier payment / refund. Partial payments cannot exceed its payable balance; refunds cannot exceed its supplier debit balance. A cash/bank asset and payment reference are required. This records an actual movement; no bank transfer is performed.","افتح مستند استلام مرحّل واختر دفعة المورد / الاسترداد. الدفعة الجزئية لا تتجاوز المستحق، والاسترداد لا يتجاوز الرصيد لصالح الشركة. يلزم حساب النقد أو البنك ومرجع العملية. يُسجّل هذا حركة تمت بالفعل ولا ينفّذ تحويلًا بنكيًا.")}</p><a href="/purchasing/receipts">{t("Open goods receipts","فتح سجل الاستلام")}</a></section>
 <section className="panel"><h2>{t("Saved settlements","التسويات المحفوظة")}</h2>{!scopes.length?<p>{t("No accessible settlements.","لا توجد تسويات متاحة بالصلاحيات الحالية.")}</p>:<><form method="get"><label>{t("Company","الشركة")}<select name="scope" defaultValue={scope?.value??""}>{scopes.map(s=><option key={s.value} value={s.value}>{s.label}</option>)}</select></label><button>{t("Select company","اختيار الشركة")}</button></form>{(!valid||!scope)&&<p role="alert">{t("Invalid or unavailable filters.","الفلاتر غير صالحة أو غير متاحة.")}</p>}
 <div style={{overflowX:"auto"}}><table className="settlement-table"><thead><tr>{[t("Date","التاريخ"),t("Order / supplier","أمر الشراء / المورد"),t("Branch","الفرع"),t("Type","النوع"),t("Reference","المرجع"),t("Amount","المبلغ"),t("Journal","القيد"),t("Source","المصدر")].map(label=><th key={label}>{label}</th>)}</tr></thead><tbody>{rows.slice(0,50).map(s=><tr key={s.id}><td>{s.entry.entryDate.toISOString().slice(0,10)}</td><td>{s.receipt.order.number} · {s.receipt.order.supplierName}</td><td>{s.receipt.branch.name}</td><td>{s.kind==="PAYMENT"?t("Payment","دفعة"):t("Refund","استرداد")}</td><td>{s.reference}</td><td>{s.amount.toFixed(3)} {s.entry.currency}</td><td><a href={`/accounting/ledger/journals/${s.entry.reversal?.id??s.entry.id}`}>{s.entry.reversal?t("Reversed","معكوس"):t("Posted","مرحّل")}</a></td><td><a href={`/purchasing/receipts/${s.receiptId}/settlements`}>{t("Receipt settlement","تسوية الاستلام")}</a></td></tr>)}</tbody></table></div>{!rows.length&&<p>{t("No saved settlements match these filters.","لا توجد تسويات محفوظة تطابق الفلاتر.")}</p>}{scope&&valid&&page>0&&<a href={pageLink(page-1)}>{t("Previous","السابق")}</a>}{scope&&valid&&rows.length>50&&<a href={pageLink(page+1)}>{t("Next","التالي")}</a>}</>}</section></main>;
}
