"use client";
import {useState} from "react";
import {translate,type Locale} from "@/lib/locale";
export type ExpenseVatSnapshot={supplierName:string;supplierTaxNumber:string|null;reference:string;treatment:string;recoverable:boolean;netAmount:string;taxAmount:string;recoverableTax:string;inputAccountId:string|null};
export type ExpenseVatSetup={required:boolean;netAmount:string;amount:string;inputAccountId:string|null;snapshot:ExpenseVatSnapshot|null};
const fixed=(n:bigint)=>`${n/BigInt(1000)}.${(n%BigInt(1000)).toString().padStart(3,"0")}`;
export function ExpenseVatFields({setup,locale,busy}:{setup:ExpenseVatSetup;locale:Locale;busy:boolean}){
 const t=(en:string,ar:string)=>translate(locale,en,ar),[choice,setChoice]=useState("");
 const net=BigInt(setup.netAmount.replace(".","")),tax=choice.startsWith("STANDARD")?(net*BigInt(5)+BigInt(50))/BigInt(100):BigInt(0),input=choice.endsWith("-R")?tax:BigInt(0);
 return <fieldset disabled={busy} style={{gridColumn:"1 / -1",padding:16,border:"1px solid #ddd",borderRadius:8}}><legend>{t("Expense VAT","ضريبة المصروف")}</legend><p>{t("Enter the amount before tax. Choose the treatment and deductibility from the actual supplier invoice. Non-deductible VAT increases expense cost. Imports, reverse charge, inclusive pricing and partial recovery percentages are not supported.","أدخل المبلغ قبل الضريبة. حدّد المعالجة وقابلية الخصم من فاتورة المورد الفعلية. تزيد الضريبة غير القابلة للخصم تكلفة المصروف. الاستيراد والاحتساب العكسي والأسعار الشاملة ونسب الخصم الجزئي غير مشمولة.")}</p><label>{t("Supplier name on invoice","اسم المورد في الفاتورة")}<input name="expenseSupplierName" required minLength={2} maxLength={200}/></label><label>{t("Supplier invoice reference","مرجع فاتورة المورد")}<input name="expenseReference" required minLength={3} maxLength={120}/></label><label>{t("VAT treatment","المعالجة الضريبية")}<select name="expenseTreatment" value={choice} required onChange={e=>setChoice(e.target.value)}><option value="">{t("Choose treatment and deductibility","اختر المعالجة وقابلية الخصم")}</option><option value="STANDARD-R">{t("Standard 5% — deductible","أساسي ٥٪ — قابل للخصم")}</option><option value="STANDARD-N">{t("Standard 5% — non-deductible","أساسي ٥٪ — غير قابل للخصم")}</option><option value="ZERO-N">{t("Zero-rated 0%","صفري ٠٪")}</option><option value="EXEMPT-N">{t("Exempt","معفى")}</option><option value="NO_VAT-N">{t("No VAT charged","لا توجد ضريبة مفروضة")}</option></select></label><label>{t("Supplier VAT number (required for standard tax)","رقم المورد الضريبي (إلزامي للضريبة الأساسية)")}<input name="expenseSupplierTaxNumber" required={choice.startsWith("STANDARD")} minLength={3} maxLength={40}/></label>{choice&&<p role="status">{t("Net","الصافي")}: {setup.netAmount} · {t("VAT","الضريبة")}: {fixed(tax)} · {t("Deductible VAT","الضريبة القابلة للخصم")}: {fixed(input)} · <strong>{t("Gross amount","المبلغ شامل الضريبة")}: {fixed(net+tax)} OMR</strong> · {t("Expense cost","تكلفة المصروف")}: {fixed(net+tax-input)} OMR</p>}{!setup.inputAccountId&&<p>{t("Configure a separate input VAT asset account before posting deductible tax.","اضبط حساب أصل مستقل لضريبة المدخلات قبل ترحيل ضريبة قابلة للخصم.")} <a href="/accounting/vat-settings">{t("VAT settings","إعدادات الضريبة")}</a></p>}</fieldset>;
}
export function ExpenseVatSummary({snapshot,gross,currency,locale}:{snapshot:ExpenseVatSnapshot;gross:string;currency:string;locale:Locale}){
 const t=(en:string,ar:string)=>translate(locale,en,ar),labels:Record<string,string>={STANDARD:t("Standard 5%","أساسي ٥٪"),ZERO:t("Zero-rated","صفري"),EXEMPT:t("Exempt","معفى"),NO_VAT:t("No VAT charged","لا توجد ضريبة مفروضة")};
 return <div><h3>{t("Saved expense VAT","ضريبة المصروف المحفوظة")}</h3><p>{snapshot.supplierName} · {snapshot.supplierTaxNumber??t("No VAT number recorded","لم يُسجّل رقم ضريبي")} · {snapshot.reference}</p><p>{labels[snapshot.treatment]} · {snapshot.recoverable?t("Deductible","قابل للخصم"):t("Non-deductible","غير قابل للخصم")}</p><p>{t("Net","الصافي")}: {snapshot.netAmount} · {t("VAT","الضريبة")}: {snapshot.taxAmount} · {t("Deductible VAT","الضريبة القابلة للخصم")}: {snapshot.recoverableTax} · <strong>{t("Gross amount","المبلغ شامل الضريبة")}: {gross} {currency}</strong></p><p>{t("Internal accounting record. Reversals retain this original snapshot.","سجل محاسبي داخلي. تحتفظ التصحيحات بهذه التفاصيل الأصلية.")}</p></div>;
}
