"use client";
import {useState,type ChangeEvent} from "react";
import {translate,type Locale} from "@/lib/locale";
export type PurchaseVatSetup={required:boolean;recorded:boolean;inputAccountId:string|null;amount:string;lines:{id:string;description:string;quantity:string;unitPrice:string;net:string}[];snapshot:{netAmount:string;taxAmount:string;recoverableTax:string;inputAccountId:string|null;supplierName:string;supplierTaxNumber:string|null;reference:string;details:{receiptLineId:string;quantity:string;net:string;tax:string;treatment:string;recoverable:boolean}[]}|null};
const scaled=(s:string)=>BigInt(s.replace(".",""));
const fixed=(n:bigint)=>`${n/BigInt(1000)}.${(n%BigInt(1000)).toString().padStart(3,"0")}`;
export function PurchaseVatFields({setup,locale,busy}:{setup:PurchaseVatSetup;locale:Locale;busy:boolean}){
 const t=(en:string,ar:string)=>translate(locale,en,ar),[estimate,setEstimate]=useState<{net:string;tax:string;input:string;gross:string}|null>(null);
 function estimateTax(event:ChangeEvent<HTMLFieldSetElement>){const form=event.currentTarget.closest("form");if(!form)return;const data=new FormData(form);let net=BigInt(0),tax=BigInt(0),input=BigInt(0);for(const l of setup.lines){const value=String(data.get(`purchase-tax-${l.id}`)??"");if(!value){setEstimate(null);return;}const n=scaled(l.net),v=value.startsWith("STANDARD")?(n*BigInt(5)+BigInt(50))/BigInt(100):BigInt(0);net+=n;tax+=v;if(value.endsWith("-R"))input+=v;}setEstimate({net:fixed(net),tax:fixed(tax),input:fixed(input),gross:fixed(net+tax)});}
 return <fieldset disabled={busy} onChange={estimateTax} style={{gridColumn:"1 / -1",padding:16,border:"1px solid #ddd",borderRadius:8}}><legend>{t("Purchase VAT classification","تصنيف ضريبة المشتريات")}</legend><p>{t("Prices exclude VAT. Confirm each treatment and deductibility from the actual supplier document. Deductible tax posts to input VAT; non-deductible tax adds to purchase cost. Imports, reverse charge and partial recovery percentages are not supported here.","الأسعار لا تشمل الضريبة. حدّد المعالجة وقابلية الخصم من مستند المورد الفعلي. تُرحّل الضريبة القابلة للخصم إلى المدخلات، وغير القابلة للخصم إلى تكلفة المشتريات. الاستيراد والاحتساب العكسي ونسب الخصم الجزئي غير مشمولة هنا.")}</p><label>{t("Supplier invoice reference","مرجع فاتورة المورد")}<input name="purchaseReference" required minLength={3} maxLength={120}/></label><label>{t("Supplier VAT number (required for standard tax)","رقم المورد الضريبي (إلزامي للضريبة الأساسية)")}<input name="supplierTaxNumber" minLength={3} maxLength={40}/></label>{setup.lines.map(l=><label key={l.id} style={{marginTop:12}}>{l.description} · {l.quantity} × {l.unitPrice} = {l.net} OMR<select name={`purchase-tax-${l.id}`} required defaultValue=""><option value="">{t("Choose treatment and deductibility","اختر المعالجة وقابلية الخصم")}</option><option value="STANDARD-R">{t("Standard 5% — deductible","أساسي ٥٪ — قابل للخصم")}</option><option value="STANDARD-N">{t("Standard 5% — non-deductible","أساسي ٥٪ — غير قابل للخصم")}</option><option value="ZERO-N">{t("Zero-rated 0%","صفري ٠٪")}</option><option value="EXEMPT-N">{t("Exempt","معفى")}</option><option value="NO_VAT-N">{t("No VAT charged","لا توجد ضريبة مفروضة")}</option></select></label>)}{!setup.inputAccountId&&<p>{t("Configure an input VAT asset account before posting deductible tax.","اضبط حساب أصل ضريبة المدخلات قبل ترحيل ضريبة قابلة للخصم.")} <a href="/accounting/vat-settings">{t("VAT settings","إعدادات الضريبة")}</a></p>}{estimate?<p role="status">{t("Net","الصافي")}: {estimate.net} · {t("VAT","الضريبة")}: {estimate.tax} · {t("Deductible VAT","الضريبة القابلة للخصم")}: {estimate.input} · <strong>{t("Supplier payable including VAT","مستحق المورد شامل الضريبة")}: {estimate.gross} OMR</strong></p>:<p>{t("Complete every line to preview the gross payable. Amounts are recalculated when posting.","حدّد جميع البنود لعرض المستحق شامل الضريبة. يُعاد احتساب المبالغ عند الترحيل.")}</p>}</fieldset>;
}
export function PurchaseVatSummary({snapshot,currency,locale,recorded=true}:{recorded?:boolean;snapshot:NonNullable<PurchaseVatSetup["snapshot"]>;currency:string;locale:Locale}){
 const t=(en:string,ar:string)=>translate(locale,en,ar),labels:Record<string,string>={STANDARD:t("Standard 5%","أساسي ٥٪"),ZERO:t("Zero-rated","صفري"),EXEMPT:t("Exempt","معفى"),NO_VAT:t("No VAT charged","لا توجد ضريبة مفروضة")};
 return <div><h3>{recorded?t("Saved purchase VAT","ضريبة المشتريات المحفوظة"):t("Return VAT preview — recalculated at posting","معاينة ضريبة المرتجع — يُعاد احتسابها عند الترحيل")}</h3><p>{snapshot.supplierName} · {snapshot.supplierTaxNumber??t("No VAT number recorded","لم يُسجّل رقم ضريبي")} · {snapshot.reference}</p><p>{t("Net","الصافي")}: {snapshot.netAmount} · {t("VAT","الضريبة")}: {snapshot.taxAmount} · {t("Deductible VAT","الضريبة القابلة للخصم")}: {snapshot.recoverableTax} {currency}</p><ul>{snapshot.details.map(l=><li key={l.receiptLineId}>{l.quantity} · {labels[l.treatment]} · {t("Net","الصافي")}: {l.net} · {t("VAT","الضريبة")}: {l.tax} · {l.recoverable?t("Deductible","قابل للخصم"):t("Non-deductible","غير قابل للخصم")}</li>)}</ul></div>;
}
