"use client";
import {useState} from "react";
import {translate,type Locale} from "@/lib/locale";
type Refund={id:string;amount:string;reference:string;reason:string;entry:{id:string;number:string;entryDate:string;reversal:{id:string;number:string}|null}};
type State={eligible:boolean;latest:string;amount:string;netAmount:string;taxAmount:string;currency:string;original:{id:string;number:string;reversed:boolean}|null;activeId:string|null;count:number;refunds:Refund[]};
type Pending={tenantId:string;requestId:string;entryDate:string;reference:string;reason:string};
export function PosRefunds({id,tenantId,canManage,locale,onRecorded}:{id:string;tenantId:string;canManage:boolean;locale:Locale;onRecorded:()=>void}){
 const t=(en:string,ar:string)=>translate(locale,en,ar),endpoint=`/api/pos/orders/${id}/refunds`;
 const [open,setOpen]=useState(false),[busy,setBusy]=useState(false),[state,setState]=useState<State|null>(null),[message,setMessage]=useState("");const [pending,setPending]=useState<Pending|null>(null);
 async function inspect(){const r=await fetch(`${endpoint}?${new URLSearchParams({tenantId})}`),data=await r.json();if(!r.ok)throw new Error(data.error);setState(data as State);}
 async function load(){setOpen(true);setBusy(true);setMessage("");try{await inspect();}catch(error){setMessage(error instanceof Error?error.message:t("Could not load refunds","تعذر تحميل الاستردادات"));}finally{setBusy(false);}}
 async function record(body:Pending){setPending(body);setBusy(true);setMessage("");try{const r=await fetch(endpoint,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)}),data=await r.json();if(!r.ok){setMessage(data.error);setPending(null);await inspect();return;}setPending(null);setState(old=>old?{...old,eligible:false,activeId:body.requestId}:old);onRecorded();setMessage(t("Full refund recorded; no money was transferred","سُجّل الاسترداد الكامل؛ لم تُحوّل أموال"));try{await inspect();}catch{setMessage(t("Refund saved. Could not refresh history; reload to inspect it.","حُفظ الاسترداد. تعذر تحديث السجل؛ أعد تحميله للفحص."));}}catch{setMessage(t("Connection failed. Check history or retry the same record before creating another.","فشل الاتصال. افحص السجل أو أعد محاولة العملية نفسها قبل إنشاء غيرها."));}finally{setBusy(false);}}
 return <div><button type="button" disabled={busy} onClick={()=>open?setOpen(false):void load()}>{t("Full refund / history","الاسترداد الكامل / السجل")}</button>{open&&<section><p>{t("Records a full refund already made, including saved VAT, to the original cash/bank account. Post the original sale first. This does not transfer money, refund a card, return stock or issue a statutory credit note. Partial refunds are not supported here.","يسجّل استردادًا كاملًا تم فعليًا شاملًا الضريبة المحفوظة إلى حساب النقد أو البنك الأصلي. رحّل البيع أولًا. لا يحوّل أموالًا ولا يسترد من البطاقة ولا يعيد مخزونًا ولا يصدر إشعارًا ضريبيًا معتمدًا. الاسترداد الجزئي غير مدعوم هنا.")}</p>{message&&<p role="status">{message}</p>}{busy&&<p role="status">{t("Working…","جارٍ التنفيذ…")}</p>}{!busy&&<button type="button" onClick={()=>void load()}>{t("Refresh history","تحديث السجل")}</button>}
 {state&&<><p>{t("Full gross amount","المبلغ الكامل الشامل")}: {state.amount} {state.currency} · {t("Net","الصافي")}: {state.netAmount} · {t("VAT","الضريبة")}: {state.taxAmount}</p>{state.original?<p><a href={`/accounting/ledger/journals/${state.original.id}`}>{t("Original sale journal","قيد البيع الأصلي")}</a>{state.original.reversed&&` · ${t("Reversed","معكوس")}`}</p>:<p>{t("Post the original sale journal first.","رحّل قيد البيع الأصلي أولًا.")}</p>}{state.activeId&&<p>{t("This order already has an active full refund. Reverse its refund journal to correct it before recording another.","يوجد استرداد كامل سارٍ لهذا الطلب. اعكس قيد الاسترداد لتصحيحه قبل تسجيل غيره.")}</p>}{state.refunds.map(f=><article className="card" key={f.id}><strong>{f.reference} · {f.amount} {state.currency}</strong><p>{f.entry.entryDate.slice(0,10)} UTC · {f.reason}</p><p><a href={`/accounting/ledger/journals/${f.entry.id}`}>{f.entry.number}</a>{f.entry.reversal&&<> · <a href={`/accounting/ledger/journals/${f.entry.reversal.id}`}>{t("Reversed","معكوس")}</a></>}</p></article>)}{state.count>50&&<p>{t("Showing the latest 50 records. Use the refund report for all matching records.","تظهر أحدث ٥٠ عملية. استخدم تقرير الاسترداد لكل العمليات المطابقة.")}</p>}
 {canManage&&state.eligible&&!pending&&<form action={form=>record({tenantId,requestId:crypto.randomUUID(),entryDate:String(form.get("entryDate")),reference:String(form.get("reference")).trim(),reason:String(form.get("reason")).trim()})}><label>{t("Refund journal date (UTC)","تاريخ قيد الاسترداد (UTC)")} <input name="entryDate" type="date" required min={state.latest} disabled={busy}/></label><label>{t("Actual refund reference","مرجع الاسترداد الفعلي")} <input name="reference" required minLength={3} maxLength={120} disabled={busy}/></label><label>{t("Reason","السبب")} <input name="reason" required minLength={3} maxLength={500} disabled={busy}/></label><button disabled={busy}>{t("Record full refund already made","تسجيل الاسترداد الكامل الذي تم فعليًا")}</button></form>}</>}
 {pending&&<button type="button" disabled={busy} onClick={()=>void record(pending)}>{t("Retry the same refund record","إعادة محاولة سجل الاسترداد نفسه")}</button>}</section>}</div>;
}
type Scope={tenantId:string;companyId:string;branchId:string};
type Summary={currency:string;count:number;reversedCount:number;netAmount:string;taxAmount:string;amount:string;reversedAmount:string};
export function PosRefundReport({scope,locale}:{scope:Scope;locale:Locale}){
 const t=(en:string,ar:string)=>translate(locale,en,ar),[busy,setBusy]=useState(false),[message,setMessage]=useState("");const [result,setResult]=useState<{from:string;to:string;count:number;summary:Summary[]}|null>(null);
 return <section><h2>{t("Recorded full refunds","الاستردادات الكاملة المسجّلة")}</h2><p>{t("Uses refund journal dates (UTC), up to 31 days, and current reversal status. Active totals exclude corrected refund journals. Paid sales remain in their separate payment-date register. These totals are not historical balances or cash transfers.","يعتمد تاريخ قيد الاسترداد (UTC) حتى ٣١ يومًا وحالة العكس الحالية. الإجماليات السارية تستثني قيود الاسترداد المصحّحة. يبقى البيع المدفوع في سجلّه المنفصل بحسب تاريخ الدفع. هذه الإجماليات ليست أرصدة تاريخية أو تحويلات نقدية.")}</p><form action={async form=>{setBusy(true);setMessage("");setResult(null);const from=String(form.get("from")),to=String(form.get("to"));try{const r=await fetch(`/api/pos/refunds/report?${new URLSearchParams({...scope,from,to})}`),data=await r.json();if(r.ok)setResult({from,to,count:data.count,summary:data.summary});else setMessage(data.error);}catch{setMessage(t("Network request failed","فشل الاتصال بالشبكة"));}finally{setBusy(false);}}}><label>{t("From","من")} <input name="from" type="date" required/></label><label>{t("To","إلى")} <input name="to" type="date" required/></label><button disabled={busy}>{t("Generate refund report","إنشاء تقرير الاسترداد")}</button></form>{message&&<p role="status">{message}</p>}{result&&<><p>{result.from} — {result.to} UTC · {result.count} {t("recorded refunds","استردادات مسجّلة")}</p>{result.count===0&&<p>{t("No recorded full refunds match these dates.","لا توجد استردادات كاملة مسجّلة تطابق هذه الفترة.")}</p>}<a href={`/api/pos/refunds/report?${new URLSearchParams({...scope,from:result.from,to:result.to,format:"csv"})}`}>{t("Download refund CSV","تنزيل CSV الاستردادات")}</a>{result.summary.map(g=><article className="card" key={g.currency}><strong>{t("Active gross refunds","الاستردادات الشاملة السارية")}: {g.amount} {g.currency}</strong><p>{t("Net","الصافي")}: {g.netAmount} · {t("VAT","الضريبة")}: {g.taxAmount}</p><p>{t("Recorded / reversed","المسجّلة / المعكوسة")}: {g.count} / {g.reversedCount} · {t("Reversed gross","المبلغ الشامل المعكوس")}: {g.reversedAmount}</p></article>)}</>}</section>;
}
