"use client";
import {useCallback,useEffect,useState} from "react";
import {PosReport} from "./report";
import {translate,type Locale} from "@/lib/locale";
type Option={tenantId:string;companyId:string;branchId:string;label:string;currency:string;canManage:boolean;canManageShared:boolean};
type Item={id:string;code:string;name:string;category:string;price:string;currency:string;active:boolean;branchId:string|null};
type Order={id:string;number:string;type:"DINE_IN"|"TAKEAWAY";tableLabel:string|null;total:string;currency:string;status:"OPEN"|"PAID"|"CANCELLED";kitchenStatus:"WAITING"|"PREPARING"|"READY"|"SERVED";paymentMethod:string|null;paymentReference:string|null;cancelReason:string|null;change:string|null;lines:{id:string;itemName:string;quantity:number;unitPrice:string;amount:string}[]};
export function PosWorkspace({options,locale}:{options:Option[];locale:Locale}){
 const t=useCallback((en:string,ar:string)=>translate(locale,en,ar),[locale]);const [selected,setSelected]=useState(0);const option=options[selected];
 const [items,setItems]=useState<Item[]>([]);const [itemNext,setItemNext]=useState<number|null>(null);const [orders,setOrders]=useState<Order[]>([]);const [page,setPage]=useState(0);const [next,setNext]=useState<number|null>(null);
 const [menuCategory,setMenuCategory]=useState("");const [availability,setAvailability]=useState("ALL");
 const [reportVersion,setReportVersion]=useState(0);
 const [status,setStatus]=useState("");const [cart,setCart]=useState<Record<string,number>>({});const [search,setSearch]=useState("");const [busy,setBusy]=useState(false);const [message,setMessage]=useState("");
 const scope=useCallback(()=>({tenantId:option.tenantId,companyId:option.companyId,branchId:option.branchId}),[option]);
 const load=useCallback(async(number=0)=>{if(!option)return;try{const response=await fetch(`/api/pos/orders?${new URLSearchParams({...scope(),page:String(number),...(status?{status}:{})})}`);const data=await response.json();if(!response.ok){setMessage(data.error);return;}setOrders(data.orders);setPage(number);setNext(data.nextPage);}catch{setMessage(t("Network request failed","فشل الاتصال بالشبكة"));}},[option,scope,status,t]);
 const loadItems=useCallback(async(number=0)=>{if(!option)return;try{const response=await fetch(`/api/pos/items?${new URLSearchParams({...scope(),page:String(number),includeInactive:"true"})}`);const data=await response.json();if(!response.ok){setMessage(data.error);return;}setItems(old=>number===0?data.items:[...old,...data.items]);setItemNext(data.nextPage);}catch{setMessage(t("Network request failed","فشل الاتصال بالشبكة"));}},[option,scope,t]);
 useEffect(()=>{void load();},[load]);useEffect(()=>{void loadItems();},[loadItems]);
 async function save(url:string,method:"POST"|"PATCH",body:object){setBusy(true);setMessage("");try{const response=await fetch(url,{method,headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const data=await response.json();setMessage(response.ok?t("Saved","تم الحفظ"):data.error);if(response.ok){setReportVersion(version=>version+1);if(url==="/api/pos/orders")setCart({});await load();if(url.includes("items")){setCart({});await loadItems();}}}catch{setMessage(t("Network request failed","فشل الاتصال بالشبكة"));}finally{setBusy(false);}}
 if(!option)return <section className="panel"><p>{t("No accessible POS branches.","لا توجد فروع نقاط بيع متاحة.")}</p></section>;
 const cartItems=items.filter(item=>cart[item.id]);
 const categories=[...new Set(items.map(item=>item.category))].sort((a,b)=>a.localeCompare(b));
 const filteredItems=items.filter(item=>(!menuCategory||item.category===menuCategory)&&(availability==="ALL"||item.active===(availability==="AVAILABLE"))&&`${item.code} ${item.name} ${item.category}`.toLocaleLowerCase().includes(search.toLocaleLowerCase()));
 const estimated=new Map<string,bigint>();
 for(const item of cartItems){const [whole,fraction=""]=item.price.split(".");const units=BigInt(whole)*BigInt(1000)+BigInt(fraction.padEnd(3,"0"));estimated.set(item.currency,(estimated.get(item.currency)??BigInt(0))+units*BigInt(cart[item.id]));}
 const formatUnits=(value:bigint)=>`${value/BigInt(1000)}.${String(value%BigInt(1000)).padStart(3,"0")}`;
 return <section className="panel"><label>{t("Branch","الفرع")} <select disabled={busy} value={selected} onChange={event=>{setSelected(Number(event.target.value));setItems([]);setOrders([]);setCart({});setSearch("");setMenuCategory("");setAvailability("ALL");setMessage("");}}>{options.map((entry,index)=><option key={entry.branchId} value={index}>{entry.label}</option>)}</select></label>
 <p>{t("Payments are recorded manually. Card recording does not charge a card. Tax, inventory consumption, kitchen printers and ledger posting are not connected yet.","يُسجّل الدفع يدوياً. تسجيل البطاقة لا يخصم منها. الضرائب واستهلاك المخزون وطابعات المطبخ والترحيل المحاسبي لم تُربط بعد.")}</p>{message&&<p role="status">{message}</p>}
 {option.canManage&&<details><summary>{t("Add menu item","إضافة صنف للقائمة")}</summary><form key={option.branchId} action={form=>save("/api/pos/items","POST",{...scope(),code:form.get("code"),name:form.get("name"),category:form.get("category"),price:form.get("price")})}>
 <label>{t("Code","الرمز")} <input name="code" required pattern="[A-Z0-9-]{2,30}"/></label><label>{t("Name","الاسم")} <input name="name" required minLength={2} maxLength={200}/></label><label>{t("Category","التصنيف")} <input name="category" required minLength={2} maxLength={80}/></label><label>{t("Price","السعر")} · {option.currency} <input name="price" type="number" min="0.001" max="999999999" step="0.001" required/></label><button disabled={busy}>{t("Create menu item","إنشاء الصنف")}</button></form></details>}
 <h2>{t("Menu","القائمة")}</h2><label>{t("Search loaded menu items","بحث في الأصناف المحملة")} <input value={search} onChange={event=>setSearch(event.target.value)} maxLength={120}/></label>
 <label>{t("Category","التصنيف")} <select value={menuCategory} onChange={event=>setMenuCategory(event.target.value)}><option value="">{t("All loaded categories","كل التصنيفات المحملة")}</option>{categories.map(category=><option key={category} value={category}>{category}</option>)}</select></label>
 <label>{t("Availability","التوفر")} <select value={availability} onChange={event=>setAvailability(event.target.value)}><option value="ALL">{t("All items","كل الأصناف")}</option><option value="AVAILABLE">{t("Available","متاح")}</option><option value="UNAVAILABLE">{t("Unavailable","غير متاح")}</option></select></label>
 <button type="button" onClick={()=>{setSearch("");setMenuCategory("");setAvailability("ALL");}}>{t("Reset menu filters","إعادة ضبط فلاتر القائمة")}</button>
 <p>{t("Filters apply to loaded items. Load more to include additional menu items. Filtering keeps the current cart.","تُطبق الفلاتر على الأصناف المحملة. حمّل المزيد لإظهار أصناف إضافية. التصفية تحافظ على السلة الحالية.")}</p>
 {filteredItems.length===0&&<p>{t("No loaded items match these filters.","لا توجد أصناف محملة تطابق هذه الفلاتر.")}</p>}
 <div className="cards">{filteredItems.map(item=><article className="card" key={item.id}><strong>{item.name}</strong><p>{item.category} · {item.price} {item.currency}</p>{!item.active&&<p>{t("Unavailable","غير متاح")}</p>}
 {option.canManage&&item.active&&<button disabled={busy||((cart[item.id]??0)>=999)||(!cart[item.id]&&Object.keys(cart).length>=100)} onClick={()=>setCart(old=>({...old,[item.id]:(old[item.id]??0)+1}))}>{t("Add to order","إضافة للطلب")}</button>}
 {option.canManage&&(item.branchId===option.branchId||(!item.branchId&&option.canManageShared))&&<button disabled={busy} onClick={()=>void save(`/api/pos/items/${item.id}`,"PATCH",{tenantId:option.tenantId,active:!item.active})}>{item.active?t("Make unavailable","جعله غير متاح"):t("Make available","جعله متاحاً")}</button>}
 {option.canManage&&(item.branchId===option.branchId||(!item.branchId&&option.canManageShared))&&<details><summary>{t("Edit menu item","تعديل الصنف")}</summary><form key={`${item.id}:${item.name}:${item.category}:${item.price}`} action={form=>save(`/api/pos/items/${item.id}`,"PATCH",{tenantId:option.tenantId,name:form.get("name"),category:form.get("category"),price:form.get("price")})}>
 <label>{t("Name","الاسم")} <input name="name" required minLength={2} maxLength={200} defaultValue={item.name}/></label><label>{t("Category","التصنيف")} <input name="category" required minLength={2} maxLength={80} defaultValue={item.category}/></label><label>{t("Price","السعر")} · {item.currency} <input name="price" type="number" min="0.001" max="999999999.999" step="0.001" defaultValue={item.price} required/></label><button disabled={busy}>{t("Save menu changes","حفظ تعديل الصنف")}</button></form><p>{t("Existing orders keep their saved names and prices. Saving clears the current cart.","تحتفظ الطلبات السابقة بأسمائها وأسعارها المحفوظة. الحفظ يفرّغ السلة الحالية.")}</p></details>}
 </article>)}</div>
 {itemNext!==null&&<button disabled={busy} onClick={()=>void loadItems(itemNext)}>{t("Load more items","تحميل أصناف إضافية")}</button>}
 {option.canManage&&<form key={`cart-${option.branchId}`} action={form=>save("/api/pos/orders","POST",{...scope(),number:form.get("number"),type:form.get("type"),tableLabel:form.get("tableLabel")||null,note:form.get("note")||null,lines:Object.entries(cart).map(([itemId,quantity])=>({itemId,quantity}))})}>
 <h2>{t("New order","طلب جديد")}</h2>{cartItems.map(item=><p key={item.id}>{item.name} · {cart[item.id]} × {item.price} {item.currency} <button type="button" disabled={busy} onClick={()=>setCart(old=>{const updated={...old};if(updated[item.id]>1)updated[item.id]--;else delete updated[item.id];return updated;})}>{t("Remove one","إزالة واحد")}</button></p>)}
 {Array.from(estimated.entries()).map(([currency,total])=><p key={currency}><strong>{t("Estimated total","الإجمالي التقديري")}: {formatUnits(total)} {currency}</strong></p>)}
 <p>{t("The server calculates the final total using current menu prices.","يحسب الخادم الإجمالي النهائي وفق أسعار القائمة الحالية.")}</p><label>{t("Order number","رقم الطلب")} <input name="number" required pattern="[A-Z0-9-]{2,30}"/></label><label>{t("Order type","نوع الطلب")} <select name="type"><option value="TAKEAWAY">{t("Takeaway","سفري")}</option><option value="DINE_IN">{t("Dine in","داخل المطعم")}</option></select></label><label>{t("Table (required for dine-in)","الطاولة (مطلوبة داخل المطعم)")} <input name="tableLabel" maxLength={80}/></label><label>{t("Note","ملاحظة")} <input name="note" maxLength={500}/></label><button disabled={busy||!Object.keys(cart).length}>{t("Create order","إنشاء الطلب")}</button><button type="button" disabled={busy} onClick={()=>setCart({})}>{t("Clear cart","تفريغ الطلب")}</button></form>}
 <PosReport key={`${option.branchId}:${reportVersion}`} scope={scope()} locale={locale}/>
 <h2>{t("Orders","الطلبات")}</h2><label>{t("Status","الحالة")} <select value={status} onChange={event=>{setStatus(event.target.value);setOrders([]);}}><option value="">{t("All statuses","كل الحالات")}</option><option value="OPEN">{t("Open","مفتوح")}</option><option value="PAID">{t("Paid","مدفوع")}</option><option value="CANCELLED">{t("Cancelled","ملغى")}</option></select></label>
 {orders.map(order=><article className="card" key={order.id}><strong>{order.number} · {t(order.status,{OPEN:"مفتوح",PAID:"مدفوع",CANCELLED:"ملغى"}[order.status])}</strong><p>{t("Preparation","التحضير")}: {t(order.kitchenStatus,{WAITING:"بانتظار التحضير",PREPARING:"قيد التحضير",READY:"جاهز",SERVED:"تم التسليم"}[order.kitchenStatus])}</p><p>{t(order.type,order.type==="DINE_IN"?"داخل المطعم":"سفري")} · {order.tableLabel} · {order.total} {order.currency}</p>{order.lines.map(line=><p key={line.id}>{line.itemName} · {line.quantity} × {line.unitPrice} = {line.amount}</p>)}<p><a href={`/pos/${order.id}`}>{t("View / print receipt","عرض / طباعة الإيصال")}</a></p>{order.paymentMethod&&<p>{t("Payment","الدفع")}: {t(order.paymentMethod,order.paymentMethod==="CASH"?"نقدي":"بطاقة")} · {order.paymentReference} {order.change&&`${t("Change","الباقي")}: ${order.change}`}</p>}{order.cancelReason&&<p>{order.cancelReason}</p>}
 {option.canManage&&order.status==="OPEN"&&<><form action={form=>save(`/api/pos/orders/${order.id}`,"PATCH",{tenantId:option.tenantId,action:"pay",method:"CASH",tendered:form.get("tendered")})}><label>{t("Cash received","النقد المستلم")} <input name="tendered" type="number" min={order.total} max="999999999" step="0.001" required/></label><button disabled={busy}>{t("Record cash payment","تسجيل الدفع النقدي")}</button></form>
 <form action={form=>save(`/api/pos/orders/${order.id}`,"PATCH",{tenantId:option.tenantId,action:"pay-card",reference:form.get("reference")})}><label>{t("Card payment reference","مرجع دفع البطاقة")} <input name="reference" minLength={3} maxLength={200} required/></label><button disabled={busy}>{t("Record card payment","تسجيل دفع البطاقة")}</button></form>
 <details><summary>{t("Cancel order","إلغاء الطلب")}</summary><form action={form=>save(`/api/pos/orders/${order.id}`,"PATCH",{tenantId:option.tenantId,action:"cancel",reason:form.get("reason")})}><label>{t("Reason","السبب")} <input name="reason" minLength={3} maxLength={500} required/></label><button disabled={busy}>{t("Cancel","إلغاء")}</button></form></details></>}
 </article>)}{orders.length===0&&<p>{t("No orders on this page.","لا توجد طلبات في هذه الصفحة.")}</p>}{page>0&&<button disabled={busy} onClick={()=>void load(page-1)}>{t("Previous","السابق")}</button>}{next!==null&&<button disabled={busy} onClick={()=>void load(next)}>{t("Next","التالي")}</button>}
 </section>;
}
