"use client";
import {useEffect,useRef,useState,type FormEvent} from "react";
import {parseBankCsv} from "@/lib/bank-csv";
import {translate,type Locale} from "@/lib/locale";
type Option={tenantId:string;companyId:string;label:string;currency:string;canPost:boolean};
type Account={id:string;code:string;name:string;type:string};
type Statement={voidedAt:string|null;id:string;reference:string;from:string;to:string;opening:string;closing:string;currency:string;account:{code:string;name:string};_count:{lines:number}};
type Payload={tenantId:string;companyId:string;requestId:string;accountId:string;reference:string;from:string;to:string;opening:string;closing:string;lines:ReturnType<typeof parseBankCsv>};
export function BankWorkspace({options,locale}:{options:Option[];locale:Locale}){
 const t=(en:string,ar:string)=>translate(locale,en,ar),[selected,setSelected]=useState(0),[accounts,setAccounts]=useState<Account[]>([]),[accountNext,setAccountNext]=useState<number|null>(null),[rows,setRows]=useState<Statement[]>([]),[page,setPage]=useState(0),[next,setNext]=useState<number|null>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState(""),[pending,setPending]=useState<Payload|null>(null);
 const working=useRef(false),formRef=useRef<HTMLFormElement>(null),scope=options[selected],storage=scope?`erp-bank-import:${scope.tenantId}:${scope.companyId}`:"";
 useEffect(()=>{
  if(!scope)return;const controller=new AbortController();setRows([]);setAccounts([]);setNext(null);setAccountNext(null);setPage(0);setMessage("");setPending(null);setBusy(true);
  try{const raw=sessionStorage.getItem(storage);if(raw){const p=JSON.parse(raw);if(p.tenantId===scope.tenantId&&p.companyId===scope.companyId&&typeof p.requestId==="string"&&Array.isArray(p.lines))setPending(p);}}catch{}
  const query=new URLSearchParams({tenantId:scope.tenantId,companyId:scope.companyId});
  Promise.all([fetch(`/api/bank/statements?${query}`,{signal:controller.signal}).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error);return d;}),fetch(`/api/ledger/accounts?${query}`,{signal:controller.signal}).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error);return d;})]).then(([s,a])=>{if(!controller.signal.aborted){setRows(s.statements);setNext(s.nextPage);setAccounts(a.accounts);setAccountNext(a.nextPage);}}).catch(e=>{if(!controller.signal.aborted)setMessage(e instanceof Error?e.message:"Connection failed");}).finally(()=>{if(!controller.signal.aborted)setBusy(false);});
  return ()=>controller.abort();
 },[scope,storage]);
 function remember(p:Payload|null){setPending(p);try{if(p)sessionStorage.setItem(storage,JSON.stringify(p));else sessionStorage.removeItem(storage);}catch{}}
 async function load(n:number){const r=await fetch(`/api/bank/statements?${new URLSearchParams({tenantId:scope.tenantId,companyId:scope.companyId,page:String(n)})}`),d=await r.json();if(!r.ok)throw new Error(d.error);setRows(d.statements);setPage(n);setNext(d.nextPage);}
 async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();if(working.current||!scope)return;let payload:Payload;
  try{const f=new FormData(event.currentTarget);payload=pending??{tenantId:scope.tenantId,companyId:scope.companyId,requestId:crypto.randomUUID(),accountId:String(f.get("accountId")),reference:String(f.get("reference")),from:String(f.get("from")),to:String(f.get("to")),opening:String(f.get("opening")),closing:String(f.get("closing")),lines:parseBankCsv(String(f.get("csv")))};}catch(e){setMessage(e instanceof Error?e.message:"Invalid CSV");return;}
  remember(payload);working.current=true;setBusy(true);setMessage("");let confirmed=false;
  try{const r=await fetch("/api/bank/statements",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)}),d=await r.json();if(!r.ok){if([400,404,409].includes(r.status))remember(null);setMessage(d.error);return;}confirmed=true;remember(null);formRef.current?.reset();setMessage(t("Statement saved. Open it to match movements.","حُفظ الكشف. افتحه لمطابقة الحركات."));await load(0);}catch{setMessage(confirmed?t("Statement saved. Refresh to load the latest register.","حُفظ الكشف. حدّث الصفحة لتحميل السجل الحالي."):t("Connection failed. Retry the saved request to confirm its result without duplication.","فشل الاتصال. أعد الطلب المحفوظ للتأكد من نتيجته دون تكراره."));}finally{working.current=false;setBusy(false);}
 }
 if(!options.length)return <section className="panel"><p>{t("Company-wide ledger read permission is required. Bank statements cannot be viewed with branch-only access.","يلزم إذن قراءة دفتر الأستاذ على مستوى الشركة. صلاحية الفرع وحدها لا تتيح الكشف البنكي للشركة.")}</p></section>;
 return <section><label>{t("Company","الشركة")}<select value={selected} disabled={busy||!!pending} onChange={e=>setSelected(Number(e.target.value))}>{options.map((o,i)=><option key={o.companyId} value={i}>{o.label}</option>)}</select></label>{message&&<p role="status">{message}</p>}
 <section className="panel"><h2>{t("Import a bank statement","استيراد كشف البنك")}</h2><p>{t("Use a dedicated bank asset account. Dates use YYYY-MM-DD; positive amounts are receipts and negative amounts are payments. Opening plus movements must equal closing. Saved statements cannot be edited and periods cannot overlap for the same account.","استخدم حساب أصل مخصصًا للبنك. التواريخ بصيغة YYYY-MM-DD؛ الموجب للمبالغ الواردة والسالب للصادرة. رصيد البداية مع الحركات يجب أن يساوي رصيد النهاية. الكشف المحفوظ لا يُعدّل، ولا تتداخل فتراته لنفس الحساب.")}</p><p>{t("Currency","العملة")}: {scope.currency} · {t("Maximum 500 movements per statement. Paste CSV with the exact header shown below.","الحد 500 حركة في الكشف. ألصق CSV بالعناوين الموضّحة أدناه.")}</p><pre dir="ltr">date,reference,amount{"\n"}2026-10-01,Bank receipt,125.000{"\n"}2026-10-02,Bank payment,-25.000</pre>
 {scope.canPost&&!pending&&<form ref={formRef} onSubmit={e=>void submit(e)}><fieldset disabled={busy}><label>{t("Bank asset account","حساب أصل البنك")}<select name="accountId" required><option value="">{t("Choose account","اختر الحساب")}</option>{accounts.filter(a=>a.type==="ASSET").map(a=><option key={a.id} value={a.id}>{a.code} · {a.name}</option>)}</select></label><label>{t("Statement reference","مرجع الكشف")}<input name="reference" minLength={3} maxLength={120} required/></label><label>{t("From","من")}<input name="from" type="date" required/></label><label>{t("To","إلى")}<input name="to" type="date" required/></label><label>{t("Opening balance","رصيد البداية")}<input name="opening" inputMode="decimal" required/></label><label>{t("Closing balance","رصيد النهاية")}<input name="closing" inputMode="decimal" required/></label><label>{t("Statement CSV","حركات الكشف بصيغة CSV")}<textarea name="csv" required rows={8} maxLength={180000} dir="ltr"/></label><button>{t("Save statement","حفظ الكشف")}</button></fieldset></form>}
 {pending&&scope.canPost&&<form onSubmit={e=>void submit(e)}><p>{t("Saved request awaiting confirmation","طلب محفوظ بانتظار التأكيد")}: {pending.reference} · {pending.lines.length}</p><button disabled={busy}>{t("Retry saved request","إعادة الطلب المحفوظ")}</button></form>}
 {accountNext!==null&&<button disabled={busy||!!pending} onClick={async()=>{if(working.current)return;working.current=true;setBusy(true);try{const r=await fetch(`/api/ledger/accounts?${new URLSearchParams({tenantId:scope.tenantId,companyId:scope.companyId,page:String(accountNext)})}`),d=await r.json();if(!r.ok)throw new Error(d.error);setAccounts(a=>[...a,...d.accounts]);setAccountNext(d.nextPage);}catch{setMessage(t("Accounts could not load","تعذر تحميل الحسابات"));}finally{working.current=false;setBusy(false);}}}>{t("More accounts","المزيد من الحسابات")}</button>}</section>
 <section className="panel"><h2>{t("Saved bank statements","كشوف البنك المحفوظة")}</h2>{rows.map(s=><article className="card" key={s.id}><h3><a href={`/accounting/bank/${s.id}`}>{s.reference}</a>{s.voidedAt?` · ${t("Voided","ملغى")}`:""}</h3><p>{s.account.code} · {s.account.name} · {s.from.slice(0,10)} — {s.to.slice(0,10)}</p><p>{t("Opening","البداية")}: {s.opening} · {t("Closing","النهاية")}: {s.closing} {s.currency} · {t("Movements","الحركات")}: {s._count.lines}</p></article>)}{!rows.length&&!busy&&<p>{t("No bank statements saved yet.","لا توجد كشوف بنكية محفوظة بعد.")}</p>}{[[page>0?page-1:null,t("Previous","السابق")],[next,t("Next","التالي")]].map(([n,label])=>typeof n==="number"&&<button key={label} disabled={busy} onClick={async()=>{if(working.current)return;working.current=true;setBusy(true);try{await load(n);}catch{setMessage(t("Statements could not load","تعذر تحميل الكشوف"));}finally{working.current=false;setBusy(false);}}}>{label}</button>)}</section></section>;
}
