"use client";
import {useEffect,useRef,useState,type FormEvent} from "react";
import {translate,type Locale} from "@/lib/locale";
type Account={id:string;code:string;name:string;type:string};
type State={receivable:{id:string}|null;collected:string;original:{id:string;number:string;currency:string;reversed:boolean}|null;balance:string;paymentAvailable:string;refundAvailable:string;latest:string;settlementCount:number;settlements:{id:string;kind:string;amount:string;reference:string;entry:{id:string;number:string;entryDate:string;currency:string;reversal:{id:string;number:string}|null}}[]};
type Payload={tenantId:string;requestId:string;kind:"COLLECTION"|"REFUND";amount:string;entryDate:string;assetAccountId:string;reference:string};
export function CustomerSettlementForm({tenantId,companyId,invoiceId,locale,canPost}:{tenantId:string;companyId:string;invoiceId:string;locale:Locale;canPost:boolean}){
 const t=(en:string,ar:string)=>translate(locale,en,ar),endpoint=`/api/invoices/${invoiceId}/settlements`,storage=`erp-customer-settlement:${tenantId}:${invoiceId}`;
 const [state,setState]=useState<State|null>(null),[accounts,setAccounts]=useState<Account[]>([]),[next,setNext]=useState<number|null>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState(""),[pending,setPending]=useState<Payload|null>(null);
 const working=useRef(false),formRef=useRef<HTMLFormElement>(null);
 useEffect(()=>{try{const value=sessionStorage.getItem(storage);if(value){const p=JSON.parse(value);if(p.tenantId===tenantId&&typeof p.requestId==="string"&&["COLLECTION","REFUND"].includes(p.kind)&&[p.amount,p.entryDate,p.assetAccountId,p.reference].every(v=>typeof v==="string"))setPending(p);}}catch{}},[storage,tenantId]);
 async function accountPage(page:number){const r=await fetch(`/api/ledger/accounts?${new URLSearchParams({tenantId,companyId,page:String(page)})}`);if(!r.ok)throw new Error("Accounts unavailable");const data=await r.json();setAccounts(old=>page===0?data.accounts:[...old,...data.accounts]);setNext(data.nextPage);}
 async function inspect(){if(working.current)return;working.current=true;setBusy(true);setMessage("");try{const r=await fetch(`${endpoint}?${new URLSearchParams({tenantId})}`);const data=await r.json();if(!r.ok)throw new Error(data.error??"Could not load settlement balance");setState(data);if(canPost)await accountPage(0);}catch(e){setMessage(e instanceof Error?e.message:t("Connection failed","فشل الاتصال"));}finally{working.current=false;setBusy(false);}}
 function remember(p:Payload|null){setPending(p);try{if(p)sessionStorage.setItem(storage,JSON.stringify(p));else sessionStorage.removeItem(storage);}catch{}}
 async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();if(working.current)return;const form=new FormData(event.currentTarget);const payload=pending??{tenantId,requestId:crypto.randomUUID(),kind:String(form.get("kind")) as "COLLECTION"|"REFUND",amount:String(form.get("amount")),entryDate:String(form.get("entryDate")),assetAccountId:String(form.get("assetAccountId")),reference:String(form.get("reference"))};remember(payload);working.current=true;setBusy(true);setMessage("");
  try{const r=await fetch(endpoint,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});const data=await r.json();if(!r.ok){if([400,409].includes(r.status))remember(null);setMessage(data.error??t("Could not save settlement","تعذر حفظ التسوية"));return;}remember(null);formRef.current?.reset();setMessage(t("Settlement and its balanced journal were saved.","تم حفظ التسوية وقيدها المتوازن."));const refreshed=await fetch(`${endpoint}?${new URLSearchParams({tenantId})}`);if(refreshed.ok)setState(await refreshed.json());else setState(null);
  }catch{setMessage(t("Connection failed. Retry the same saved request to check its result without duplicating it.","فشل الاتصال. أعد نفس الطلب المحفوظ للتحقق من نتيجته دون تكراره."));}finally{working.current=false;setBusy(false);}
 }
 const disabled=busy||!!pending;
 return <section className="panel"><h2>{t("Customer collection / refund","تحصيل العميل / رد الدفعة")}</h2><p>{t("Record a collection already received or a refund already paid for this invoice. The original receivable account is used automatically. Choose a separate cash or bank asset account. Refunds are limited to the net amount collected. Corrections use a linked journal reversal.","سجّل تحصيلًا استُلم بالفعل أو مبلغًا رُدّ للعميل لهذه الفاتورة. يُستخدم حساب الذمم الأصلي تلقائيًا. اختر حساب نقد أو بنك منفصلًا. لا يتجاوز الرد صافي المبلغ المحصّل، والتصحيح بقيد عكسي مرتبط.")}</p><button type="button" disabled={busy} onClick={()=>void inspect()}>{t("Check balance / refresh","فحص الرصيد / تحديث")}</button>{message&&<p role="status">{message}</p>}
 {state&&<><p>{t("Outstanding invoice balance","رصيد الفاتورة المتبقي")}: <strong>{state.balance} {state.original?.currency}</strong> · {t("Available collection","المتاح للتحصيل")}: {state.paymentAvailable} · {t("Available refund","المتاح للاسترداد")}: {state.refundAvailable}</p>{state.original&&<p><a href={`/accounting/ledger/journals/${state.original.id}`}>{t("Original invoice journal","قيد الفاتورة الأصلي")}</a>{state.original.reversed?` · ${t("Reversed","معكوس")}`:""}</p>}
 {!state.original||state.original.reversed?<p>{t("Post an active invoice receivable journal before recording a collection.","رحّل قيد الذمم المدينة للفاتورة قبل تسجيل التحصيل.")}</p>:canPost&&!pending&&<form ref={formRef} onSubmit={event=>void submit(event)}><fieldset disabled={disabled}><label>{t("Type","النوع")}<select name="kind" required><option value="COLLECTION">{t("Customer collection","تحصيل من العميل")}</option><option value="REFUND">{t("Refund paid to customer","دفعة مردودة للعميل")}</option></select></label><label>{t("Amount","المبلغ")}<input name="amount" inputMode="decimal" pattern="(?:0|[1-9][0-9]{0,11})(?:\.[0-9]{1,3})?" required/></label><label>{t("Journal date","تاريخ القيد")}<input name="entryDate" type="date" min={state.latest} required/></label><label>{t("Collection / refund reference","مرجع التحصيل / رد الدفعة")}<input name="reference" minLength={3} maxLength={120} required/></label><label>{t("Cash / bank asset account","حساب أصل النقد / البنك")}<select name="assetAccountId" required><option value="">{t("Choose account","اختر الحساب")}</option>{accounts.filter(a=>a.type==="ASSET"&&a.id!==state.receivable?.id).map(a=><option key={a.id} value={a.id}>{a.code} · {a.name}</option>)}</select></label><button>{t("Record settlement and journal","تسجيل التسوية والقيد")}</button></fieldset></form>}
 <h3>{t("Latest 50 settlements; total","آخر 50 تسوية؛ الإجمالي")}: {state.settlementCount}</h3>{state.settlements.map(s=><article className="card" key={s.id}><strong>{s.kind==="COLLECTION"?t("Collection","تحصيل"):t("Refund","رد دفعة")}: {s.amount} {s.entry.currency}</strong><p>{s.reference} · {s.entry.entryDate.slice(0,10)} · <a href={`/accounting/ledger/journals/${s.entry.id}`}>{t("Journal / correction","القيد / التصحيح")}</a>{s.entry.reversal&&<> · <a href={`/accounting/ledger/journals/${s.entry.reversal.id}`}>{t("Reversed","معكوس")}</a></>}</p></article>)}</>}
 {canPost&&pending&&<form onSubmit={event=>void submit(event)}><p>{t("Saved request awaiting confirmation","طلب محفوظ بانتظار التأكيد")}: {pending.kind} · {pending.amount} · {pending.entryDate} · {pending.reference}</p><button disabled={busy}>{t("Retry saved request","إعادة الطلب المحفوظ")}</button></form>}
 {canPost&&next!==null&&<button disabled={busy||!!pending} type="button" onClick={async()=>{if(working.current)return;working.current=true;setBusy(true);try{await accountPage(next);}catch{setMessage(t("Could not load more accounts","تعذر تحميل المزيد من الحسابات"));}finally{working.current=false;setBusy(false);}}}>{t("More accounts","المزيد من الحسابات")}</button>}
 </section>;
}
