"use client";
import {useState} from "react";
import {translate,type Locale} from "@/lib/locale";
type Report={from:string;to:string;summary:{entries:number;totalMinutes:number;employees:{employeeId:string;employeeName:string|null;employeeCode:string|null;minutes:number;entries:number}[]}};
const duration=(minutes:number)=>`${Math.floor(minutes/60)}:${String(minutes%60).padStart(2,"0")}`;
export function TimeReport({projectId,tenantId,locale}:{projectId:string;tenantId:string;locale:Locale}){
 const t=(en:string,ar:string)=>translate(locale,en,ar);const [report,setReport]=useState<Report|null>(null);const [busy,setBusy]=useState(false);const [error,setError]=useState("");
 async function load(form:FormData){setBusy(true);setError("");setReport(null);try{const response=await fetch(`/api/projects/${projectId}/time/report?${new URLSearchParams({tenantId,from:String(form.get("from")),to:String(form.get("to"))})}`);const data=await response.json();if(response.ok)setReport(data);else setError(data.error);}catch{setError(t("Network request failed","فشل الاتصال بالشبكة"));}finally{setBusy(false);}}
 return <section><h2>{t("Project time report","تقرير ساعات المشروع")}</h2><p>{t("Up to 366 days and 5000 entries. Voided entries are excluded. Durations are hours:minutes; this is recorded effort, not payroll.","حتى 366 يوماً و5000 سجل. تُستبعد السجلات الملغاة. المدد ساعات:دقائق، وهي جهد مسجّل وليست حساب رواتب.")}</p><form action={load}><label>{t("From","من")} <input type="date" name="from" required/></label><label>{t("To","إلى")} <input type="date" name="to" required/></label><button disabled={busy}>{t("Show report","عرض التقرير")}</button></form>{error&&<p role="status">{error}</p>}{report&&<><p>{report.from} — {report.to} · {t("Entries","السجلات")}: {report.summary.entries} · {t("Total duration","المدة الإجمالية")}: {duration(report.summary.totalMinutes)}</p><a href={`/api/projects/${projectId}/time/report?${new URLSearchParams({tenantId,from:report.from,to:report.to,format:"csv"})}`}>{t("Download CSV","تنزيل CSV")}</a>{report.summary.employees.map(employee=><article className="card" key={employee.employeeId}><strong>{employee.employeeName??t("Employee details restricted","بيانات الموظف مقيّدة")}</strong> {employee.employeeCode}<p>{duration(employee.minutes)} · {t("Entries","السجلات")}: {employee.entries}</p></article>)}{!report.summary.entries&&<p>{t("No time entries in this period.","لا توجد سجلات وقت في هذه الفترة.")}</p>}</>}</section>;
}
