import {redirect} from "next/navigation";
import {currentUser} from "@/lib/auth";
import {db} from "@/lib/db";
import {readableCompanyPermissions} from "@/lib/access";
import {customerBalances,CustomerBalanceError} from "@/lib/customer-balances";
import {getLocale} from "@/lib/server-locale";
import {translate} from "@/lib/locale";
import {LanguageSwitcher} from "../../language-switcher";
export default async function CustomerBalancesPage({searchParams}:{searchParams:Promise<Record<string,string|string[]|undefined>>}){
 const actor=await currentUser();if(!actor)redirect("/login");
 const locale=await getLocale(),t=(en:string,ar:string)=>translate(locale,en,ar);
 const memberships=await db.membership.findMany({where:{userId:actor.id,status:"ACTIVE"},include:{tenant:{include:{companies:{include:{branches:true},orderBy:{name:"asc"}}}}}});
 const scopes=(await Promise.all(memberships.flatMap(({tenant})=>tenant.companies.map(async company=>{
  const rights=await readableCompanyPermissions({userId:actor.id,tenantId:tenant.id,companyId:company.id,permissions:["customer:read","order:read","invoice:read","ledger:read"]});if(Object.values(rights).some(r=>r===false))return null;
  return {tenantId:tenant.id,companyId:company.id,value:`${tenant.id}:${company.id}`,label:`${tenant.name} / ${company.name}`,branches:company.branches.filter(b=>[rights["invoice:read"],rights["ledger:read"]].every(r=>r===null||(Array.isArray(r)&&r.includes(b.id))))};
 })))).filter(s=>s!==null);
 const query=await searchParams,value=(key:string)=>typeof query[key]==="string"?query[key] as string:"";
 const scope=scopes.find(s=>s.value===value("scope"))??(query.scope?undefined:scopes[0]),asOf=value("asOf")||new Date().toISOString().slice(0,10),q=value("q"),branchId=value("branchId");
 let result:Awaited<ReturnType<typeof customerBalances>>|undefined,error="";
 if(scope)try{if(Object.values(query).some(v=>Array.isArray(v)))throw new CustomerBalanceError("Duplicate filter",400);result=await customerBalances(actor.id,{tenantId:scope.tenantId,companyId:scope.companyId,asOf,q,...(branchId?{branchId}:{})});}catch(e){if(e instanceof CustomerBalanceError)error=e.status===413?t("Too many records. Narrow the customer search or invoice branch.","السجلات تتجاوز الحد المتاح. حدد العميل أو فرع الفاتورة."):t("Invalid or unavailable filters. Reset the report.","الفلاتر غير صالحة أو غير متاحة. أعد ضبط التقرير.");else throw e;}
 const csv=scope&&result?`/api/accounting/customer-balances?${new URLSearchParams({tenantId:scope.tenantId,companyId:scope.companyId,asOf:result.asOf,q:result.q,format:"csv",...(branchId?{branchId}:{})})}`:"";
 return <main><style>{`.customer-balances-table{width:100%;border-collapse:collapse}.customer-balances-table th,.customer-balances-table td{padding:12px;text-align:start;border-bottom:1px solid #ddd}@media print{header,form,.balance-controls{display:none}.hero{padding:20px 0!important}.hero h1{font-size:28px!important}.panel{break-inside:auto}}`}</style>
 <header><strong>FINAL <span>ARROW</span> ERP</strong><LanguageSwitcher locale={locale}/><a href="/accounting/customer-statement">{t("Customer statement","كشف حساب العميل")}</a><a href="/crm">{t("Customers","العملاء")}</a><a href="/accounting/collections">{t("Customer collections", "تحصيلات العملاء")}</a><a href="/workspace">{t("Workspace","مساحة العمل")}</a></header>
 <section className="hero"><p>{t("ACCOUNTING / CUSTOMERS","المحاسبة / العملاء")}</p><h1>{t("Posted customer balances.","أرصدة العملاء المرحلة.")}</h1><p className="sub">{t("Posted invoices, collections, refunds and corrections as of a selected journal date.","إجمالي الفواتير المرحلة والتحصيلات وردّ الدفعات والقيود العكسية حتى تاريخ القيد المختار.")}</p></section>
 <section className="panel"><p>{t("These balances cover posted source journals only. Tax, freight and unrelated manual journals are excluded. Currencies remain separate; positive balances are debit minus credit. Zero balances and archived customers remain visible when they have posted history. This is not a confirmed customer balance or an overdue-payment report.","الأرصدة تشمل قيود المستندات المرحلة فقط، وتستبعد الضرائب والشحن والقيود اليدوية الأخرى. العملات منفصلة والرصيد الموجب يساوي المدين ناقص الدائن. يظهر العميل المؤرشف والرصيد الصفري إذا كانت لهما قيود سابقة. هذا ليس تأكيدًا لرصيد العميل أو تقريرًا للدفعات المتأخرة.")}</p>
 {!scopes.length?<p>{t("No accessible customer balances.","لا توجد أرصدة عملاء متاحة بالصلاحيات الحالية.")}</p>:<><form method="get"><label>{t("Company","الشركة")}<select name="scope" defaultValue={scope?.value??""}>{scopes.map(s=><option key={s.value} value={s.value}>{s.label}</option>)}</select></label><button>{t("Select company","اختيار الشركة")}</button></form>
 {scope&&<form method="get"><input type="hidden" name="scope" value={scope.value}/><label>{t("As of (UTC)","حتى تاريخ (UTC)")}<input type="date" name="asOf" defaultValue={asOf} required/></label><label>{t("Customer name or code","اسم العميل أو رمزه")}<input name="q" maxLength={120} defaultValue={q}/></label><label>{t("Invoice branch","فرع الفاتورة")}<select name="branchId" defaultValue={branchId}><option value="">{t("All accessible branches","كل الفروع المتاحة")}</option>{scope.branches.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></label><button>{t("Show balances","عرض الأرصدة")}</button><a href="/accounting/customer-balances">{t("Reset","إعادة ضبط")}</a></form>}
 {!scope&&<p role="alert">{t("Choose an accessible company.","اختر شركة متاحة.")}</p>}{error&&<p role="alert">{error}</p>}
 {result&&<><p>{result.asOf}</p><p className="balance-controls"><a href={csv}>{t("Download CSV","تنزيل CSV")}</a> · {t("Use browser Print to print or save PDF.","استخدم طباعة المتصفح للطباعة أو حفظ PDF.")}</p>{result.summary.map(g=><article className="card" key={g.currency}><strong>{g.currency}</strong><p>{t("Customers","العملاء")}: {g.customers} · {t("Positive balances","الأرصدة الموجبة")}: {g.positive} · {t("Negative balances","الأرصدة السالبة")}: {g.negative} · {t("Net balance","صافي الرصيد")}: {g.balance}</p></article>)}
 <div style={{overflowX:"auto"}}><table className="customer-balances-table"><thead><tr>{[t("Code","الرمز"),t("Customer","العميل"),t("Journals","القيود"),t("Corrections","القيود العكسية"),t("Balance","الرصيد"),t("Currency","العملة"),t("Statement","الكشف")].map(label=><th key={label}>{label}</th>)}</tr></thead><tbody>{result.rows.map(r=><tr key={r.customer.id+":"+r.currency}><td>{r.customer.code}</td><td>{r.customer.displayName}{r.customer.archivedAt?` · ${t("Archived","مؤرشف")}`:""}</td><td>{r.journals}</td><td>{r.corrections}</td><td>{r.balance}</td><td>{r.currency}</td><td><a href={`/accounting/customer-statement?${new URLSearchParams({scope:scope!.value,customerId:r.customer.id,from:result.asOf,to:result.asOf,...(branchId?{branchId}:{})})}`}>{t("View statement","عرض الكشف")}</a></td></tr>)}</tbody></table></div>{!result.rows.length&&<p>{t("No posted customer history matches these filters.","لا توجد قيود عملاء مرحلة تطابق هذه الفلاتر.")}</p>}</>}
 </>}</section></main>;
}
