"use client";
import {useCallback,useEffect,useRef,useState,type FormEvent} from "react";
import {translate,type Locale} from "@/lib/locale";
import {permissionGroup,permissionLabel,requiredReads,roleDisplay} from "@/lib/permission-labels";
type Role={id:string;name:string;permissions:string[];protected:boolean;assignable:boolean;revision:string;members:number;invitations:number};
type Scope={type:"TENANT"|"COMPANY"|"BRANCH";companyId?:string|null;branchId?:string|null};
type Member={id:string;userId:string;name:string;email:string;status:string;revision:string;grants:{roleId:string;role:string;scopes:Scope[]}[]};
type Company={id:string;name:string;branches:{id:string;name:string}[]};
type Submit=(path:string,method:string,body:unknown)=>Promise<boolean>;
export function RolesPanel({tenantId,currentUserId,companies,locale}:{tenantId:string;currentUserId:string;companies:Company[];locale:Locale}){
 const t=useCallback((en:string,ar:string)=>translate(locale,en,ar),[locale]);
 const [roles,setRoles]=useState<Role[]>([]),[permissions,setPermissions]=useState<string[]>([]),[members,setMembers]=useState<Member[]>([]),[selected,setSelected]=useState(""),[busy,setBusy]=useState(false),[message,setMessage]=useState(""),[loaded,setLoaded]=useState(false);
 const working=useRef(false),sequence=useRef(0);
 const load=useCallback(async(signal?:AbortSignal)=>{const stamp=++sequence.current;const results=await Promise.all([fetch(`/api/roles?tenantId=${tenantId}`,{signal}),fetch(`/api/team?tenantId=${tenantId}`,{signal})]);if(results.some(r=>!r.ok))throw new Error(t("Could not load access settings.","تعذر تحميل إعدادات الوصول."));const [catalog,team]=await Promise.all(results.map(r=>r.json()));if(stamp!==sequence.current||signal?.aborted)return;setRoles(catalog.roles);setPermissions(catalog.permissions);setMembers(team.members);setLoaded(true);},[tenantId,t]);
 useEffect(()=>{const controller=new AbortController();void load(controller.signal).catch(e=>{if(!controller.signal.aborted)setMessage(e instanceof Error?e.message:t("Connection failed","فشل الاتصال"));});return()=>{controller.abort();sequence.current++;};},[load,t]);
 async function submit(path:string,method:string,body:unknown){if(working.current)return false;working.current=true;setBusy(true);setMessage("");try{const r=await fetch(path,{method,headers:{"Content-Type":"application/json"},body:JSON.stringify(body)}),data=await r.json();if(!r.ok){setMessage(data.error??t("Could not save changes.","تعذر حفظ التغييرات."));if(r.status===409)await load();return false;}await load();setMessage(t("Access settings saved.","تم حفظ إعدادات الوصول."));return true;}catch{setMessage(t("Connection failed. Refresh to check whether the change was saved before trying again.","فشل الاتصال. حدّث الصفحة للتحقق من حفظ التغيير قبل المحاولة مجددًا."));return false;}finally{working.current=false;setBusy(false);}}
 const role=roles.find(r=>r.id===selected);
 return <><style>{`.permission-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:16px}.permission-grid fieldset{padding:16px;border:1px solid #ddd;border-radius:12px}.permission-grid label{display:flex;align-items:center;flex-direction:row;gap:8px;margin:8px 0}.permission-grid input{width:auto;margin:0}.role-editor-fields{border:0;padding:0;margin:0}.role-members{display:grid;gap:16px}.role-member{padding:20px;border:1px solid #ddd;border-radius:12px}.role-scope{display:flex;flex-wrap:wrap;gap:12px;align-items:end}.role-scope label{min-width:160px}.role-scope select{width:100%}`}</style>
 <section className="panel"><button type="button" disabled={busy} onClick={async()=>{if(working.current)return;working.current=true;setBusy(true);try{await load();setMessage(t("Settings refreshed.","تم تحديث الإعدادات."));}catch{setMessage(t("Could not refresh.","تعذر التحديث."));}finally{working.current=false;setBusy(false);}}}>{t("Refresh settings","تحديث الإعدادات")}</button>{message&&<p role="status">{message}</p>}{!loaded&&<p>{t("Loading access settings…","جارٍ تحميل إعدادات الوصول…")}</p>}</section>
 {loaded&&<><section className="panel"><h2>{t("Role editor","محرّر الأدوار")}</h2><label>{t("Role","الدور")}<select value={selected} disabled={busy} onChange={e=>setSelected(e.target.value)}><option value="">{t("New custom role","دور مخصّص جديد")}</option>{roles.map(r=><option key={r.id} value={r.id}>{roleDisplay(r.name,locale)}{r.protected?` · ${t("Built-in","أساسي")}`:""}</option>)}</select></label>
 <RoleEditor key={role?`${role.id}:${role.revision}`:"new"} role={role} roles={roles} available={permissions} tenantId={tenantId} locale={locale} busy={busy} submit={submit}/></section>
 <section className="panel"><h2>{t("Member role assignments","إسناد أدوار الأعضاء")}</h2><p>{t("Saving replaces this member's existing roles and scopes. Pending invitations for that member are revoked to prevent restoring older access. Suspended accounts stay suspended.","الحفظ يستبدل أدوار العضو ونطاقاته الحالية. تُلغى دعواته المعلّقة لمنع استعادة صلاحيات أقدم. الحساب المعلّق يبقى معلّقًا.")}</p><div className="role-members">{members.map(m=><article className="role-member" key={m.id}><h3>{m.name}</h3><p>{m.email} · {m.status==="ACTIVE"?t("Active","نشط"):t("Suspended","معلّق")}</p>{m.userId===currentUserId||m.grants.some(g=>g.role==="Owner")?<p>{t("Protected owner access","صلاحيات المالك محمية")}</p>:<MemberEditor key={m.revision} member={m} roles={roles.filter(r=>r.assignable)} companies={companies} tenantId={tenantId} busy={busy} locale={locale} submit={submit}/>}</article>)}</div></section></>}
 </>;
}
function RoleEditor({role,roles,available,tenantId,locale,busy,submit}:{role?:Role;roles:Role[];available:string[];tenantId:string;locale:Locale;busy:boolean;submit:Submit}){
 const t=(en:string,ar:string)=>translate(locale,en,ar),[name,setName]=useState(role?.name??""),[keys,setKeys]=useState(role?.permissions??[]);
 const groups=[...new Set(available.map(k=>k.split(":")[0]))];
 function toggle(key:string,on:boolean){setKeys(old=>{const next=new Set(old);if(on){next.add(key);for(const read of requiredReads(key,available)){next.add(read);for(const linked of requiredReads(read,available))next.add(linked);}}else{next.delete(key);for(const k of old)if(requiredReads(k,available).includes(key))next.delete(k);}return [...next];});}
 async function save(e:FormEvent){e.preventDefault();const ok=await submit(role?`/api/roles/${role.id}`:"/api/roles",role?"PATCH":"POST",{tenantId,name,permissions:keys,...(role?{expectedRevision:role.revision}:{})});if(ok&&!role){setName("");setKeys([]);}}
 return <form onSubmit={e=>void save(e)}><fieldset className="role-editor-fields" disabled={busy||role?.protected}><label>{t("Role name","اسم الدور")}<input value={name} onChange={e=>setName(e.target.value)} minLength={2} maxLength={80} required/></label>{!role&&<label>{t("Start from a template","البدء من قالب")}<select defaultValue="" onChange={e=>{const template=roles.find(r=>r.id===e.target.value);setKeys(template?.permissions.filter(k=>available.includes(k))??[]);}}><option value="">{t("No permissions","بدون صلاحيات")}</option>{roles.filter(r=>r.name!=="Owner").map(r=><option key={r.id} value={r.id}>{roleDisplay(r.name,locale)}</option>)}</select></label>}
 {role&&<p>{t("Assignments","الإسنادات")}: {role.members} · {t("Historical invitations","الدعوات المسجلة")}: {role.invitations}</p>}{role?.protected&&<p>{t("Built-in role: view only. Create a custom role to use different permissions.","دور أساسي للعرض فقط. أنشئ دورًا مخصّصًا لاستخدام صلاحيات مختلفة.")}</p>}<p>{t("Action permissions include the required module view permissions. Save no permissions to remove this role's operational access.","صلاحيات الإجراءات تتضمن صلاحيات العرض المطلوبة. احفظ دون صلاحيات لإيقاف وصول هذا الدور إلى وحدات العمل.")}</p><div className="permission-grid">{groups.map(group=><fieldset key={group}><legend>{permissionGroup(group,locale)}</legend>{available.filter(k=>k.startsWith(group+":")).map(k=><label key={k}><input type="checkbox" checked={keys.includes(k)} onChange={e=>toggle(k,e.target.checked)}/>{permissionLabel(k,locale)}</label>)}</fieldset>)}</div>{!role?.protected&&<button>{t("Save role permissions","حفظ صلاحيات الدور")}</button>}</fieldset></form>;
}
function MemberEditor({member,roles,companies,tenantId,busy,locale,submit}:{member:Member;roles:Role[];companies:Company[];tenantId:string;busy:boolean;locale:Locale;submit:Submit}){
 const t=(en:string,ar:string)=>translate(locale,en,ar),[grants,setGrants]=useState(()=>member.grants.flatMap(g=>g.scopes.map(scope=>({roleId:g.roleId,scope}))));
 const update=(index:number,next:{roleId:string;scope:Scope})=>setGrants(old=>old.map((g,i)=>i===index?next:g));
 async function save(e:FormEvent){e.preventDefault();await submit(`/api/team/${member.id}/grants`,"PATCH",{tenantId,expectedRevision:member.revision,grants:grants.map(g=>({roleId:g.roleId,scope:g.scope.type==="TENANT"?{type:"TENANT"}:g.scope.type==="COMPANY"?{type:"COMPANY",companyId:g.scope.companyId}:{type:"BRANCH",companyId:g.scope.companyId,branchId:g.scope.branchId}}))});}
 return <form onSubmit={e=>void save(e)}><fieldset disabled={busy}>{grants.map((g,i)=><div className="role-scope" key={i}><label>{t("Role","الدور")}<select required value={g.roleId} onChange={e=>update(i,{...g,roleId:e.target.value})}><option value="">{t("Choose role","اختر الدور")}</option>{roles.map(r=><option key={r.id} value={r.id}>{roleDisplay(r.name,locale)}</option>)}</select></label><label>{t("Scope","النطاق")}<select value={g.scope.type} onChange={e=>update(i,{...g,scope:{type:e.target.value as Scope["type"]}})}><option value="TENANT">{t("Organization","المؤسسة")}</option><option value="COMPANY">{t("Company","الشركة")}</option><option value="BRANCH">{t("Branch","الفرع")}</option></select></label>{g.scope.type!=="TENANT"&&<label>{t("Company","الشركة")}<select required value={g.scope.companyId??""} onChange={e=>update(i,{...g,scope:{type:g.scope.type,companyId:e.target.value}})}><option value="">{t("Choose company","اختر الشركة")}</option>{companies.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label>}{g.scope.type==="BRANCH"&&<label>{t("Branch","الفرع")}<select required value={g.scope.branchId??""} onChange={e=>update(i,{...g,scope:{...g.scope,branchId:e.target.value}})}><option value="">{t("Choose branch","اختر الفرع")}</option>{companies.find(c=>c.id===g.scope.companyId)?.branches.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></label>}{grants.length>1&&<button type="button" onClick={()=>setGrants(old=>old.filter((_,index)=>index!==i))}>{t("Remove assignment","إزالة الإسناد")}</button>}</div>)}{grants.length<10&&<button type="button" onClick={()=>setGrants(old=>[...old,{roleId:"",scope:{type:"TENANT"}}])}>{t("Add role / scope","إضافة دور / نطاق")}</button>}<button>{t("Replace member access","حفظ واستبدال صلاحيات العضو")}</button></fieldset></form>;
}
