"use client";
import {useState} from "react";
import {translate,type Locale} from "@/lib/locale";
type Result={from:string;to:string;timeZone:string;item:{sku:string;name:string;unit:string;archivedAt:string|null};summary:{opening:string;incoming:string;outgoing:string;closing:string;count:number};rows:{id:string;timestamp:string;type:string;delta:string;balance:string;reason:string}[]};
export function StockReport({scope,items,locale}:{scope:{tenantId:string;companyId:string;branchId:string};items:{id:string;sku:string;name:string}[];locale:Locale}){
 const t=(en:string,ar:string)=>translate(locale,en,ar);const [result,setResult]=useState<Result|null>(null);const [query,setQuery]=useState("");const [limit,setLimit]=useState(100);const [busy,setBusy]=useState(false);const [error,setError]=useState("");
 async function load(form:FormData){if(busy)return;setBusy(true);setError("");setResult(null);setQuery("");setLimit(100);const params=new URLSearchParams({...scope,itemId:String(form.get("itemId")),from:String(form.get("from")),to:String(form.get("to")),timeZone:String(form.get("timeZone"))});try{const response=await fetch(`/api/inventory/stock/report?${params}`);const data=await response.json();if(response.ok){setResult(data);setQuery(params.toString());}else setError(data.error);}catch{setError(t("Network request failed","فشل الاتصال بالشبكة"));}finally{setBusy(false);}}
 const types:Record<string,string>={ADJUSTMENT_IN:"إضافة يدوية",ADJUSTMENT_OUT:"سحب يدوي",PURCHASE_RECEIPT:"استلام مشتريات"};
 return <section className="panel"><h2>{t("Stock movement report","تقرير حركة المخزون")}</h2><p>{t("Select one item and a date range up to 366 days. Opening includes earlier movements; closing includes movements through the selected end date. Quantities are not monetary valuations.","اختر صنفاً وفترة حتى 366 يوماً. يشمل رصيد البداية الحركات السابقة، ورصيد النهاية الحركات حتى نهاية اليوم المختار. الكميات ليست تقييماً مالياً.")}</p><form action={load}><label>{t("Item","الصنف")} <select name="itemId" required defaultValue=""><option value="">{t("Choose item","اختر صنفاً")}</option>{items.map(item=><option value={item.id} key={item.id}>{item.sku} · {item.name}</option>)}</select></label><label>{t("From","من")} <input name="from" type="date" required/></label><label>{t("To","إلى")} <input name="to" type="date" required/></label><label>{t("Time zone","التوقيت")} <select name="timeZone" defaultValue="Asia/Muscat"><option value="Asia/Muscat">{t("Muscat (UTC+4)","مسقط (UTC+4)")}</option><option value="UTC">UTC</option></select></label><button disabled={busy||!items.length}>{t("Show report","عرض التقرير")}</button></form>{error&&<p role="status">{error}</p>}{result&&<><h3>{result.item.sku} · {result.item.name}{result.item.archivedAt?t(" · archived"," · مؤرشف"):""}</h3><p>{result.from} — {result.to} · {result.timeZone} · {result.summary.count} {t("movements","حركة")}</p><div className="cards">{(["opening","incoming","outgoing","closing"] as const).map(key=><article className="card" key={key}><strong>{t({opening:"Opening",incoming:"Incoming",outgoing:"Outgoing",closing:"Closing"}[key],{opening:"رصيد البداية",incoming:"الوارد",outgoing:"الصادر",closing:"رصيد النهاية"}[key])}</strong><p>{result.summary[key]} {result.item.unit}</p></article>)}</div><a href={`/api/inventory/stock/report?${query}&format=csv`}>{t("Download CSV","تنزيل CSV")}</a><table><thead><tr><th>{t("Time","الوقت")}</th><th>{t("Type","النوع")}</th><th>{t("Change","التغير")}</th><th>{t("Running balance","الرصيد المتراكم")}</th><th>{t("Reason","السبب")}</th></tr></thead><tbody>{result.rows.slice(0,limit).map(row=><tr key={row.id}><td>{row.timestamp}</td><td>{t(row.type,types[row.type]??row.type)}</td><td>{row.delta}</td><td>{row.balance}</td><td>{row.reason}</td></tr>)}</tbody></table>{limit<result.rows.length&&<button onClick={()=>setLimit(value=>value+100)}>{t("Show 100 more movements","عرض 100 حركة إضافية")}</button>}{!result.rows.length&&<p>{t("No movements in this period; balances may carry forward.","لا توجد حركات في الفترة؛ قد يبقى رصيد مرحّل من قبلها.")}</p>}</>}</section>;
}
