"use client";
import {useEffect,useRef,useState,type FormEvent} from "react";
import {translate,type Locale} from "@/lib/locale";
type Account={id:string;code:string;name:string;type:string};
type State={original:{id:string;number:string;currency:string;reversed:boolean}|null;balance:string;paymentAvailable:string;refundAvailable:string;latest:string;settlementCount:number;settlements:{id:string;kind:string;amount:string;reference:string;entry:{id:string;number:string;entryDate:string;currency:string;reversal:{id:string;number:string}|null}}[]};
type Payload={tenantId:string;requestId:string;kind:"PAYMENT"|"REFUND";amount:string;entryDate:string;assetAccountId:string;reference:string};
export function SettlementForm({tenantId,companyId,receiptId,locale,canPost}:{tenantId:string;companyId:string;receiptId:string;locale:Locale;canPost:boolean}){
 const t=(en:string,ar:string)=>translate(locale,en,ar),endpoint=`/api/purchasing/receipts/${receiptId}/settlements`,storage=`erp-settlement:${tenantId}:${receiptId}`;
 const [state,setState]=useState<State|null>(null),[accounts,setAccounts]=useState<Account[]>([]),[next,setNext]=useState<number|null>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState(""),[pending,setPending]=useState<Payload|null>(null);
 const working=useRef(false),formRef=useRef<HTMLFormElement>(null);
 useEffect(()=>{try{const value=sessionStorage.getItem(storage);if(value){const p=JSON.parse(value);if(p.tenantId===tenantId&&typeof p.requestId==="string"&&["PAYMENT","REFUND"].includes(p.kind)&&[p.amount,p.entryDate,p.assetAccountId,p.reference].every(v=>typeof v==="string"))setPending(p);}}catch{}},[storage,tenantId]);
 async function accountPage(page:number){const r=await fetch(`/api/ledger/accounts?${new URLSearchParams({tenantId,companyId,page:String(page)})}`);if(!r.ok)throw new Error("Accounts unavailable");const data=await r.json();setAccounts(old=>page===0?data.accounts:[...old,...data.accounts]);setNext(data.nextPage);}
 async function inspect(){if(working.current)return;working.current=true;setBusy(true);setMessage("");try{const r=await fetch(`${endpoint}?${new URLSearchParams({tenantId})}`);const data=await r.json();if(!r.ok)throw new Error(data.error??"Could not load settlement balance");setState(data);if(canPost)await accountPage(0);}catch(e){setMessage(e instanceof Error?e.message:t("Connection failed","فشل الاتصال"));}finally{working.current=false;setBusy(false);}}
 function remember(p:Payload|null){setPending(p);try{if(p)sessionStorage.setItem(storage,JSON.stringify(p));else sessionStorage.removeItem(storage);}catch{}}
 async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();if(working.current)return;const form=new FormData(event.currentTarget);const payload=pending??{tenantId,requestId:crypto.randomUUID(),kind:String(form.get("kind")) as "PAYMENT"|"REFUND",amount:String(form.get("amount")),entryDate:String(form.get("entryDate")),assetAccountId:String(form.get("assetAccountId")),reference:String(form.get("reference"))};remember(payload);working.current=true;setBusy(true);setMessage("");
  try{const r=await fetch(endpoint,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});const data=await r.json();if(!r.ok){if([400,409].includes(r.status))remember(null);setMessage(data.error??t("Could not save settlement","تعذر حفظ التسوية"));return;}remember(null);formRef.current?.reset();setMessage(t("Settlement and its balanced journal were saved.","تم حفظ التسوية وقيدها المتوازن."));const refreshed=await fetch(`${endpoint}?${new URLSearchParams({tenantId})}`);if(refreshed.ok)setState(await refreshed.json());else setState(null);
  }catch{setMessage(t("Connection failed. Retry the same saved request to check its result without duplicating it.","فشل الاتصال. أعد نفس الطلب المحفوظ للتحقق من نتيجته دون تكراره."));}finally{working.current=false;setBusy(false);}
 }
 const disabled=busy||!!pending;
 return <section className="panel"><h2>{t("Supplier payment / refund","دفعة المورد / الاسترداد")}</h2><p>{t("Record an actual payment or refund against this receipt. Use its original payable account and choose the cash/bank asset used. This does not transfer money. Corrections use a linked journal reversal; saved records remain unchanged.","سجّل دفعة أو استردادًا تم بالفعل لهذا الاستلام. يُستخدم حساب المستحق الأصلي، واختر حساب النقد أو البنك المستخدم. لا يحوّل هذا الإجراء أموالًا. التصحيح بقيد عكسي مرتبط ويبقى السجل محفوظًا.")}</p><button type="button" disabled={busy} onClick={()=>void inspect()}>{t("Check balance / refresh","فحص الرصيد / تحديث")}</button>{message&&<p role="status">{message}</p>}
 {state&&<><p>{t("Balance (credit minus debit)","الرصيد (الدائن ناقص المدين)")}: <strong>{state.balance} {state.original?.currency}</strong> · {t("Available payment","المتاح للسداد")}: {state.paymentAvailable} · {t("Available refund","المتاح للاسترداد")}: {state.refundAvailable}</p>{state.original&&<p><a href={`/accounting/ledger/journals/${state.original.id}`}>{t("Original receipt journal","قيد الاستلام الأصلي")}</a>{state.original.reversed?` · ${t("Reversed","معكوس")}`:""}</p>}
 {!state.original||state.original.reversed?<p>{t("Post an active receipt journal before recording a settlement.","رحّل قيد استلام سارٍ قبل تسجيل التسوية.")}</p>:canPost&&!pending&&<form ref={formRef} onSubmit={event=>void submit(event)}><fieldset disabled={disabled}><label>{t("Type","النوع")}<select name="kind" required><option value="PAYMENT">{t("Supplier payment","دفعة للمورد")}</option><option value="REFUND">{t("Refund received","استرداد مستلم")}</option></select></label><label>{t("Amount","المبلغ")}<input name="amount" inputMode="decimal" pattern="(?:0|[1-9][0-9]{0,11})(?:\.[0-9]{1,3})?" required/></label><label>{t("Journal date","تاريخ القيد")}<input name="entryDate" type="date" min={state.latest} required/></label><label>{t("Payment / refund reference","مرجع الدفعة / الاسترداد")}<input name="reference" minLength={3} maxLength={120} required/></label><label>{t("Cash / bank asset account","حساب أصل النقد / البنك")}<select name="assetAccountId" required><option value="">{t("Choose account","اختر الحساب")}</option>{accounts.filter(a=>a.type==="ASSET").map(a=><option key={a.id} value={a.id}>{a.code} · {a.name}</option>)}</select></label><button>{t("Record settlement and journal","تسجيل التسوية والقيد")}</button></fieldset></form>}
 <h3>{t("Latest 50 settlements; total","آخر 50 تسوية؛ الإجمالي")}: {state.settlementCount}</h3>{state.settlements.map(s=><article className="card" key={s.id}><strong>{s.kind==="PAYMENT"?t("Payment","دفعة"):t("Refund","استرداد")}: {s.amount} {s.entry.currency}</strong><p>{s.reference} · {s.entry.entryDate.slice(0,10)} · <a href={`/accounting/ledger/journals/${s.entry.id}`}>{t("Journal / correction","القيد / التصحيح")}</a>{s.entry.reversal&&<> · <a href={`/accounting/ledger/journals/${s.entry.reversal.id}`}>{t("Reversed","معكوس")}</a></>}</p></article>)}</>}
 {canPost&&pending&&<form onSubmit={event=>void submit(event)}><p>{t("Saved request awaiting confirmation","طلب محفوظ بانتظار التأكيد")}: {pending.kind} · {pending.amount} · {pending.entryDate} · {pending.reference}</p><button disabled={busy}>{t("Retry saved request","إعادة الطلب المحفوظ")}</button></form>}
 {canPost&&next!==null&&<button disabled={busy||!!pending} type="button" onClick={async()=>{if(working.current)return;working.current=true;setBusy(true);try{await accountPage(next);}catch{setMessage(t("Could not load more accounts","تعذر تحميل المزيد من الحسابات"));}finally{working.current=false;setBusy(false);}}}>{t("More accounts","المزيد من الحسابات")}</button>}
 </section>;
}
