"use client";
import {useEffect,useRef,useState,type FormEvent} from "react";
import {translate,type Locale} from "@/lib/locale";
type Entry={id:string;number:string;entryDate:string;description?:string};
type Data={statement:{voidedAt:string|null;voidReason:string|null;reference:string;from:string;to:string;opening:string;closing:string;currency:string;account:{code:string;name:string};lines:{id:string;bookingDate:string;reference:string;amount:string;matches:{id:string;journalLine:{id:string;entry:Entry}}[]}[]};bookClosing:string;outstandingTotal:string;adjustedBank:string;difference:string;pendingBank:number;reconciled:boolean;outstanding:{id:string;amount:string;entry:Entry}[]};
type Action={tenantId:string;action:"void";reason:string}|{tenantId:string;action:"match";requestId:string;bankLineId:string;journalLineId:string}|{tenantId:string;action:"cancel";matchId:string;reason:string};
export function ReconciliationPanel({tenantId,id,initial,locale,canPost}:{tenantId:string;id:string;initial:Data;locale:Locale;canPost:boolean}){
 const t=(en:string,ar:string)=>translate(locale,en,ar),[state,setState]=useState(initial),[busy,setBusy]=useState(false),[message,setMessage]=useState(""),[selected,setSelected]=useState(""),[pending,setPending]=useState<Action|null>(null),[page,setPage]=useState(0),working=useRef(false),storage=`erp-bank-match:${tenantId}:${id}`,endpoint=`/api/bank/statements/${id}`;
 useEffect(()=>{try{const raw=sessionStorage.getItem(storage);if(raw){const p=JSON.parse(raw);if(p.tenantId===tenantId&&["match","cancel","void"].includes(p.action))setPending(p);}}catch{}},[storage,tenantId]);
 function remember(p:Action|null){setPending(p);try{if(p)sessionStorage.setItem(storage,JSON.stringify(p));else sessionStorage.removeItem(storage);}catch{}}
 async function reload(){const r=await fetch(`${endpoint}?${new URLSearchParams({tenantId})}`),d=await r.json();if(!r.ok)throw new Error(d.error);setState(d);setPage(0);}
 async function mutate(p:Action){if(working.current)return;working.current=true;setBusy(true);setMessage("");remember(p);let confirmed=false;
  try{const r=await fetch(`${endpoint}/${p.action==="void"?"void":"matches"}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(p)}),d=await r.json();if(!r.ok){if([400,404,409].includes(r.status))remember(null);setMessage(d.error);return;}confirmed=true;remember(null);setSelected("");await reload();setMessage(t("Match action saved and balances refreshed.","حُفظ إجراء المطابقة وحُدّثت الأرصدة."));}catch{setMessage(confirmed?t("Action saved. Refresh to load the latest balances.","حُفظ الإجراء. حدّث الصفحة لتحميل الأرصدة الحالية."):t("Connection failed. Retry the saved action to confirm its result without duplicating it.","فشل الاتصال. أعد الإجراء المحفوظ للتأكد من نتيجته دون تكراره."));}finally{working.current=false;setBusy(false);}
 }
 function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);void mutate({tenantId,action:"match",requestId:crypto.randomUUID(),bankLineId:selected,journalLineId:String(f.get("journalLineId"))});}
 const bank=state.statement.lines.find(l=>l.id===selected),candidates=bank?state.outstanding.filter(l=>l.amount===bank.amount):[];
 return <section><section className="panel"><h2>{state.statement.reference}</h2>{state.statement.voidedAt&&<p><strong>{t("Voided statement; retained for audit","كشف ملغى محفوظ للتدقيق")}</strong> · {state.statement.voidReason}</p>}<p>{state.statement.account.code} · {state.statement.account.name} · {state.statement.from.slice(0,10)} — {state.statement.to.slice(0,10)} · {state.statement.currency}</p><p>{t("Positive = incoming; negative = outgoing. Match one bank movement to one book line with the exact amount and direction. Record bank fees or missing movements as balanced journals before matching them.","الموجب وارد والسالب صادر. طابق حركة البنك بسطر محاسبي واحد بنفس المبلغ والاتجاه. سجّل رسوم البنك أو الحركات الناقصة بقيود متوازنة قبل مطابقتها.")}</p><p>{t("This is a live review of imported statements, not a frozen period close. Earlier outstanding book movements and unmatched imported bank movements are included. Corrections and new journals refresh the result.","هذه مراجعة مباشرة للكشوف المستوردة وليست إقفالًا نهائيًا للفترة. تشمل الحركات المحاسبية السابقة المعلّقة وحركات البنك المستوردة غير المطابقة. التصحيحات والقيود الجديدة تحدّث النتيجة.")}</p>
 <div className="customer-list">{[[t("Statement opening","رصيد بداية الكشف"),state.statement.opening],[t("Statement closing","رصيد نهاية الكشف"),state.statement.closing],[t("Book closing","رصيد الدفاتر"),state.bookClosing],[t("Outstanding book movements","صافي الحركات المحاسبية المعلّقة"),state.outstandingTotal],[t("Adjusted bank balance","رصيد البنك المعدّل"),state.adjustedBank],[t("Difference","الفرق"),state.difference]].map(([label,value])=><article key={label}><strong>{label}</strong><p>{value} {state.statement.currency}</p></article>)}</div><p><strong>{state.reconciled?t("Balanced with all imported bank movements matched","الرصيد متوازن وجميع حركات البنك المستوردة مطابقة"):t("Review incomplete","المراجعة غير مكتملة")}</strong> · {t("Unmatched imported bank movements through this date","حركات البنك المستوردة غير المطابقة حتى هذا التاريخ")}: {state.pendingBank}</p><button disabled={busy} onClick={async()=>{if(working.current)return;working.current=true;setBusy(true);try{await reload();setMessage("");}catch{setMessage(t("Could not refresh","تعذر التحديث"));}finally{working.current=false;setBusy(false);}}}>{t("Refresh balances","تحديث الأرصدة")}</button></section>
 {message&&<p role="status">{message}</p>}{pending&&canPost&&<section className="panel"><p>{t("Saved action awaiting confirmation","إجراء محفوظ بانتظار التأكيد")}: {pending.action}</p><button disabled={busy} onClick={()=>void mutate(pending)}>{t("Retry saved action","إعادة الإجراء المحفوظ")}</button></section>}
 {canPost&&!pending&&!state.statement.voidedAt&&<section className="panel"><h2>{t("Match a bank movement","مطابقة حركة بنكية")}</h2><form onSubmit={submit}><fieldset disabled={busy}><label>{t("Unmatched bank movement","حركة البنك غير المطابقة")}<select required value={selected} onChange={e=>setSelected(e.target.value)}><option value="">{t("Choose bank movement","اختر حركة البنك")}</option>{state.statement.lines.filter(l=>!l.matches.length).map(l=><option key={l.id} value={l.id}>{l.bookingDate.slice(0,10)} · {l.reference} · {l.amount}</option>)}</select></label><label>{t("Same-amount outstanding book movement","حركة محاسبية معلّقة بنفس المبلغ")}<select key={selected} name="journalLineId" required defaultValue=""><option value="">{t("Choose book movement","اختر حركة الدفاتر")}</option>{candidates.map(l=><option key={l.id} value={l.id}>{l.entry.entryDate.slice(0,10)} · {l.entry.number} · {l.entry.description} · {l.amount}</option>)}</select></label>{selected&&!candidates.length&&<p>{t("No equal outstanding book movement. Check the ledger and record any legitimate missing movement.","لا توجد حركة معلّقة بنفس المبلغ. راجع الدفاتر وسجّل أي حركة فعلية ناقصة.")}</p>}<button disabled={!candidates.length}>{t("Save match","حفظ المطابقة")}</button></fieldset></form></section>}
 <section className="panel"><h2>{t("Bank movements","حركات البنك")}: {state.statement.lines.length}</h2>{state.statement.lines.map(l=><article className="card" key={l.id}><strong>{l.reference} · {l.amount} {state.statement.currency}</strong><p>{l.bookingDate.slice(0,10)} · {l.matches.length?t("Matched","مطابقة"):t("Unmatched","غير مطابقة")}</p>{l.matches.map(m=><div key={m.id}><a href={`/accounting/ledger/journals/${m.journalLine.entry.id}`}>{m.journalLine.entry.number}</a>{canPost&&!pending&&<form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void mutate({tenantId,action:"cancel",matchId:m.id,reason:String(f.get("reason"))});}}><fieldset disabled={busy}><label>{t("Reason to cancel match","سبب إلغاء المطابقة")}<input name="reason" minLength={3} maxLength={300} required/></label><button>{t("Cancel match; retain history","إلغاء المطابقة مع حفظ السجل")}</button></fieldset></form>}</div>)}</article>)}</section>
 {canPost&&!pending&&!state.statement.voidedAt&&<section className="panel"><h2>{t("Correct an imported statement","تصحيح كشف مستورد")}</h2><p>{t("Cancel this statement’s active matches first. Then void it with a reason and import the corrected statement with a new reference. The original statement and match history remain saved.","ألغِ المطابقات السارية لهذا الكشف أولًا، ثم ألغِ الكشف مع السبب واستورد النسخة الصحيحة بمرجع جديد. يبقى الكشف الأصلي وسجل المطابقات محفوظين.")}</p><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void mutate({tenantId,action:"void",reason:String(f.get("reason"))});}}><fieldset disabled={busy}><label>{t("Reason to void the statement","سبب إلغاء الكشف")}<input name="reason" required minLength={3} maxLength={300}/></label><button>{t("Void statement; retain history","إلغاء الكشف مع حفظ السجل")}</button></fieldset></form></section>}
 <section className="panel"><h2>{t("Outstanding book movements","الحركات المحاسبية المعلّقة")}: {state.outstanding.length}</h2>{state.outstanding.slice(page*50,(page+1)*50).map(l=><article className="card" key={l.id}><a href={`/accounting/ledger/journals/${l.entry.id}`}>{l.entry.number}</a><p>{l.entry.entryDate.slice(0,10)} · {l.entry.description} · {l.amount} {state.statement.currency}</p></article>)}{page>0&&<button onClick={()=>setPage(p=>p-1)}>{t("Previous","السابق")}</button>}{(page+1)*50<state.outstanding.length&&<button onClick={()=>setPage(p=>p+1)}>{t("Next","التالي")}</button>}</section></section>;
}
