import {redirect} from "next/navigation";
import {currentUser} from "@/lib/auth";
import {db} from "@/lib/db";
import {readableCompanyPermissions} from "@/lib/access";
import {customerStatement,CustomerStatementError} from "@/lib/customer-statement";
import {getLocale} from "@/lib/server-locale";
import {translate} from "@/lib/locale";
import {LanguageSwitcher} from "../../language-switcher";
export default async function CustomerStatementPage({searchParams}:{searchParams:Promise<Record<string,string|string[]|undefined>>}){
 const actor=await currentUser();if(!actor)redirect("/login");
 const locale=await getLocale(),t=(en:string,ar:string)=>translate(locale,en,ar);
 const memberships=await db.membership.findMany({where:{userId:actor.id,status:"ACTIVE"},include:{tenant:{include:{companies:{include:{branches:true},orderBy:{name:"asc"}}}}}});
 const scopes=(await Promise.all(memberships.flatMap(({tenant})=>tenant.companies.map(async company=>{
  const rights=await readableCompanyPermissions({userId:actor.id,tenantId:tenant.id,companyId:company.id,permissions:["customer:read","order:read","invoice:read","ledger:read"]});
  if(Object.values(rights).some(r=>r===false))return null;
  const invoiceRights=rights["invoice:read"],ledger=rights["ledger:read"];
  return {tenantId:tenant.id,companyId:company.id,value:`${tenant.id}:${company.id}`,label:`${tenant.name} / ${company.name}`,customerBranches:rights["customer:read"],branches:company.branches.filter(b=>(invoiceRights===null||(Array.isArray(invoiceRights)&&invoiceRights.includes(b.id)))&&(ledger===null||(Array.isArray(ledger)&&ledger.includes(b.id))))};
 })))).filter(s=>s!==null);
 const query=await searchParams,value=(key:string)=>typeof query[key]==="string"?query[key] as string:"";
 const scope=scopes.find(s=>s.value===value("scope"))??(query.scope?undefined:scopes[0]);
 const customerId=value("customerId"),q=value("q").slice(0,120),branchId=value("branchId"),today=new Date().toISOString().slice(0,10),from=value("from")||today.slice(0,8)+"01",to=value("to")||today;
 const customers=scope?await db.customer.findMany({where:{tenantId:scope.tenantId,companyId:scope.companyId,...(scope.customerBranches===null?{}:{branchId:{in:Array.isArray(scope.customerBranches)?scope.customerBranches:[]}}),...(q?{OR:[{displayName:{contains:q,mode:"insensitive"}},{code:{contains:q,mode:"insensitive"}}]}:{})},select:{id:true,code:true,displayName:true,archivedAt:true},orderBy:[{displayName:"asc"},{id:"asc"}],take:201}):[];
 let result:Awaited<ReturnType<typeof customerStatement>>|undefined,error="";
 if(scope&&customerId)try{
  if(Object.values(query).some(v=>Array.isArray(v)))throw new CustomerStatementError("Duplicate filter",400);
  result=await customerStatement(actor.id,{tenantId:scope.tenantId,companyId:scope.companyId,customerId,from,to,...(branchId?{branchId}:{})});
 }catch(e){if(e instanceof CustomerStatementError)error=e.status===413?t("The report is too large. Narrow the invoice branch or dates.","الكشف أكبر من الحد المتاح. حدد فرع الفاتورة أو قلّص الفترة."):t("Invalid or unavailable filters. Choose an accessible customer, branch and valid dates.","الفلاتر غير صالحة أو غير متاحة. اختر عميلًا وفرعًا متاحين وتواريخ صحيحة.");else throw e;}
 const selected=result&&!customers.some(s=>s.id===result!.customer.id)?result.customer:null;
 const branchNames=new Map(scope?.branches.map(b=>[b.id,b.name])??[]);
 const csv=scope&&result?`/api/accounting/customer-statement?${new URLSearchParams({tenantId:scope.tenantId,companyId:scope.companyId,customerId,from:result.from,to:result.to,format:"csv",...(branchId?{branchId}:{})})}`:"";
 return <main><style>{`.customer-statement-table{width:100%;min-width:900px;border-collapse:collapse}.customer-statement-table th,.customer-statement-table td{padding:12px;text-align:start;border-bottom:1px solid #ddd}@media print{header,form,.statement-controls{display:none}.hero{padding:20px 0!important}.hero h1{font-size:28px!important}.panel{break-inside:auto}.customer-statement-table{min-width:0;font-size:10px}}`}</style>
 <header><strong>FINAL <span>ARROW</span> ERP</strong><LanguageSwitcher locale={locale}/><a href="/crm">{t("Customers","العملاء")}</a><a href="/accounting/invoices">{t("Invoices","الفواتير")}</a><a href="/accounting/collections">{t("Customer collections", "تحصيلات العملاء")}</a><a href="/accounting/customer-balances">{t("Customer balances","أرصدة العملاء")}</a><a href="/workspace">{t("Workspace","مساحة العمل")}</a></header>
 <section className="hero"><p>{t("ACCOUNTING / CUSTOMERS","المحاسبة / العملاء")}</p><h1>{t("Customer statement.","كشف حساب العميل.")}</h1><p className="sub">{t("Posted invoices, collections, refunds and corrections, by customer and invoice branch.","الفواتير المرحلة والتحصيلات وردّ الدفعات والقيود العكسية، حسب العميل وفرع الفاتورة.")}</p></section>
 <section className="panel"><p>{t("This is a source-journal statement, not a confirmed customer balance. It excludes unposted documents, tax, freight and unrelated manual journals. A positive balance is debit minus credit; currencies remain separate. Journal dates use UTC. Earlier visible journals form the opening balance. Maximum 366 days and 5000 period journals.","هذا كشف للقيود المرتبطة بالمستندات، وليس تأكيدًا لرصيد العميل. يستبعد المستندات غير المرحلة والضرائب والشحن والقيود اليدوية الأخرى. الرصيد الموجب يساوي المدين ناقص الدائن، وتبقى العملات منفصلة. التواريخ حسب تاريخ القيد بتوقيت UTC، والقيود السابقة المتاحة تشكل رصيد البداية. الحد 366 يومًا و5000 قيد في الفترة.")}</p>
 {!scopes.length?<p>{t("No accessible customer statements.","لا توجد كشوف عملاء متاحة بالصلاحيات الحالية.")}</p>:<>
 <form method="get"><label>{t("Company","الشركة")}<select name="scope" defaultValue={scope?.value??""}>{scopes.map(s=><option key={s.value} value={s.value}>{s.label}</option>)}</select></label><button>{t("Select company","اختيار الشركة")}</button></form>
 {scope&&<><form method="get"><input type="hidden" name="scope" value={scope.value}/><label>{t("Find customer by name or code","ابحث عن العميل بالاسم أو الرمز")}<input name="q" maxLength={120} defaultValue={q}/></label><button>{t("Find customer","بحث عن عميل")}</button></form>
 <form method="get"><input type="hidden" name="scope" value={scope.value}/><input type="hidden" name="q" value={q}/><label>{t("Customer","العميل")}<select name="customerId" required defaultValue={customerId}><option value="">{t("Choose customer","اختر العميل")}</option>{selected&&<option value={selected.id}>{selected.code} · {selected.displayName}</option>}{customers.slice(0,200).map(s=><option key={s.id} value={s.id}>{s.code} · {s.displayName}{s.archivedAt?` · ${t("Archived","مؤرشف")}`:""}</option>)}</select></label><label>{t("Invoice branch","فرع الفاتورة")}<select name="branchId" defaultValue={branchId}><option value="">{t("All accessible invoice branches","كل فروع الفواتير المتاحة")}</option>{scope.branches.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></label><label>{t("From","من")}<input type="date" name="from" required defaultValue={from}/></label><label>{t("To","إلى")}<input type="date" name="to" required defaultValue={to}/></label><button>{t("Show statement","عرض الكشف")}</button><a href="/accounting/customer-statement">{t("Reset","إعادة ضبط")}</a></form>
 {customers.length>200&&<p>{t("Showing the first 200 customers. Search by name or code to narrow the list.","تظهر أول 200 نتيجة. ابحث بالاسم أو الرمز لتضييق قائمة العملاء.")}</p>}</>}
 {!scope&&<p role="alert">{t("Choose an accessible company.","اختر شركة متاحة.")}</p>}{error&&<p role="alert">{error}</p>}
 {result&&<><h2>{result.customer.code} · {result.customer.displayName}</h2><p>{result.from} — {result.to} · {result.branchId?branchNames.get(result.branchId):t("All accessible invoice branches","كل فروع الفواتير المتاحة")}</p><p className="statement-controls"><a href={csv}>{t("Download CSV","تنزيل CSV")}</a> · {t("Use browser Print to print or save PDF.","استخدم طباعة المتصفح للطباعة أو حفظ PDF.")}</p>
 {result.summary.map(g=><article className="card" key={g.currency}><strong>{g.currency}</strong><p>{t("Opening","رصيد البداية")}: {g.opening} · {t("Increase","زيادة")}: {g.increase} · {t("Decrease","تخفيض")}: {g.decrease} · {t("Closing","رصيد النهاية")}: {g.closing}</p></article>)}
 <div style={{overflowX:"auto"}}><table className="customer-statement-table"><thead><tr>{[t("Date","التاريخ"),t("Invoice","الفاتورة"),t("Source","المصدر"),t("Journal","القيد"),t("Branch","الفرع"),t("Increase","زيادة"),t("Decrease","تخفيض"),t("Balance","الرصيد"),t("Currency","العملة")].map(label=><th key={label}>{label}</th>)}</tr></thead><tbody>{result.rows.map(r=><tr key={r.id}><td>{r.date}</td><td>{r.invoice}</td><td><a href={`/accounting/invoices/${r.documentId}/settlements`}>{r.kind==="invoice"?t("Invoice","فاتورة"):r.kind==="collection"?t("Collection","تحصيل"):t("Refund","رد دفعة")}</a>{r.reversal&&` · ${t("Reversal","عكسي")}`}</td><td><a href={`/accounting/ledger/journals/${r.id}`}>{r.number}</a></td><td>{r.branchId?(branchNames.get(r.branchId)??r.branchId):t("Company wide","على مستوى الشركة")}</td><td>{r.increase}</td><td>{r.decrease}</td><td>{r.balance}</td><td>{r.currency}</td></tr>)}</tbody></table></div>{!result.rows.length&&<p>{t("No posted source journals in this period.","لا توجد قيود مصدر مرحلة في هذه الفترة.")}</p>}</>}
 </>}</section></main>;
}
